<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chương 2 Ma trận, mảng nhiều chiều và \(list\) | index</title>
<meta name="generator" content="bookdown 0.37 with bs4_book()">
<meta property="og:title" content="Chương 2 Ma trận, mảng nhiều chiều và \(list\) | index">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chương 2 Ma trận, mảng nhiều chiều và \(list\) | index">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/Roboto-0.4.2/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.4.0/transition.js"></script><script src="libs/bs3compat-0.4.0/tabs.js"></script><script src="libs/bs3compat-0.4.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.1/htmlwidgets.js"></script><script src="libs/d3-bundle-5.16.0/d3-bundle.min.js"></script><script src="libs/d3-lasso-0.0.5/d3-lasso.min.js"></script><script src="libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js"></script><script src="libs/flatbush-4.0.0/flatbush.min.js"></script><link href="libs/ggiraphjs-0.4.6/ggiraphjs.min.css" rel="stylesheet">
<script src="libs/ggiraphjs-0.4.6/ggiraphjs.min.js"></script><script src="libs/girafe-binding-0.8.8/girafe.js"></script><script src="libs/plotly-binding-4.10.1/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<meta name="description" content="Trong cuốn sách này chúng tôi cố gắng tránh nhắc đến các khái niệm toán học phức tạp bởi đối tượng chúng tôi hướng đến là những người làm việc với dữ liệu nhưng không có một nền tảng chuyên sâu về...">
<meta property="og:description" content="Trong cuốn sách này chúng tôi cố gắng tránh nhắc đến các khái niệm toán học phức tạp bởi đối tượng chúng tôi hướng đến là những người làm việc với dữ liệu nhưng không có một nền tảng chuyên sâu về...">
<meta name="twitter:description" content="Trong cuốn sách này chúng tôi cố gắng tránh nhắc đến các khái niệm toán học phức tạp bởi đối tượng chúng tôi hướng đến là những người làm việc với dữ liệu nhưng không có một nền tảng chuyên sâu về...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title=""></a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Kiến thức R cơ bản</a></li>
<li><a class="active" href="ma-tr%E1%BA%ADn-m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u-v%C3%A0-list.html"><span class="header-section-number">2</span> Ma trận, mảng nhiều chiều và \(list\)</a></li>
<li><a class="" href="ph%C3%A2n-t%C3%ADch-d%E1%BB%AF-li%E1%BB%87u-b%E1%BA%B1ng-r.html"><span class="header-section-number">3</span> Phân tích dữ liệu bằng R</a></li>
<li><a class="" href="nh%E1%BA%ADp-d%E1%BB%AF-li%E1%BB%87u-t%E1%BB%AB-c%C3%A1c-ngu%E1%BB%93n-kh%C3%A1c-nhau-v%C3%A0o-r.html"><span class="header-section-number">4</span> Nhập dữ liệu từ các nguồn khác nhau vào R</a></li>
<li><a class="" href="ti%E1%BB%81n-x%E1%BB%AD-l%C3%BD-d%E1%BB%AF-li%E1%BB%87u.html"><span class="header-section-number">5</span> Tiền xử lý dữ liệu</a></li>
<li><a class="" href="bi%E1%BA%BFn-%C4%91%E1%BB%95i-d%E1%BB%AF-li%E1%BB%87u-b%E1%BA%B1ng-th%C6%B0-vi%E1%BB%87n-dplyr.html"><span class="header-section-number">6</span> Biến đổi dữ liệu bằng thư viện \(dplyr\)</a></li>
<li><a class="" href="tr%E1%BB%B1c-quan-h%C3%B3a-d%E1%BB%AF-li%E1%BB%87u.html"><span class="header-section-number">7</span> Trực quan hóa dữ liệu</a></li>
<li><a class="" href="tr%E1%BB%B1c-quan-h%C3%B3a-d%E1%BB%AF-li%E1%BB%87u-1.html"><span class="header-section-number">8</span> Trực quan hóa dữ liệu</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-h%E1%BB%93i-quy-tuy%E1%BA%BFn-t%C3%ADnh.html"><span class="header-section-number">9</span> Mô hình hồi quy tuyến tính</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html"><span class="header-section-number">10</span> Mô hình tuyến tính tổng quát.</a></li>
<li><a class="" href="reference.html"><span class="header-section-number">11</span> REFERENCE</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-d%E1%BA%A1ng-c%C3%A2y.html"><span class="header-section-number">12</span> Mô hình dạng cây</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-m%E1%BA%A1ng-neural-network.html"><span class="header-section-number">13</span> Mô hình mạng neural network</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/dgrtwo/tidy-text-mining">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="ma-trận-mảng-nhiều-chiều-và-list" class="section level1" number="2">
<h1>
<span class="header-section-number">Chương 2</span> Ma trận, mảng nhiều chiều và <span class="math inline">\(list\)</span><a class="anchor" aria-label="anchor" href="#ma-tr%E1%BA%ADn-m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u-v%C3%A0-list"><i class="fas fa-link"></i></a>
</h1>
<p>Trong cuốn sách này chúng tôi cố gắng tránh nhắc đến các khái niệm toán học phức tạp bởi đối tượng chúng tôi hướng đến là những người làm việc với dữ liệu nhưng không có một nền tảng chuyên sâu về toán học. Tuy nhiên để làm việc được với dữ liệu thì các kiến thức về ma trận nói riêng và kiến thức về đại số tuyến tính nói chung là bắt buộc phải nắm vững. Điều đáng tiếc là tại thời điểm chúng tôi viết cuốn sách này, đa số các chương trình đào tạo dành cho sinh viên các ngành kinh tế đang cắt giảm dần kiến thức về toán học và đặc biệt là kiến thức đại số tuyến tính.</p>
<div id="ma-trận" class="section level2" number="2.1">
<h2>
<span class="header-section-number">2.1</span> Ma trận<a class="anchor" aria-label="anchor" href="#ma-tr%E1%BA%ADn"><i class="fas fa-link"></i></a>
</h2>
<p>Ma trận có ý nghĩa đặc biệt quan trọng trong phân tích dữ liệu bởi đa số các dữ liệu đều được chuyển thành kiểu ma trận để dễ dàng phân tích và tính toán. Cũng giống như véc-tơ, ma trận là một đối tượng dùng để lưu các biến có cùng kiểu. Khác với véc-tơ, ma trận lưu phần tử theo hàng và cột, nghĩa là trong không gian hai chiều trong khi véc-tơ lưu phần tử trong không gian một chiều. Bạn đọc cũng có thể hiểu véc-tơ là một cột trong khi ma trận là tập hợp của các cột có cùng độ dài. Kích thước của một véc-tơ là chiều dài của véc-tơ đó trong khi kích thước của một ma trận là số hàng và số cột của ma trận đó.</p>
<div id="khởi-tạo-ma-trận" class="section level3" number="2.1.1">
<h3>
<span class="header-section-number">2.1.1</span> Khởi tạo ma trận<a class="anchor" aria-label="anchor" href="#kh%E1%BB%9Fi-t%E1%BA%A1o-ma-tr%E1%BA%ADn"><i class="fas fa-link"></i></a>
</h3>
<p>Hàm số dùng để tạo ra ma trận trong R là hàm <code><a href="https://rdrr.io/r/base/matrix.html">matrix()</a></code>. Khi tạo ma trận, bạn đọc sẽ luôn luôn phải khởi tạo giá trị cho ma trận đó. Đoạn lệnh sau sẽ khởi tạo một ma trận có tên là <span class="math inline">\(M\)</span>, có 3 hàng, 4 cột, và giá trị trong ma trận là các số tự nhiên từ 1 đến 12 được sắp xếp theo thứ tự</p>
<div class="sourceCode" id="cb256"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="co"># nrow: số hàng, ncol: số cột</span></span>
<span><span class="va">M</span> <span class="co"># in M ra của sổ console</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    4    7   10
## [2,]    2    5    8   11
## [3,]    3    6    9   12</code></pre>
<p>Các giá trị dùng để khởi tạo cho ma trận là các số từ 1 đến 12 và được điền vào ma trận <span class="math inline">\(M\)</span> theo nguyên tắc từ trên xuống dưới rồi từ trái sang phải, nghĩa là cột thứ nhất sẽ được ưu tiên cho giá trị trước; phần tử hàng thứ nhất của cột thứ nhất sẽ được điền giá trị trước, sau đó đến phần tử ở hàng thứ hai của cột thứ nhất, …; sau khi hết cột thứ nhất R sẽ tiếp tục điền vào giá trị ở hàng thứ nhất của cột thứ hai,…, và cứ tiếp tục như thế sau khi tất cả các phần tử trong ma trận đều có giá trị. Véc-tơ dùng đề khởi tạo giá trị cho ma trận có độ dài 12 vừa đúng với số phần tử trong ma trận nên câu lệnh tạo ma trận <span class="math inline">\(M\)</span> ở trên hoạt động bình thường. Trong trường hợp bạn đọc sử dụng véc-tơ có độ dài khác 12 để khởi tạo giá trị cho ma trận, câu lệnh vẫn sẽ chạy nhưng có kèm theo cảnh báo:</p>
<div class="sourceCode" id="cb258"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">13</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="co"># Code chạy kèm theo cảnh báo; </span></span>
<span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">5</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="co"># Code chạy kèm theo cảnh báo; </span></span></code></pre></div>
<p>Bạn đọc có thể thấy rằng:</p>
<ul>
<li><p>Nếu véc-tơ dùng để khởi tạo giá trị cho ma trận <span class="math inline">\(M\)</span> có độ dài lớn hơn 12, R sẽ dùng 12 giá trị đầu tiên để khởi tạo giá trị cho ma trận.</p></li>
<li><p>Nếu véc-tơ dùng để khởi tạo giá trị cho ma trận <span class="math inline">\(M\)</span> có độ dài nhỏ hơn 12, R sẽ lặp lại véc-tơ đó cho đến khi có độ dài lớn hơn hoặc bằng 12 rồi sau đó dùng 12 giá trị đầu tiên để khởi tạo giá trị cho ma trận.</p></li>
</ul>
<p>Khi khởi tạo ma trận, bạn đọc có thể yêu cầu giá trị được khởi tạo theo hàng thay vì theo cột bằng tùy biến <span class="math inline">\(byrow = TRUE\)</span> trong hàm <code><a href="https://rdrr.io/r/base/matrix.html">matrix()</a></code>.</p>
<div class="sourceCode" id="cb259"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="co"># nrow: số hàng, ncol: số cột</span></span>
<span><span class="va">M</span> <span class="co"># in M ra của sổ console</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    5    6    7    8
## [3,]    9   10   11   12</code></pre>
<p>Để biết kích cỡ của ma trận, chúng ta sử dụng hàm <code><a href="https://rdrr.io/r/base/dim.html">dim()</a></code>. Hàm <code><a href="https://rdrr.io/r/base/dim.html">dim()</a></code> trên ma trận sẽ trả lại giá trị là một véc-tơ kiểu số có độ dài là hai, phần tử thứ nhất là số hàng, phần tử thứ hai là số cột của ma trận</p>
<div class="sourceCode" id="cb261"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span> <span class="co"># ma trận 3 hàng 4 cột</span></span></code></pre></div>
<pre><code>## [1] 3 4</code></pre>
<p>Ma trận cũng có thể được khởi tạo bằng cách ghép các véc-tơ hoặc các ma trận khác theo hàng hay theo cột bằng các hàm <code><a href="https://rdrr.io/r/base/cbind.html">cbind()</a></code> hoặc <code><a href="https://rdrr.io/r/base/cbind.html">rbind()</a></code>:</p>
<ul>
<li><p>Hàm <code><a href="https://rdrr.io/r/base/cbind.html">cbind()</a></code> nối các ma trận có cùng số hàng hoặc ma trận với véc-tơ có độ dài bằng số hàng của ma trận.</p></li>
<li><p>Tương tự, <code><a href="https://rdrr.io/r/base/cbind.html">rbind()</a></code> nối các ma trận có cùng số cột hoặc ma trận với véc-tơ có độ dài bằng số cột của ma trận.</p></li>
</ul>
<div class="sourceCode" id="cb263"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">M</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="co"># ghép THEO CỘT, ma trận M (3 hàng, 4 cột) với véc-tơ độ dài 3</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5]
## [1,]    1    2    3    4    1
## [2,]    5    6    7    8    1
## [3,]    9   10   11   12    1</code></pre>
<div class="sourceCode" id="cb265"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">M</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span> <span class="co"># ghép THEO HÀNG, ma trận M (3 hàng, 4 cột) với véc-tơ độ dài 4</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    5    6    7    8
## [3,]    9   10   11   12
## [4,]    1    1    1    1</code></pre>
<p>Các phép tính toán thông thường trên ma trận cũng có nguyên tắc giống như đối với véc-tơ. Các phép toán như cộng, trừ, nhân, chia, lũy thừa, …, sẽ tác động lên tất cả các phần tử trong ma trận theo thứ tự của các phần tử xuất hiện trên ma trận. Bạn đọc hãy quan sát kết quả của các ví dụ sau để hiểu cách R thực hiện các phép toán trên ma trận</p>
<p>Nhân ma trận <span class="math inline">\(M\)</span> kích thước <span class="math inline">\(3 \times 4\)</span> với một số</p>
<div class="sourceCode" id="cb267"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="va">M</span> <span class="op">*</span> <span class="fl">2</span> <span class="co"># in M*2 ra của sổ console</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    2    8   14   20
## [2,]    4   10   16   22
## [3,]    6   12   18   24</code></pre>
<p>Bạn đọc có thể thấy rằng kết quả nhận được là một ma trận có kích thước bằng với kích thước của ma trận <span class="math inline">\(M\)</span> và mỗi phần tử bằng phần tử ở vị trí tương ứng của ma trận <span class="math inline">\(M\)</span> nhân với 2.</p>
<p>Khi thực hiện phép nhân thông thường ma trận <span class="math inline">\(M\)</span> với một ma trận <span class="math inline">\(M_1\)</span> có cùng kích thước thì kết quả nhận được là một ma trận mà mỗi phần tử bằng tích của 2 phần tử ở vị trí tương ứng của <span class="math inline">\(M\)</span> và <span class="math inline">\(M_1\)</span>. R sẽ báo lỗi nếu thực hiện phép nhân thông thường giữa hai ma trận không có cùng kích thước.</p>
<div class="sourceCode" id="cb269"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="va">M1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span>,<span class="fl">6</span><span class="op">)</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="va">M</span> <span class="op">*</span> <span class="va">M1</span><span class="co"># in M * M1 ra của sổ console</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    0    4    0   10
## [2,]    2    0    8    0
## [3,]    0    6    0   12</code></pre>
<p>Phép nhân thông thường cũng có thể được thực hiện giữa ma trận <span class="math inline">\(M\)</span> với một véc-tơ có độ dài nhỏ hơn hoặc bằng số phần tử của <span class="math inline">\(M\)</span>. Trước khi thực hiệp phép nhân, R sẽ chuyển các phần tử trong véc-tơ vào một ma trận có kích thước tương ứng với <span class="math inline">\(M\)</span> sau đó thực hiện phép nhân giống như nhân hai ma trận có cùng kích thước:</p>
<div class="sourceCode" id="cb271"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="va">x</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">2</span>,<span class="op">-</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span> <span class="co"># véc-tơ độ dài 5</span></span>
<span><span class="va">M</span> <span class="op">*</span> <span class="va">x</span> <span class="co"># phép nhân được thực hiện mà không báo lỗi</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]   -2    4   -7   20
## [2,]   -2   10    0  -22
## [3,]    0  -12    9  -12</code></pre>
<p>Khi thực hiện tính toán như trên, R đã tự động lặp lại <span class="math inline">\(x\)</span> cho đến khi số lượng phần tử bằng với số phần tử của <span class="math inline">\(M\)</span>, điền các giá trị này vào một ma trận có kích thước bằng với kích thước của <span class="math inline">\(M\)</span> rồi sau đó thực hiện phép nhân. Thật vậy</p>
<div class="sourceCode" id="cb273"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">y</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">x</span>,<span class="fl">3</span><span class="op">)</span> <span class="co"># lặp lại x cho đến khi số phần tử của véc-tơ thu được lớn hơn 12</span></span>
<span><span class="va">M1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span><span class="op">]</span>,nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="co"># dùng 12 giá trị ban đầu để tạo thành ma trận có cùng kích thước 3*4</span></span>
<span><span class="va">M</span> <span class="op">*</span> <span class="va">M1</span> <span class="co"># kết quả giống như M * x</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]   -2    4   -7   20
## [2,]   -2   10    0  -22
## [3,]    0  -12    9  -12</code></pre>
</div>
<div id="cách-lấy-phần-tử-con-và-ma-trận-con-của-ma-trận." class="section level3" number="2.1.2">
<h3>
<span class="header-section-number">2.1.2</span> Cách lấy phần tử con và ma trận con của ma trận.<a class="anchor" aria-label="anchor" href="#c%C3%A1ch-l%E1%BA%A5y-ph%E1%BA%A7n-t%E1%BB%AD-con-v%C3%A0-ma-tr%E1%BA%ADn-con-c%E1%BB%A7a-ma-tr%E1%BA%ADn."><i class="fas fa-link"></i></a>
</h3>
<p>Tương tự như với véc-tơ, chúng ta sử dụng <span class="math inline">\([]\)</span> để lấy phần tử con trong ma trận. Khác với véc-tơ, ma trận có chỉ số hàng và chỉ số cột nên chúng ta cần cho biết phần tử được lấy ra ở hàng thứ bao nhiêu và cột thứ bao nhiêu:</p>
<div class="sourceCode" id="cb275"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">[</span><span class="fl">2</span>,<span class="fl">3</span><span class="op">]</span> <span class="co"># phần tử ở hàng thứ hai, cột thứ ba của ma trận M</span></span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<p>Chúng ta cũng có thể lấy ra véc-tơ hàng hoặc véc-tơ cột của ma trận bằng cách sau</p>
<div class="sourceCode" id="cb277"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">[</span>,<span class="fl">3</span><span class="op">]</span> <span class="co"># lấy ra véc-tơ cột thứ 3 của ma trận M</span></span></code></pre></div>
<pre><code>## [1] 7 8 9</code></pre>
<div class="sourceCode" id="cb279"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">[</span><span class="fl">2</span>,<span class="op">]</span> <span class="co"># lấy ra véc-tơ hàng thứ 2 của ma trận M</span></span></code></pre></div>
<pre><code>## [1]  2  5  8 11</code></pre>
<p>Để lấy ra một ma trận con của một ma trận, chúng ta cũng tạo véc-tơ chỉ số giống như cách tạo chỉ số với véc-tơ. Thay vì chỉ tạo một véc-tơ chỉ số duy nhất như khi làm với véc-tơ, chúng ta cần tạo một véc-tơ chỉ số theo hàng và một véc-tơ chỉ số theo cột. Bạn đọc có thể tạo chỉ số bằng một véc-tơ kiểu số hoặc véc-tơ kiểu logical hoặc kết hợp cả hai phương pháp này</p>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">chi_so_hang</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="cn">TRUE</span>,<span class="cn">FALSE</span>,<span class="cn">TRUE</span><span class="op">)</span> <span class="co"># Chỉ số theo hàng kiểu logical</span></span>
<span><span class="va">chi_so_cot</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">4</span><span class="op">)</span> <span class="co"># chỉ số cột theo kiểu số</span></span>
<span><span class="va">M</span><span class="op">[</span><span class="va">chi_so_hang</span>,<span class="va">chi_so_cot</span><span class="op">]</span> <span class="co"># ma trận con của ma trận M</span></span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    4   10
## [2,]    6   12</code></pre>
</div>
<div id="các-phép-toán-trên-ma-trận." class="section level3" number="2.1.3">
<h3>
<span class="header-section-number">2.1.3</span> Các phép toán trên ma trận.<a class="anchor" aria-label="anchor" href="#c%C3%A1c-ph%C3%A9p-to%C3%A1n-tr%C3%AAn-ma-tr%E1%BA%ADn."><i class="fas fa-link"></i></a>
</h3>
<p>Các phép toán trên ma trận có ý nghĩa đặc biệt trong phân tích dữ liệu. Ở các chương sách tiếp theo bạn đọc sẽ thấy rằng tất cả các tính toán nhằm biến đổi dữ liệu, hoặc ước lượng tham số cho các mô hình trên dữ liệu đều dựa trên các phép tính toán trên ma trận. Chúng tôi sẽ giải thích các phép toán này một cách đơn giản nhất để những bạn đọc không có nền tảng chuyên sâu về toán cũng có thể hiểu được. Tuy nhiên, để có kỹ năng thành thạo trong biến đổi dữ liệu, phân tích dữ liệu, và xây dựng các mô hình trên dữ liệu, chúng tôi khuyên bạn đọc nên tự trang bị cho mình các kiến thức về đại số tuyến tính và giải tích véc-tơ.</p>
<div id="phép-chuyển-vị." class="section level4" number="2.1.3.1">
<h4>
<span class="header-section-number">2.1.3.1</span> Phép chuyển vị.<a class="anchor" aria-label="anchor" href="#ph%C3%A9p-chuy%E1%BB%83n-v%E1%BB%8B."><i class="fas fa-link"></i></a>
</h4>
<p>Phép toán chuyển vị (transpose) là một phép toán biến đổi một ma trận <span class="math inline">\(M\)</span> kích thước <span class="math inline">\(n \times p\)</span> (<span class="math inline">\(n\)</span> hàng và <span class="math inline">\(p\)</span> cột) thành một ma trận mới, ký hiệu là <span class="math inline">\(M^T\)</span>, có kích thước <span class="math inline">\(p \times n\)</span> (<span class="math inline">\(p\)</span> hàng và <span class="math inline">\(n\)</span> cột), đồng thời phần tử hàng thứ <span class="math inline">\(j\)</span> và cột thứ <span class="math inline">\(i\)</span> của ma trận <span class="math inline">\(M^T\)</span> bằng phần tử ở hàng thứ <span class="math inline">\(i\)</span> và cột thứ <span class="math inline">\(j\)</span> của ma trận <span class="math inline">\(M\)</span>.</p>
<p><span class="math display">\[\begin{align}
\begin{bmatrix}
m_{11} &amp; m_{12} &amp; m_{13}\\
m_{21} &amp; m_{22} &amp; m_{23}
\end{bmatrix}

\xrightarrow[\text{(transpose)}]{\text{chuyển vị}}

\begin{bmatrix}
m_{11} &amp; m_{21} \\
m_{12} &amp; m_{22} \\
m_{13} &amp; m_{23}
\end{bmatrix}

\end{align}\]</span></p>
<p>Hàm số để thực hiện phép chuyển vị ma trận trong R là hàm <code><a href="https://rdrr.io/r/base/t.html">t()</a></code></p>
<div class="sourceCode" id="cb283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="co"># nrow: số hàng, ncol: số cột</span></span>
<span><span class="va">M</span> <span class="co"># in M ra của sổ console</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    5    6    7    8
## [3,]    9   10   11   12</code></pre>
<div class="sourceCode" id="cb285"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span> <span class="co"># ma trận chuyển vị của ma trận </span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    5    9
## [2,]    2    6   10
## [3,]    3    7   11
## [4,]    4    8   12</code></pre>
<p>Bạn đọc có thể thấy rằng nếu thực hiện phép chuyển vị hai lần liên tiếp ta sẽ thu được ma trận ban đầu</p>
<div class="sourceCode" id="cb287"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span><span class="op">)</span> <span class="co"># ma trận chuyển vị của ma trận chuyển vị là ma trận ban đầu </span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    5    6    7    8
## [3,]    9   10   11   12</code></pre>
</div>
</div>
<div id="phép-nhân-ma-trận" class="section level3" number="2.1.4">
<h3>
<span class="header-section-number">2.1.4</span> Phép nhân ma trận<a class="anchor" aria-label="anchor" href="#ph%C3%A9p-nh%C3%A2n-ma-tr%E1%BA%ADn"><i class="fas fa-link"></i></a>
</h3>
<p>Phép nhân ma trận (matrix multiplication) của ma trận <span class="math inline">\(A\)</span> với ma trận <span class="math inline">\(B\)</span> chỉ thực hiện được nếu số cột của ma trận <span class="math inline">\(A\)</span> bằng với số hàng của ma trận <span class="math inline">\(B\)</span>. Giả sử rằng <span class="math inline">\(A\)</span> có kích thước là <span class="math inline">\(n \times p\)</span> và <span class="math inline">\(B\)</span> có kích thước là <span class="math inline">\(p \times k\)</span> thì kết quả của phép nhân ma trận của ma trận <span class="math inline">\(A\)</span> với ma trận <span class="math inline">\(B\)</span> là một ma trận <span class="math inline">\(M\)</span> có kích thước <span class="math inline">\(n \times k\)</span>, phần tử ở hàng thứ <span class="math inline">\(i\)</span> và cột thứ <span class="math inline">\(j\)</span> của ma trận <span class="math inline">\(M\)</span> là tích vô hướng giữa véc-tơ hàng <span class="math inline">\(i\)</span> của ma trận <span class="math inline">\(A\)</span> và véc-tơ cột <span class="math inline">\(j\)</span> của ma trận <span class="math inline">\(B\)</span>. Nhắc lại với bạn đọc rằng tích vô hướng của hai véc-tơ <span class="math inline">\(x\)</span> và <span class="math inline">\(y\)</span> (phải) có cùng độ dài <span class="math inline">\(n\)</span> được ký hiệu là <span class="math inline">\(&lt;x,y&gt;\)</span> và được tính như sau</p>
<p><span class="math display">\[\begin{align}
&lt;x,y&gt; = \sum\limits_{i = 1}^n \ x_i y_i
\end{align}\]</span></p>
<p>trong đó <span class="math inline">\(x_i\)</span>, <span class="math inline">\(y_i\)</span> lần lượt là phần tử thứ <span class="math inline">\(i\)</span> của véc-tơ <span class="math inline">\(x\)</span> và véc-tơ <span class="math inline">\(y\)</span>. Để phân biệt với phép nhân thông thường, chúng tôi sử dụng ký hiệu <span class="math inline">\(*\)</span> cho phép nhân ma trận mà chỉ đơn giản ký hiệu phép nhân ma trận giữa ma trận <span class="math inline">\(A\)</span> và ma trận <span class="math inline">\(B\)</span> là <span class="math inline">\(AB\)</span>. Công thức dưới đây mô tả phép nhân ma trận giữa một ma trận có 2 hàng và 3 cột với một ma trận có 3 hàng và 4 cột để được một ma trận có kích thước là 2 hàng và 4 cột</p>
<p><span class="math display">\[\begin{align}
&amp;&amp; AB = M \\

&amp;&amp;

\begin{bmatrix}
a_{11} &amp; a_{12} &amp; a_{13}\\
a_{21} &amp; a_{22} &amp; a_{23}
\end{bmatrix}

\% * \%

\begin{bmatrix}
b_{11} &amp; b_{12} &amp; b_{13} &amp; b_{14} \\
b_{21} &amp; b_{22} &amp; b_{23} &amp; b_{24} \\
b_{31} &amp; b_{32} &amp; b_{33} &amp; b_{34}
\end{bmatrix}

=

\begin{bmatrix}
m_{11} &amp; m_{12} &amp; m_{13} &amp; m_{14} \\
m_{21} &amp; m_{22} &amp; m_{23} &amp; m_{24} \\
\end{bmatrix} \\

&amp;&amp; m_{ij} = &lt;A[i,],B[,j]&gt;

\end{align}\]</span>
trong đó <span class="math inline">\(A[i,]\)</span> là véc-tơ hàng <span class="math inline">\(i\)</span> của ma trận <span class="math inline">\(A\)</span> và <span class="math inline">\(B[,j]\)</span> là véc-tơ cột <span class="math inline">\(j\)</span> của ma trận <span class="math inline">\(B\)</span>.</p>
<p>Toán tử dùng để thực hiện phép nhân ma trận trong R là <span class="math inline">\(\% * \%\)</span>. Bạn đọc có thể thực hiện phép nhân hai ma trận <span class="math inline">\(A\)</span> và <span class="math inline">\(B\)</span> như sau</p>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">A</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">6</span>, nrow <span class="op">=</span> <span class="fl">2</span>, ncol <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="co"># ma trận kích thước 2 * 3</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">A</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<div class="sourceCode" id="cb291"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">B</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">12</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="co"># ma trận kích thước 3 * 4</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">B</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    4    7   10
## [2,]    2    5    8   11
## [3,]    3    6    9   12</code></pre>
<div class="sourceCode" id="cb293"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span> <span class="op">&lt;-</span> <span class="va">A</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">B</span> <span class="co"># kết quả là ma trận M có kich thước 2 * 4</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]   22   49   76  103
## [2,]   28   64  100  136</code></pre>
<p>Chúng ta có thể kiểm tra giá trị của phần tử ở hàng thứ 2 và cột thứ 3 của ma trận kết quả (số 100) chính là tích vô hướng giữa véc-tơ hàng thứ hai của ma trận <span class="math inline">\(A\)</span> và véc-tơ cột thứ ba của ma trận <span class="math inline">\(B\)</span>.</p>
<p><span class="math display">\[\begin{align}
&lt;(2,4,6),(7,8,9)&gt; &amp;=&amp; 2 \times 7 + 4 \times 8 + 6 \times 9 \\
&amp;=&amp; 100
\end{align}\]</span></p>
<p>Bạn đọc cần phân biệt giữa phép nhân ma trận (ký hiệu <span class="math inline">\(\% * \%\)</span>) và phép nhân thông thường (ký hiệu <span class="math inline">\(*\)</span>) như đã trình bày ở trên. Để tránh gây nhầm lẫn, chúng tôi luôn sử dụng cụm từ nhân ma trận cho phép nhân <span class="math inline">\(\% * \%\)</span>.</p>
</div>
<div id="ma-trận-đường-chéo-và-ma-trận-đơn-vị." class="section level3" number="2.1.5">
<h3>
<span class="header-section-number">2.1.5</span> Ma trận đường chéo và ma trận đơn vị.<a class="anchor" aria-label="anchor" href="#ma-tr%E1%BA%ADn-%C4%91%C6%B0%E1%BB%9Dng-ch%C3%A9o-v%C3%A0-ma-tr%E1%BA%ADn-%C4%91%C6%A1n-v%E1%BB%8B."><i class="fas fa-link"></i></a>
</h3>
<p>Các khái niệm và phép toán trên ma trận được trình bày từ phần này sẽ chỉ áp dụng trên ma trận vuông, nghĩa là ma trận có số hàng bằng với số cột. Trong một ma trận vuông, các phần tử nằm trên đường chéo <span class="math inline">\(chính\)</span> là các phần tử có chỉ số hàng bằng với chỉ số cột, các phần tử nằm trên đường chéo <span class="math inline">\(phụ\)</span> là các phần tử có chỉ số hàng cộng với chỉ số cột bằng <span class="math inline">\((n+1)\)</span> trong đó <span class="math inline">\(n\)</span> là số hàng. Với ma trận vuông <span class="math inline">\(M\)</span> có kích thước <span class="math inline">\(n \times n\)</span> đường chéo chính của ma trận được ký hiệu là <span class="math inline">\(diag(M)\)</span> xác định như sau</p>
<p><span class="math display">\[\begin{align}
M
=
\begin{bmatrix}
m_{11} &amp; m_{12} &amp; m_{13} &amp; m_{14} \\
m_{21} &amp; m_{22} &amp; m_{23} &amp; m_{24} \\
m_{31} &amp; m_{32} &amp; m_{33} &amp; m_{34}\\
m_{41} &amp; m_{42} &amp; m_{43} &amp; m_{44}
\end{bmatrix} \\

diag(M) = (m_{11}, m_{22}, m_{33},  m_{44})

\end{align}\]</span></p>
<p>Ma trận có tất cả các phần tử nằm <span class="math inline">\(ngoài\)</span> đường chéo chính bằng 0 được gọi là ma trận đường chéo. Hàm <code><a href="https://rdrr.io/r/base/diag.html">diag()</a></code> trong R được sử dụng để lấy ra véc-tơ đường chéo chính của một ma trận vuông và để tạo ra một ma trận đường chéo hoặc cũng có thể dùng để khai báo một ma trận đường chéo.</p>
<div class="sourceCode" id="cb295"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">9</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="co"># ma trận vuông 3 * 3</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    4    7
## [2,]    2    5    8
## [3,]    3    6    9</code></pre>
<div class="sourceCode" id="cb297"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span> <span class="co"># lấy ra véc-tơ đường chéo chính của M</span></span></code></pre></div>
<pre><code>## [1] 1 5 9</code></pre>
<div class="sourceCode" id="cb299"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">10</span>,<span class="fl">100</span><span class="op">)</span><span class="op">)</span> <span class="co"># tạo ra ma trận đường chéo có đường chéo chính là (1,10,100)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">M1</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]    0   10    0
## [3,]    0    0  100</code></pre>
<p>Ma trận đơn vị kích thước <span class="math inline">\(n \times n\)</span>, thường được ký hiệu <span class="math inline">\(I_n\)</span>, là một ma trận đường chéo mà tất cả các phần tử trên đường chéo chính bằng 1. Ma trận đơn vị <span class="math inline">\(I_n\)</span> có tính chất quan trọng là mọi ma trận <span class="math inline">\(M\)</span> kích thước <span class="math inline">\(k \times n\)</span> khi thực hiện phép nhân ma trận với ma trận <span class="math inline">\(I_n\)</span> sẽ được kết quả đúng bằng ma trận <span class="math inline">\(M\)</span>. Bạn đọc có thể quan sát ví dụ sau</p>
<div class="sourceCode" id="cb301"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">In</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span> <span class="co"># ma trận đơn vị kích thước 4*4</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">In</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    0    0    0
## [2,]    0    1    0    0
## [3,]    0    0    1    0
## [4,]    0    0    0    1</code></pre>
<div class="sourceCode" id="cb303"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">20</span>, nrow <span class="op">=</span> <span class="fl">5</span>, ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> <span class="co"># ma trận vuông 5 * 4</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">M</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">In</span><span class="op">)</span> <span class="co"># kết quả vẫn là ma trận M</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    6   11   16
## [2,]    2    7   12   17
## [3,]    3    8   13   18
## [4,]    4    9   14   19
## [5,]    5   10   15   20</code></pre>
</div>
<div id="định-thức-của-ma-trận" class="section level3" number="2.1.6">
<h3>
<span class="header-section-number">2.1.6</span> Định thức của ma trận<a class="anchor" aria-label="anchor" href="#%C4%91%E1%BB%8Bnh-th%E1%BB%A9c-c%E1%BB%A7a-ma-tr%E1%BA%ADn"><i class="fas fa-link"></i></a>
</h3>
<p>Định thức của ma trận là một khái niệm toán học phức tạp. Phần lớn bạn đọc khi làm quen với khái niệm định thức trong môn học đại số tuyến tính sẽ được giới thiệu về công thức tính định thức của một ma trận, hoặc sử dụng định thức của ma trận để thực hiện tính toán như giải hệ phương trình thay vì thực sự hiểu khái niệm định thức được bắt đầu từ đâu. Định thức là một giá trị số thực đặc trưng của một ma trận vuông. Định thức cho biết nhiều tính chất quan trọng của ma trận đó, đồng thời định thức xuất hiện trong rất nhiều tính toán liên quan đến ma trận.</p>
<p>Hãy bắt đầu với một ma trận vuông <span class="math inline">\(M\)</span> kích thước <span class="math inline">\(2 \times 2\)</span> như sau:
<span class="math display">\[\begin{align}
M
=
\begin{bmatrix}
m_{11} &amp; m_{12}\\
m_{21} &amp; m_{22}
\end{bmatrix}
\end{align}\]</span></p>
<p>Định thức của ma trận <span class="math inline">\(M\)</span> được ký hiệu là <span class="math inline">\(|M|\)</span> hoặc <span class="math inline">\(det(M)\)</span> được xác định bởi công thức
<span class="math display">\[\begin{align}
det(M) = m_{11} \times m_{22} - m_{12} \times m_{21}
\end{align}\]</span></p>
<p>Định thức của ma trận <span class="math inline">\(M\)</span> có thể biểu diễn dưới dạng diện tích của hình bình hành tạo thành từ 4 điểm có tọa độ <span class="math inline">\((0,0)\)</span>, <span class="math inline">\((m_{11},m_{12})\)</span>, <span class="math inline">\((m_{21},m_{22})\)</span>, và <span class="math inline">\((m_{11}+m_{21}, m_{12}+m_{22})\)</span>. Thật vậy, giả sử hai ma trận <span class="math inline">\(M\)</span> và <span class="math inline">\(M_1\)</span> có kích thước <span class="math inline">\(2 \times 2\)</span>; ma trận <span class="math inline">\(M_1\)</span> nhận được bằng cách đổi vị trí 2 dòng của ma trận <span class="math inline">\(M\)</span></p>
<p><span class="math display">\[\begin{align}
M
=
\begin{bmatrix}
2 &amp; 1 \\
1 &amp; 3
\end{bmatrix}  \text{  và  } M_1
=
\begin{bmatrix}
1 &amp; 3 \\
2 &amp; 1
\end{bmatrix} \\

det(M) = 5  \text{  và  } det(M_1) = -5

\end{align}\]</span></p>
<p>Chúng ta có thể biểu diễn định thức của <span class="math inline">\(M\)</span> và <span class="math inline">\(M_1\)</span> qua diện tích của các hình bình hành như hình vẽ dưới đây:</p>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-143-1.png" width="960" style="display: block; margin: auto;"></div>
<p>Giá trị của định thức sẽ cho ta biết thông tin về các véc-tơ tạo nên ma trận:</p>
<ul>
<li><p>Định thức bằng 0 chỉ xảy ra khi hai véc-tơ (hai mũi tên màu xanh và màu đỏ xuất phát từ điểm <span class="math inline">\((0,0)\)</span>) trùng nhau hoặc đối đỉnh nhau. Điều này chỉ xảy ra khi véc-tơ thứ nhất bằng véc-tơ thứ hai nhân với một số. Trong trường hợp tổng quát với ma trận vuông kích thước <span class="math inline">\(n \times n\)</span>, định thức bằng 0 khi một véc-tơ nào đó là tổ hợp tuyến tính của các véc-tơ còn lại.</p></li>
<li><p>Định thức gần bằng 0 nghĩa là góc tạo bởi 2 véc-tơ rất gần 0 hoặc tạo với nhau một góc xấp xỉ 180 độ. Ma trận vuông kích thước <span class="math inline">\(n \times n\)</span> có định thức xấp xỉ bằng 0 nghĩa là mối liên hệ tuyến tính giữa các véc-tơ của ma trận là rất chặt chẽ.</p></li>
<li><p>Dấu của định thức cho ta biết vị trí của các véc-tơ. Véc-tơ hàng thứ nhất tương ứng với màu xanh dương trong khi véc-tơ hàng thứ hai tương ứng với màu đỏ. Dấu của định thức dương chỉ khi véc-tơ màu xanh dương nằm phía trên (bên trái) véc-tơ màu đỏ, và dấu của định thức là âm chỉ khi véc-tơ màu xanh dương nằm phía dưới (bên phải) véc-tơ màu đỏ.</p></li>
</ul>
<p>Với các ma trận vuông kích thước <span class="math inline">\(n \times n\)</span>; <span class="math inline">\(n \geq 3\)</span> định thức của ma trận được tính bằng cách lựa chọn một dòng (hoặc cột) thứ <span class="math inline">\(i\)</span> bất kỳ và sau đó thực hiện phép khai triển
<span class="math display">\[\begin{align}
det(M) = \sum\limits_{j = 1}^n (-1)^{i+j} \times m_{ij} \times det(M_{-i,-j})
\end{align}\]</span>
trong đó <span class="math inline">\(M_{-i,-j}\)</span> mà ma trận vuông kích thước <span class="math inline">\((n-1) \times (n-1)\)</span> nhận được sau khi bỏ đi hàng thứ <span class="math inline">\(i\)</span> và cột thứ <span class="math inline">\(j\)</span> của ma trận <span class="math inline">\(M\)</span>.</p>
<p>Định thức của ma trận <span class="math inline">\(M\)</span> kích thước <span class="math inline">\(3 \times 3\)</span> có thể tính toán dựa trên định thức của các ma trận con và lựa chọn hàng <span class="math inline">\(i=2\)</span> như sau</p>
<p><span class="math display">\[\begin{align}
&amp; &amp; M
=
\begin{bmatrix}
m_{11} &amp; m_{12} &amp; m_{13}  \\
m_{21} &amp; m_{22} &amp; m_{23} \\
m_{31} &amp; m_{32} &amp; m_{33}
\end{bmatrix} \\

&amp; &amp; det(M) = - m_{21} \times \begin{vmatrix}
m_{12} &amp; m_{13}  \\
m_{32} &amp; m_{33}
\end{vmatrix} + m_{22} \times \begin{vmatrix}
m_{11} &amp; m_{13}  \\
m_{31} &amp; m_{33}  
\end{vmatrix} - m_{23} \times \begin{vmatrix}
m_{11} &amp; m_{12}  \\
m_{31} &amp; m_{32}  
\end{vmatrix}
\end{align}\]</span></p>
<p>Hàm <code><a href="https://rdrr.io/r/base/det.html">det()</a></code> trong R được sử dụng để tính định thức của ma trận.</p>
<div class="sourceCode" id="cb305"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span>,nrow <span class="op">=</span> <span class="fl">2</span>,ncol <span class="op">=</span> <span class="fl">2</span>,byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/det.html">det</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>Một vài tính chất quan trọng của định thức:</p>
<ul>
<li>Định thức của một ma trận đường chéo bằng tích các phần tử nằm trên đường chéo chính của ma trận đó. Ma trận đường chéo là một trường hợp đặc biệt của ma trận tam giác. Ma trận tam giác trên là ma trận có tất cả các phần tử nằm phía dưới đường chéo chính nhận giá trị bằng 0. Tương tự, ma trận tâm giác dưới là ma trận có tất cả các phần tử nằm phía trên đường chéo chính nhận giá trị bằng 0. Các ma trận tam giác có tính chất như đã phát biểu ở trên: định thức của các ma trận này bằng tích các phần tử nằm trên đường chéo chính.</li>
</ul>
<div class="sourceCode" id="cb307"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">16</span>,nrow <span class="op">=</span> <span class="fl">4</span>,ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="va">M</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/lower.tri.html">lower.tri</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span><span class="op">]</span><span class="op">&lt;-</span><span class="fl">0</span> <span class="co"># cho các phần tử phía dưới đường chéo chính bằng 0</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span> <span class="co"># ma trận M là ma trận tam giác trên</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    5    9   13
## [2,]    0    6   10   14
## [3,]    0    0   11   15
## [4,]    0    0    0   16</code></pre>
<div class="sourceCode" id="cb309"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/det.html">det</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/prod.html">prod</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="co"># định thức của M bằng tích các số trên đường chéo chính</span></span></code></pre></div>
<pre><code>## [1] 1056 1056</code></pre>
<ul>
<li>Định thức của ma trận chuyển vị bằng định thức của ma trận ban đầu
<span class="math display">\[\begin{align}
det(M) = det(M^T)
\end{align}\]</span>
</li>
</ul>
<div class="sourceCode" id="cb311"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">16</span><span class="op">)</span>,nrow <span class="op">=</span> <span class="fl">4</span>,ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/det.html">det</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/det.html">det</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] -4.377982 -4.377982</code></pre>
<ul>
<li>Định thức của tích hai ma trận bằng tích của các định thức.
<span class="math display">\[\begin{align}
det(A \% * \% B) = det(A) \times det(B)
\end{align}\]</span>
</li>
</ul>
<div class="sourceCode" id="cb313"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">16</span><span class="op">)</span>,nrow <span class="op">=</span> <span class="fl">4</span>,ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="va">M1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">16</span><span class="op">)</span>,nrow <span class="op">=</span> <span class="fl">4</span>,ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/det.html">det</a></span><span class="op">(</span><span class="va">M</span><span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span><span class="va">M1</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/det.html">det</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/base/det.html">det</a></span><span class="op">(</span><span class="va">M1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </span></code></pre></div>
<pre><code>## [1] 0.09626011 0.09626011</code></pre>
</div>
<div id="ma-trận-nghịch-đảo" class="section level3" number="2.1.7">
<h3>
<span class="header-section-number">2.1.7</span> Ma trận nghịch đảo<a class="anchor" aria-label="anchor" href="#ma-tr%E1%BA%ADn-ngh%E1%BB%8Bch-%C4%91%E1%BA%A3o"><i class="fas fa-link"></i></a>
</h3>
<p>Ma trận nghịch đảo của một ma trận vuông <span class="math inline">\(M\)</span>, thường được ký hiệu <span class="math inline">\(M^{-1}\)</span>, là ma trận vuông có cùng kích thước với ma trận <span class="math inline">\(M\)</span> và thỏa mãn tính chất: phép nhân ma trận giữa ma trận <span class="math inline">\(M\)</span> với ma trận nghịch đảo <span class="math inline">\(M^{-1}\)</span> sẽ cho kết quả là một ma trận đơn vị. Không phải ma trận vuông nào cũng có ma trận nghịch đảo; chỉ có các ma trận có định thức khác là có ma trận nghịch đảo. Các ma trận có ma trận nghịch đảo được còn được gọi là các ma trận khả nghịch. Các ma trận khả nghịch luôn có một ma trận nghịch đảo duy nhất.</p>
<p><span class="math display">\[\begin{align}
M \% * \% M^{-1} = I_n
\end{align}\]</span></p>
<p>Hai lần lấy nghịch đảo liên tiếp với một ma trận khả nghịch sẽ quay trở lại ma trận ban đầu, hay nói một cách khác ma trận nghịch đảo của ma trận <span class="math inline">\(M^{-1}\)</span> chính là ma trận <span class="math inline">\(M\)</span>
<span class="math display">\[\begin{align}
M^{-1} \% * \% M = I_n
\end{align}\]</span></p>
<p>Phương pháp chung để tính toán ma trận nghịch đảo là dựa trên các ma trận liên hợp (adjugate matrix). Ma trận liên hợp của ma trận <span class="math inline">\(M\)</span> được ký hiệu là <span class="math inline">\(adj(M)\)</span> là ma trận vuông kích thước <span class="math inline">\(n \times n\)</span> mà phần tử ở hàng thứ <span class="math inline">\(i\)</span>, cột thứ <span class="math inline">\(j\)</span> được tính bằng
<span class="math display">\[\begin{align}
adj(M)_{ij} = (-1)^{j+i} det(M_{-j,-i})
\end{align}\]</span>
Khi tính toán định thức của ma trận <span class="math inline">\(M\)</span>, chúng tôi đã sử dụng ký hiệu <span class="math inline">\(M_{-i,-j}\)</span> cho ma trận vuông kích thước <span class="math inline">\((n-1) \times (n-1)\)</span> nhận được sau khi bỏ đi hàng thứ <span class="math inline">\(i\)</span> và cột thứ <span class="math inline">\(j\)</span> của ma trận <span class="math inline">\(M\)</span>. Bạn đọc lưu ý rằng có sự thay đổi vị trí của <span class="math inline">\(i\)</span> và <span class="math inline">\(j\)</span> trong vế phải của phương trình ở trên. Ma trận nghịch đảo <span class="math inline">\(M^{-1}\)</span> được tính từ ma trận liên hợp như sau
<span class="math display">\[\begin{align}
M^{-1} = \cfrac{1}{det(M)} adj(M)_{ij}
\end{align}\]</span></p>
<p>Nhìn chung, để tính toán ma trận nghịch đảo của một ma trận kích thước <span class="math inline">\(n \times n\)</span>, chúng ta sẽ phải tính toán định thức của ma trận ban đầu và định thức của <span class="math inline">\(n^2\)</span> ma trận vuông có kích thước <span class="math inline">\((n-1) \times (n-1)\)</span>. Với các ma trận vuông có kích thước lớn, việc tính toán sử dụng công thức như trên sẽ tốn nhiều thời gian và bộ nhớ. Có nhiều thuật toán để tính xấp xỉ ma trận nghịch đảo của một ma trận. Trình bày các thuật toán này ở đây là không cần thiết. R sử dụng hàm <code><a href="https://rdrr.io/r/base/solve.html">solve()</a></code> để tính toán ma trận nghịch đảo.</p>
<div class="sourceCode" id="cb315"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">16</span><span class="op">)</span>,nrow <span class="op">=</span> <span class="fl">4</span>,ncol <span class="op">=</span> <span class="fl">4</span><span class="op">)</span> </span>
<span><span class="va">M1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/solve.html">solve</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span> <span class="co"># ma trận M1 là ma trận nghịch đảo của ma trận M</span></span>
<span><span class="va">M1</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">M</span> <span class="co"># tích của M1 với M là ma trận đơn vị</span></span></code></pre></div>
<pre><code>##               [,1]          [,2]          [,3]          [,4]
## [1,]  1.000000e+00 -1.387779e-16 -2.220446e-16 -1.040834e-16
## [2,] -2.081668e-17  1.000000e+00  0.000000e+00  1.387779e-17
## [3,] -6.938894e-18  1.110223e-16  1.000000e+00 -2.775558e-17
## [4,] -3.469447e-17  1.665335e-16  1.110223e-16  1.000000e+00</code></pre>
<div class="sourceCode" id="cb317"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">M1</span> <span class="co"># tích của M với M1 là ma trận đơn vị</span></span></code></pre></div>
<pre><code>##               [,1]          [,2]          [,3]          [,4]
## [1,]  1.000000e+00 -1.734723e-17 -3.053113e-16  3.122502e-17
## [2,] -5.551115e-17  1.000000e+00  5.551115e-17 -1.144917e-16
## [3,]  0.000000e+00  0.000000e+00  1.000000e+00  5.551115e-17
## [4,]  0.000000e+00  1.873501e-16  2.775558e-17  1.000000e+00</code></pre>
<p>Các tính toán liên quan đến định thức cần nhớ</p>
<ol style="list-style-type: decimal">
<li><p>Định thức của ma trận sau khi nhân tất cả các phần tử với một số
<span class="math display">\[\begin{align}
det(\lambda M) = \lambda^n \times det(M)
\end{align}\]</span></p></li>
<li><p>Định thức của ma trận chuyển vị <span class="math inline">\(M^{-T}\)</span> bằng định thức của ma trận <span class="math inline">\(M\)</span>
<span class="math display">\[\begin{align}
det(M^T) = det(M)
\end{align}\]</span></p></li>
<li><p>Tích của định thức của ma trận <span class="math inline">\(M^{-1}\)</span> với định thức của ma trận <span class="math inline">\(M\)</span> bằng 1.
<span class="math display">\[\begin{align}
det(M^{-1}) \times det(M) = det(I_n) = 1
\end{align}\]</span></p></li>
</ol>
</div>
</div>
<div id="mảng-nhiều-chiều" class="section level2" number="2.2">
<h2>
<span class="header-section-number">2.2</span> Mảng nhiều chiều<a class="anchor" aria-label="anchor" href="#m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u"><i class="fas fa-link"></i></a>
</h2>
<p>Ma trận lưu phần tử trong hai chiều mà chúng ta gọi là hàng và cột. Đa số dữ liệu kiểu bảng biểu truyền thống đều có thể biểu diễn dưới dạng ma trận. Tuy nhiên có những kiểu dữ liệu mà khi biểu diễn dưới dạng ma trận hai chiều là không dễ dàng và có thể gây nhầm lẫn cho người sử dụng. Có thể kể đến dữ liệu kiểu hình ảnh. Khi bạn đọc lưu một bức ảnh màu lên trên máy tính điện tử, bức ảnh sẽ được số hóa thành một mảng ba chiều, bao gồm có chiều cao, chiều rộng của ảnh và một chiều thứ ba là màu sắc của điểm ảnh. Phức tạp hơn nữa nếu dữ liệu là một đoạn phim, hay một hình động, bạn đọc sẽ cần phải sử dụng thêm chiều thứ tư để mô tả thời gian xuất hiện của mỗi hình ảnh trong đoạn phim.</p>
<p>Thông thường thì người làm việc với dữ liệu sẽ đổi các mảng nhiều chiều về mảng hai chiều hoặc một chiều (véc-tơ) để dễ dàng xử lý. Các thao tác cơ bản khi làm việc với mảng nhiều chiều là cần thiết để thực hiện xử lý dữ liệu một cách chính xác.</p>
<div id="khởi-tạo-mảng-nhiều-chiều" class="section level3" number="2.2.1">
<h3>
<span class="header-section-number">2.2.1</span> Khởi tạo mảng nhiều chiều<a class="anchor" aria-label="anchor" href="#kh%E1%BB%9Fi-t%E1%BA%A1o-m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u"><i class="fas fa-link"></i></a>
</h3>
<p>Để tạo mảng nhiều chiều bạn đọc sử dụng hàm <span class="math inline">\(array()\)</span>.</p>
<div class="sourceCode" id="cb319"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Ar</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">24</span>,dim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span> <span class="co"># mảng 3 chiều</span></span>
<span><span class="va">Ar</span> <span class="co"># hiển thị mảng 3 chiều Ar</span></span></code></pre></div>
<pre><code>## , , 1
## 
##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6
## 
## , , 2
## 
##      [,1] [,2] [,3]
## [1,]    7    9   11
## [2,]    8   10   12
## 
## , , 3
## 
##      [,1] [,2] [,3]
## [1,]   13   15   17
## [2,]   14   16   18
## 
## , , 4
## 
##      [,1] [,2] [,3]
## [1,]   19   21   23
## [2,]   20   22   24</code></pre>
<p>Bạn đọc có thể thấy R hiển thị mảng ba chiều <span class="math inline">\(Ar\)</span> kích thước <span class="math inline">\(2 \times 3 \times 4\)</span> như là sự kết hợp của 4 ma trận kích thước <span class="math inline">\(2 \times 3\)</span>. Tương tự như khi khởi tạo giá trị cho ma trận, số lượng phần tử đưa vào trong mảng phải bằng với số phần tử của mảng, trong trường hợp mảng <span class="math inline">\(Ar\)</span> ở trên là véc-tơ có độ dài 24 tương ứng với <span class="math inline">\(2 \times 3 \times 4 = 24\)</span> phần tử của mảng.</p>
<p>Để lấy ra các phần tử con (một biến, một ma trận, hay 1 mảng nhiều chiều) từ một nhiều mảng, bạn đọc sử dụng <span class="math inline">\([]\)</span> giống như khi làm với ma trận. Lưu ý rằng khi lấy phần tử con từ một mảng, bạn đọc cần phải sử dụng chỉ số cho tất cả các chiều.</p>
<div class="sourceCode" id="cb321"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Ar</span><span class="op">[</span><span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">1</span><span class="op">]</span> <span class="co"># phần tử có các chỉ số 1 - 2 - 1 </span></span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb323"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Ar</span><span class="op">[</span>,,<span class="fl">1</span><span class="op">]</span> <span class="co"># ma trận 2 * 3</span></span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<div class="sourceCode" id="cb325"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Ar</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">4</span><span class="op">)</span><span class="op">]</span> <span class="co"># mảng trận 2 * 2 * 2</span></span></code></pre></div>
<pre><code>## , , 1
## 
##      [,1] [,2]
## [1,]    1    5
## [2,]    2    6
## 
## , , 2
## 
##      [,1] [,2]
## [1,]   19   23
## [2,]   20   24</code></pre>
<p>Thứ tự các phần tử khi điền vào mảng khi sử dụng hàm trong hàm <code><a href="https://rdrr.io/r/base/array.html">array()</a></code> sẽ là ưu tiên ma trận kích thước <span class="math inline">\(2 \times 3\)</span> tương ứng với chỉ số <span class="math inline">\([,,1]\)</span> trước, rồi đến ma trận kích thước <span class="math inline">\(2 \times 3\)</span> tương ứng với chỉ số <span class="math inline">\([,,2]\)</span>,…, và tiếp tục như thế cho đến khi tất cả các phần tử của mảng được gán giá trị.</p>
</div>
<div id="sử-dụng-mảng-nhiều-chiều-để-biến-đổi-dữ-liệu-kiểu-hình-ảnh" class="section level3" number="2.2.2">
<h3>
<span class="header-section-number">2.2.2</span> Sử dụng mảng nhiều chiều để biến đổi dữ liệu kiểu hình ảnh<a class="anchor" aria-label="anchor" href="#s%E1%BB%AD-d%E1%BB%A5ng-m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u-%C4%91%E1%BB%83-bi%E1%BA%BFn-%C4%91%E1%BB%95i-d%E1%BB%AF-li%E1%BB%87u-ki%E1%BB%83u-h%C3%ACnh-%E1%BA%A3nh"><i class="fas fa-link"></i></a>
</h3>
<p>Để bạn đọc có cái nhìn trực quan hơn về mảng nhiều chiều, chúng ta sẽ thực hiện các phép biến đổi, tính toán trên một dữ liệu cụ thể. Như chúng tôi đã nói ở trên, mảng nhiều chiều là một đối tượng thích hợp dùng để lưu dữ liệu kiểu hình ảnh. Thư viện <span class="math inline">\(imager\)</span> được cài thêm trên R có các hàm thích hợp để làm việc với dữ liệu kiểu hình ảnh. Chúng ta sẽ sử dụng một mảng nhiều chiều để lưu một bức ảnh và thực hiện các phép biến đổi bức ảnh đó sử dụng tính toán trên mảng nhiều chiều.</p>
<div class="sourceCode" id="cb327"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#install.packages("imager")</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://asgr.github.io/imager/">imager</a></span><span class="op">)</span></span></code></pre></div>
<p>Hàm <code><a href="https://rdrr.io/pkg/imager/man/load.image.html">load.image()</a></code> trong thư viện <span class="math inline">\(imager\)</span> có thể đọc các file hình ảnh có định dạng <span class="math inline">\(png\)</span>, <span class="math inline">\(jpeg\)</span>, hoặc <span class="math inline">\(bmp\)</span>. Bạn đọc có thể đọc một hình ảnh có một trong các định dạng kể trên</p>
<div class="sourceCode" id="cb328"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/getwd.html">setwd</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD/Image"</span><span class="op">)</span></span>
<span><span class="va">img</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/load.image.html">load.image</a></span><span class="op">(</span><span class="st">"cat.jpg"</span><span class="op">)</span> <span class="co"># đọc hình ảnh tên "cat" vào </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">img</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-152-1.png" width="672"></div>
<p>Để biết <span class="math inline">\(img\)</span> là kiểu đối tượng nào, bạn đọc dùng hàm <code><a href="https://rdrr.io/r/base/class.html">class()</a></code></p>
<div class="sourceCode" id="cb329"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">img</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "cimg"         "imager_array" "numeric"</code></pre>
<p>R cho biết đây là một đối tượng kiểu <span class="math inline">\(cimg\)</span>. Kiểu đối tượng này về bản chất là một mảng bốn chiều. Chiều thứ nhất là cho biết chiều rộng của bức ảnh, chiều thứ hai cho biết chiều cao của bức ảnh, chiều thứ ba luôn bằng 1 đối với dữ liệu kiểu ảnh và chiều thứ tư bằng 3 nếu bức ảnh là ảnh màu.</p>
<p>Đối tượng kiểu <span class="math inline">\(cimg\)</span> cho phép bạn đọc thực hiện các biến đổi, tính toán giống như trên một mảng nhiều chiều mà không cần phải chuyển đổi sang kiểu mảng. Chẳng hạn như để biết bức ảnh được lưu bởi đối tượng tên <span class="math inline">\(img\)</span> có bao nhiêu chiều, chúng ta sử dụng hàm <code><a href="https://rdrr.io/r/base/dim.html">dim()</a></code> giống như với mảng</p>
<div class="sourceCode" id="cb331"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">img</span><span class="op">)</span> <span class="co"># mảng bốn chiều: chiều rộng * chiều cao * chiều thời gian * chiều màu sắc</span></span></code></pre></div>
<pre><code>## [1] 535 595   1   3</code></pre>
<p>Bức ảnh được lưu bởi đối tượng <span class="math inline">\(img\)</span> ở trên là một bức ảnh màu có chiều rộng 535 và chiều cao 595. Chiều thứ ba bằng 1 nghĩa là đây là một bức ảnh (chiều thứ ba lớn hơn 1 khi đối tượng là hình ảnh động). Chiều thứ tư bằng 3 đại diện cho 3 màu đỏ (Red), màu xanh lá cây (Green), và màu xanh da trời (Blue). Bạn đọc có thể hình dung một bức ảnh màu ở trên như là sự kết hợp của ba ma trận cùng kích thước <span class="math inline">\(535 \times 595\)</span>, ma trận thứ nhất đại diện cho màu đỏ, ma trận thứ hai đại diện cho màu xanh lá cây và ma trận thứ ba đại diện cho màu xanh da trời. Mỗi giá trị trong ma trận là một số trong khoảng từ 0 đến 1. Giá trị 0 tương ứng với màu đen và giá trị càng gần 1 thì màu sắc của điểm đó càng gần màu mà ma trận đại diện. Để quan sát ma trận tương ứng với mỗi màu, bạn đọc cần gán giá trị của 2 ma trận còn lại bằng 0 trước khi hiển thị.</p>
<div class="sourceCode" id="cb333"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">img_red</span><span class="op">&lt;-</span><span class="va">img</span></span>
<span><span class="va">img_red</span><span class="op">[</span>,,<span class="fl">1</span>,<span class="fl">2</span><span class="op">:</span><span class="fl">3</span><span class="op">]</span><span class="op">&lt;-</span><span class="fl">0</span> <span class="co"># cho 2 ma trận màu xanh lá cây và xanh da trời bằng 0</span></span>
<span></span>
<span><span class="va">img_green</span><span class="op">&lt;-</span><span class="va">img</span></span>
<span><span class="va">img_green</span><span class="op">[</span>,,<span class="fl">1</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">]</span><span class="op">&lt;-</span><span class="fl">0</span> <span class="co"># cho 2 ma trận màu đỏ và xanh da trời bằng 0</span></span>
<span></span>
<span><span class="va">img_blue</span><span class="op">&lt;-</span><span class="va">img</span></span>
<span><span class="va">img_blue</span><span class="op">[</span>,,<span class="fl">1</span>,<span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">]</span><span class="op">&lt;-</span><span class="fl">0</span> <span class="co"># cho 2 ma trận màu xanh lá cây và đỏ bằng 0</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">img_red</span>, main <span class="op">=</span> <span class="st">"Chỉ giữa lại màu đỏ"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">img_green</span>, main <span class="op">=</span> <span class="st">"Chỉ giữa lại màu xanh lá cây"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">img_blue</span>, main <span class="op">=</span> <span class="st">"Chỉ giữa lại màu xanh da trời"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-155-1.png" width="672"></div>
<p>Hàm <code><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg()</a></code> được dùng để đổi một mảng bốn chiều sang kiểu <span class="math inline">\(cimg\)</span> để có thể hiển thị khi sử dụng hàm <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code>. Lưu ý rằng hãy luôn sử dụng chiều thứ ba bằng 1 và chiều thứ tư bằng 3 nếu bạn muốn tạo ảnh màu. Các câu lệnh dưới đây tạo ra các bức ảnh mà các giá trị trong các ma trận màu sắc hoàn toàn là các giá trị ngẫu nhiên phân phối đều (uniform) trong khoảng (0,1).</p>
<div class="sourceCode" id="cb334"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">img1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">5</span><span class="op">*</span><span class="fl">5</span><span class="op">*</span><span class="fl">1</span><span class="op">*</span><span class="fl">3</span><span class="op">)</span>,dim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">5</span>,<span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="co"># bức ảnh màu kích thước 5*5</span></span>
<span><span class="va">img1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg</a></span><span class="op">(</span><span class="va">img1</span><span class="op">)</span></span>
<span></span>
<span><span class="va">img2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1000</span><span class="op">*</span><span class="fl">1000</span><span class="op">*</span><span class="fl">1</span><span class="op">*</span><span class="fl">3</span><span class="op">)</span>,dim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1000</span>,<span class="fl">1000</span>,<span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="co"># bức ảnh màu kích thước 1000*1000</span></span>
<span><span class="va">img2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg</a></span><span class="op">(</span><span class="va">img2</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">img1</span>, interpolate <span class="op">=</span> <span class="cn">FALSE</span>, main <span class="op">=</span> <span class="st">"Ảnh nhiễu kích thước 5 * 5"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">img2</span>, interpolate <span class="op">=</span> <span class="cn">FALSE</span>, main <span class="op">=</span> <span class="st">"Ảnh nhiễu kích thước 1000 * 1000"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-157-1.png" width="672"></div>
<p>Tham số <span class="math inline">\(interpolate\)</span> nhận giá trị bằng <span class="math inline">\(FALSE\)</span> có nghĩa là các điểm ảnh giữ nguyên giá trị. Tham số này có giá trị là mặc định là <span class="math inline">\(TRUE\)</span>. Khi <span class="math inline">\(interpolate\)</span> nhận giá trị bằng <span class="math inline">\(TRUE\)</span> hình ảnh hiển thị sẽ có sự giao thoa về màu sắc tại viền các điểm ảnh và làm cho ảnh nhìn mượt mà hơn.</p>
<p>Về bản chất, xử lý ảnh trên máy tính điện tử chính là xử lý các con số nằm trong mảng nhiều chiều. Chúng tôi sẽ giới thiệu một vài kỹ thuật xử lý đơn giản trên ảnh để bạn đọc có thể hiểu hơn về xử lý mảng nhiều chiều. Trước hết là thao tác cắt ảnh. Cắt ảnh chính là một phép lấy mảng con từ một mảng ban đầu. Thật vậy,</p>
<div class="sourceCode" id="cb335"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">n</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">img</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="co"># chiều rộng của ảnh</span></span>
<span><span class="va">k</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span> <span class="co"># điểm giữa để chia ảnh làm hai nửa</span></span>
<span><span class="va">img1</span><span class="op">&lt;-</span><span class="va">img</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="va">k</span>,,,<span class="op">]</span> <span class="co"># img1 là nửa bên trái của ảnh</span></span>
<span><span class="va">img2</span><span class="op">&lt;-</span><span class="va">img</span><span class="op">[</span><span class="op">(</span><span class="va">k</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span><span class="op">:</span><span class="va">n</span>,,,<span class="op">]</span> <span class="co"># img2 là nửa bên phải của ảnh</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg</a></span><span class="op">(</span><span class="va">img1</span><span class="op">)</span>, main <span class="op">=</span> <span class="st">"Nửa bên trái"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg</a></span><span class="op">(</span><span class="va">img2</span><span class="op">)</span>, main <span class="op">=</span> <span class="st">"Nửa bên phải"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-158-1.png" width="672"></div>
<p>Tiếp theo, chúng ta sẽ thực hiện tăng hoặc giảm độ sáng của ảnh. Tăng hoặc giảm độ sáng của ảnh tương đương với việc điều chỉnh đồng thời các số trong mảng nhiều chiều gần hơn đến giá trị 1 hoặc gần hơn đến giá trị 0. Chúng ta thực hiện như sau</p>
<div class="sourceCode" id="cb336"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">img1</span><span class="op">&lt;-</span><span class="va">img</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">img</span><span class="op">)</span> <span class="op">*</span> <span class="fl">0.3</span> <span class="co"># img1 là bức ảnh sau khi tăng độ sáng lên 30% </span></span>
<span><span class="va">img2</span><span class="op">&lt;-</span><span class="va">img</span> <span class="op">-</span> <span class="va">img</span> <span class="op">*</span> <span class="fl">0.3</span> <span class="co"># img2 là bức ảnh sau khi giảm độ sáng đi 30%</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">img</span>, rescale <span class="op">=</span> <span class="cn">FALSE</span>, main<span class="op">=</span> <span class="st">"Ảnh ban đầu"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg</a></span><span class="op">(</span><span class="va">img1</span><span class="op">)</span>, rescale <span class="op">=</span> <span class="cn">FALSE</span>, main <span class="op">=</span> <span class="st">"Tăng độ sáng"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg</a></span><span class="op">(</span><span class="va">img2</span><span class="op">)</span>,rescale <span class="op">=</span> <span class="cn">FALSE</span>, main <span class="op">=</span> <span class="st">"Giảm độ sáng"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-159-1.png" width="672"></div>
<p>Một kỹ thuật xử lý ảnh khác là giảm kích thước của ảnh. Giả sử bạn đọc muốn giảm kích thước ảnh mỗi chiều 50%. Để làm được việc này, mỗi ma trận kích thước <span class="math inline">\(n \times m\)</span> sẽ được đổi thành ma trận kích thước <span class="math inline">\([n/2] \times [m/2]\)</span> trong đó <span class="math inline">\([n/2]\)</span> là phần nguyên của số <span class="math inline">\(n/2\)</span>. Nguyên tắc chuyển từ ma trận ban đầu sang ma trận có kích thước nhỏ hơn là mỗi ô <span class="math inline">\(2 \times 2\)</span> của ma trận ban đầu được chuyển thành 1 số trong ma trận mới</p>
<div class="sourceCode" id="cb337"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">giamchieu</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">M</span>,<span class="va">k</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">n</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>; <span class="va">m</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span>  <span class="va">n1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="va">k</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span>; <span class="va">m1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">m</span><span class="op">/</span><span class="va">k</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span></span>
<span>  <span class="va">M1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">n1</span>,<span class="va">m1</span><span class="op">)</span></span>
<span>  <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">n1</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">j</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="va">m1</span><span class="op">)</span><span class="op">{</span></span>
<span>      <span class="va">i1</span><span class="op">&lt;-</span><span class="op">(</span><span class="va">k</span><span class="op">*</span><span class="op">(</span><span class="va">i</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span><span class="op">:</span><span class="op">(</span><span class="va">k</span><span class="op">*</span><span class="va">i</span><span class="op">)</span></span>
<span>      <span class="va">j1</span><span class="op">&lt;-</span><span class="op">(</span><span class="va">k</span><span class="op">*</span><span class="op">(</span><span class="va">j</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span><span class="op">:</span><span class="op">(</span><span class="va">k</span><span class="op">*</span><span class="va">j</span><span class="op">)</span></span>
<span>      <span class="va">M1</span><span class="op">[</span><span class="va">i</span>,<span class="va">j</span><span class="op">]</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">M</span><span class="op">[</span><span class="va">i1</span>,<span class="va">j1</span><span class="op">]</span>,na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>  <span class="op">}</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">M1</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">n</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">img</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>; <span class="va">m</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">img</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span><span class="va">k1</span><span class="op">&lt;-</span><span class="fl">10</span>; <span class="va">k2</span><span class="op">&lt;-</span><span class="fl">20</span></span>
<span><span class="va">n1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="va">k1</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span>; <span class="va">m1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">m</span><span class="op">/</span><span class="va">k1</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span></span>
<span><span class="va">n2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">n</span><span class="op">/</span><span class="va">k2</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span>; <span class="va">m2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">m</span><span class="op">/</span><span class="va">k2</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span></span>
<span></span>
<span><span class="va">img1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fl">0</span>,dim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">n1</span>,<span class="va">m1</span>,<span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span>;</span>
<span><span class="va">img2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fl">0</span>,dim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">n2</span>,<span class="va">m2</span>,<span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span>;</span>
<span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">)</span><span class="op">{</span> </span>
<span>  <span class="va">img1</span><span class="op">[</span>,,<span class="fl">1</span>,<span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="fu">giamchieu</span><span class="op">(</span><span class="va">img</span><span class="op">[</span>,,<span class="fl">1</span>,<span class="va">i</span><span class="op">]</span>,<span class="va">k1</span><span class="op">)</span></span>
<span>  <span class="va">img2</span><span class="op">[</span>,,<span class="fl">1</span>,<span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="fu">giamchieu</span><span class="op">(</span><span class="va">img</span><span class="op">[</span>,,<span class="fl">1</span>,<span class="va">i</span><span class="op">]</span>,<span class="va">k2</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">img</span>, interpolate <span class="op">=</span> <span class="cn">FALSE</span>, main<span class="op">=</span> <span class="st">"Ảnh ban đầu"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg</a></span><span class="op">(</span><span class="va">img1</span><span class="op">)</span>, interpolate <span class="op">=</span> <span class="cn">FALSE</span>, main <span class="op">=</span> <span class="st">"Giảm kích thước 1:10"</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/imager/man/as.cimg.html">as.cimg</a></span><span class="op">(</span><span class="va">img2</span><span class="op">)</span>, interpolate <span class="op">=</span> <span class="cn">FALSE</span>, main <span class="op">=</span> <span class="st">"Giảm kích thước 1:20"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-160-1.png" width="672"></div>
</div>
</div>
<div id="list" class="section level2" number="2.3">
<h2>
<span class="header-section-number">2.3</span> <code>List</code><a class="anchor" aria-label="anchor" href="#list"><i class="fas fa-link"></i></a>
</h2>
<p>Không giống như véc-tơ, ma trận, hay mảng nhiều chiều, <span class="math inline">\(list\)</span> là một cấu trúc trong R mà có thể chứa nhiều kiểu đối tượng khác nhau bao gồm biến, véc-tơ, ma trận, và cả các <span class="math inline">\(list\)</span> khác. Với những bạn đọc đã học qua Python, <span class="math inline">\(list\)</span> cũng giống như một <span class="math inline">\(dictionary\)</span>. Đối với các bạn đọc đã học qua ngôn ngữ lập trình C++, <span class="math inline">\(list\)</span> tương tự như một <span class="math inline">\(struct\)</span>. <span class="math inline">\(list\)</span> đóng vai trò quan trọng trong R, đặc biệt là trong viết hàm số và lập trình hướng đối tượng.</p>
<p>Trong phần này của cuốn sách, chúng ta sẽ tìm hiểu cách tạo ra <span class="math inline">\(list\)</span> và ứng dụng cấu trúc của <span class="math inline">\(list\)</span> để phục vụ công việc phân tích dữ liệu một cách hiệu quả nhất.</p>
<div id="khởi-tạo-list-và-chỉ-số-của-list." class="section level3" number="2.3.1">
<h3>
<span class="header-section-number">2.3.1</span> Khởi tạo <span class="math inline">\(list\)</span> và chỉ số của <span class="math inline">\(list\)</span>.<a class="anchor" aria-label="anchor" href="#kh%E1%BB%9Fi-t%E1%BA%A1o-list-v%C3%A0-ch%E1%BB%89-s%E1%BB%91-c%E1%BB%A7a-list."><i class="fas fa-link"></i></a>
</h3>
<p>Hàm số để tạo ra một <span class="math inline">\(list\)</span> trong R là hàm <code><a href="https://rdrr.io/r/base/list.html">list()</a></code>. Giả sử chúng ta muốn tạo thành một đối tượng có tên <span class="math inline">\(SV1\)</span> chứa các thông tin về một sinh viên</p>
<ol style="list-style-type: decimal">
<li><p>Tên của sinh viên: được lưu trong một biến kiểu chuỗi ký tự.</p></li>
<li><p>Ngày sinh của sinh viên: được lưu trong một biến kiểu thời gian.</p></li>
<li><p>Giới tính của sinh viên: được lưu trong một biến kiểu logic, giá trị <span class="math inline">\(TRUE\)</span> tương ứng với giới tính Nam, và <span class="math inline">\(FALSE\)</span> tương ứng với giới tính nữ.</p></li>
<li><p>Bảng điểm của sinh viên: là một <span class="math inline">\(data.frame\)</span> có 2 cột, 1 cột là tên môn học và một cột là điểm của môn học tương ứng.</p></li>
</ol>
<p>Chúng ta sử dụng hàm <code><a href="https://rdrr.io/r/base/list.html">list()</a></code> để tạo ra một <span class="math inline">\(list\)</span> có tên <span class="math inline">\(SV1\)</span> như sau</p>
<div class="sourceCode" id="cb338"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">SV1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>Ten <span class="op">=</span> <span class="st">"Nguyễn Đức Nam"</span>,</span>
<span>          Ngay_sinh <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="st">"2000-06-20"</span><span class="op">)</span>,</span>
<span>          Gioi_tinh <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>          Bang_diem <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Mon_hoc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Giải tích"</span>, <span class="st">"Đại số"</span>, <span class="st">"Xác suất"</span><span class="op">)</span>,</span>
<span>                                 Diem <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">6.5</span>, <span class="fl">8.5</span>, <span class="fl">7.0</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">SV1</span><span class="op">)</span> <span class="co"># xem cấu trúc của list SV1</span></span></code></pre></div>
<pre><code>## List of 4
##  $ Ten      : chr "Nguyễn Đức Nam"
##  $ Ngay_sinh: Date[1:1], format: "2000-06-20"
##  $ Gioi_tinh: logi TRUE
##  $ Bang_diem:'data.frame':   3 obs. of  2 variables:
##   ..$ Mon_hoc: chr [1:3] "Giải tích" "Đại số" "Xác suất"
##   ..$ Diem   : num [1:3] 6.5 8.5 7</code></pre>
<p>Bạn đọc có thể thấy <span class="math inline">\(SV1\)</span> có bốn đối tượng con có tên là <span class="math inline">\(Ten\)</span>, <span class="math inline">\(Ngay\_sinh\)</span>, <span class="math inline">\(Gioi\_tinh\)</span>, và <span class="math inline">\(Bang\_diem\)</span>. Mỗi đối tượng con có một kiểu giá trị khác nhau, riêng đối tượng con <span class="math inline">\(Bang\_diem\)</span> là một dữ liệu (<span class="math inline">\(data.frame\)</span>).</p>
<p>Để lấy ra một đối tượng con của <span class="math inline">\(list\)</span> bạn đọc sử dụng ký hiệu <span class="math inline">\(\$\)</span>. Chẳng hạn bạn đọc muốn hiển thị bảng điểm của sinh viên có thông tin được lưu trong <span class="math inline">\(list\)</span> SV1, bạn đọc sử dụng câu lệnh sau</p>
<div class="sourceCode" id="cb340"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">SV1</span><span class="op">$</span><span class="va">Bang_diem</span> <span class="co"># hiển thị bảng điểm</span></span></code></pre></div>
<pre><code>##     Mon_hoc Diem
## 1 Giải tích  6.5
## 2    Đại số  8.5
## 3  Xác suất  7.0</code></pre>
<p>Để biết tên các đối tượng trong một <span class="math inline">\(list\)</span>, bạn đọc sử dụng hàm <code><a href="https://rdrr.io/r/base/names.html">names()</a></code></p>
<div class="sourceCode" id="cb342"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">SV1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "Ten"       "Ngay_sinh" "Gioi_tinh" "Bang_diem"</code></pre>
<p>Một cách khác để lấy ra một đối tượng con của <span class="math inline">\(list\)</span> là sử dụng chỉ số của đối tượng. Do bảng điểm nằm ở vị trí thứ 4 trong list nên bạn đọc sử dụng câu lệnh sau</p>
<div class="sourceCode" id="cb344"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">SV1</span><span class="op">[[</span><span class="fl">4</span><span class="op">]</span><span class="op">]</span> <span class="co"># sử dụng 2 lần dấu ngoặc vuông</span></span></code></pre></div>
<pre><code>##     Mon_hoc Diem
## 1 Giải tích  6.5
## 2    Đại số  8.5
## 3  Xác suất  7.0</code></pre>
<p>Bạn đọc có thể thấy rằng để lấy ra phần tử con, chúng ta cần phải sử dụng hai lần dấu ngoặc vuông. Nếu chỉ sử dụng một dấu ngoặc vuông, phần tử được lấy ra sẽ là 1 list có 1 phần tử và phần tử duy nhất là bảng điểm.</p>
<div class="sourceCode" id="cb346"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">SV1</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span> <span class="co"># là một list có 1 phần tử</span></span></code></pre></div>
<pre><code>## $Bang_diem
##     Mon_hoc Diem
## 1 Giải tích  6.5
## 2    Đại số  8.5
## 3  Xác suất  7.0</code></pre>
<p>Để thêm một đối tượng vào <span class="math inline">\(list\)</span>, chúng ta có thể đặt tên trực tiếp cho đối tượng mới và gán giá trị cho đối tượng. Ví dụ như chúng ta muốn thêm thông tin về quê quán của sinh viên vào một đối tượng có tên là <span class="math inline">\(que\_quan\)</span></p>
<div class="sourceCode" id="cb348"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">SV1</span><span class="op">$</span><span class="va">que_quan</span><span class="op">&lt;-</span><span class="st">"Hà Nội"</span> <span class="co"># Thêm vào một phần tử có tên que_quan là một biến</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">SV1</span><span class="op">)</span> <span class="co"># list SV1 đã có thêm phần tử thứ năm</span></span></code></pre></div>
<pre><code>## List of 5
##  $ Ten      : chr "Nguyễn Đức Nam"
##  $ Ngay_sinh: Date[1:1], format: "2000-06-20"
##  $ Gioi_tinh: logi TRUE
##  $ Bang_diem:'data.frame':   3 obs. of  2 variables:
##   ..$ Mon_hoc: chr [1:3] "Giải tích" "Đại số" "Xác suất"
##   ..$ Diem   : num [1:3] 6.5 8.5 7
##  $ que_quan : chr "Hà Nội"</code></pre>
<p>Để xóa đi một đối tượng khỏi list, chúng ta gán cho đối tượng đó giá trị bằng <span class="math inline">\(NULL\)</span></p>
<div class="sourceCode" id="cb350"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">SV1</span><span class="op">$</span><span class="va">que_quan</span><span class="op">&lt;-</span><span class="cn">NULL</span> <span class="co"># xóa phần tử có tên que_quan khỏi SV1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">SV1</span><span class="op">)</span> <span class="co"># list SV1 chỉ còn 4 phần tử</span></span></code></pre></div>
<pre><code>## List of 4
##  $ Ten      : chr "Nguyễn Đức Nam"
##  $ Ngay_sinh: Date[1:1], format: "2000-06-20"
##  $ Gioi_tinh: logi TRUE
##  $ Bang_diem:'data.frame':   3 obs. of  2 variables:
##   ..$ Mon_hoc: chr [1:3] "Giải tích" "Đại số" "Xác suất"
##   ..$ Diem   : num [1:3] 6.5 8.5 7</code></pre>
<p>Như chúng ta đã thảo luận trong phần giới thiệu, <span class="math inline">\(list\)</span> là một cấu trúc nhiều lớp, nghĩa là một list có thể chứa các đối tượng có kiểu <span class="math inline">\(list\)</span>. Thật vậy, giả sử chúng ta có list <span class="math inline">\(SV2\)</span> chứa các thông tin tương ứng của một sinh viên khác</p>
<div class="sourceCode" id="cb352"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">SV2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>Ten <span class="op">=</span> <span class="st">"Nguyễn Thị Loan"</span>,</span>
<span>          Ngay_sinh <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="st">"2000-05-13"</span><span class="op">)</span>,</span>
<span>          Gioi_tinh <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>          Bang_diem <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Mon_hoc <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Xác suất"</span>, <span class="st">"Thống kê"</span>, <span class="st">"Học máy"</span>,<span class="st">"AI"</span><span class="op">)</span>,</span>
<span>                                 Diem <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7.0</span>, <span class="fl">9.5</span>, <span class="fl">10.0</span>, <span class="fl">9.0</span><span class="op">)</span><span class="op">)</span>,</span>
<span>          Que_quan <span class="op">=</span> <span class="st">"Hà Nội"</span><span class="op">)</span></span></code></pre></div>
<p>Chúng ta có thể tạo một <span class="math inline">\(list\)</span> có tên là <span class="math inline">\(DS\)</span> chứa thông tin của cả 2 sinh viên</p>
<div class="sourceCode" id="cb353"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">DS</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>SV1 <span class="op">=</span> <span class="va">SV1</span>,SV2 <span class="op">=</span> <span class="va">SV2</span><span class="op">)</span> <span class="co"># DS là một list có 2 phần tử, mỗi phần tử là 1 list</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">DS</span><span class="op">)</span> <span class="co"># xem cấu trúc của list DS</span></span></code></pre></div>
<pre><code>## List of 2
##  $ SV1:List of 4
##   ..$ Ten      : chr "Nguyễn Đức Nam"
##   ..$ Ngay_sinh: Date[1:1], format: "2000-06-20"
##   ..$ Gioi_tinh: logi TRUE
##   ..$ Bang_diem:'data.frame':    3 obs. of  2 variables:
##   .. ..$ Mon_hoc: chr [1:3] "Giải tích" "Đại số" "Xác suất"
##   .. ..$ Diem   : num [1:3] 6.5 8.5 7
##  $ SV2:List of 5
##   ..$ Ten      : chr "Nguyễn Thị Loan"
##   ..$ Ngay_sinh: Date[1:1], format: "2000-05-13"
##   ..$ Gioi_tinh: logi FALSE
##   ..$ Bang_diem:'data.frame':    4 obs. of  2 variables:
##   .. ..$ Mon_hoc: chr [1:4] "Xác suất" "Thống kê" "Học máy" "AI"
##   .. ..$ Diem   : num [1:4] 7 9.5 10 9
##   ..$ Que_quan : chr "Hà Nội"</code></pre>
<p>Để xem bảng điểm của sinh viên thứ hai, chúng ta cần sử dụng 2 lần ký hiệu <span class="math inline">\(\$\)</span>:</p>
<div class="sourceCode" id="cb355"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">DS</span><span class="op">$</span><span class="va">SV2</span><span class="op">$</span><span class="va">Bang_diem</span> <span class="co"># Xem bảng điểm của sinh viên thứ hai</span></span></code></pre></div>
<pre><code>##    Mon_hoc Diem
## 1 Xác suất  7.0
## 2 Thống kê  9.5
## 3  Học máy 10.0
## 4       AI  9.0</code></pre>
</div>
<div id="sử-dụng-list-với-hàm-số" class="section level3" number="2.3.2">
<h3>
<span class="header-section-number">2.3.2</span> Sử dụng <span class="math inline">\(list\)</span> với hàm số<a class="anchor" aria-label="anchor" href="#s%E1%BB%AD-d%E1%BB%A5ng-list-v%E1%BB%9Bi-h%C3%A0m-s%E1%BB%91"><i class="fas fa-link"></i></a>
</h3>
<p>Hầu như tất cả các hàm số được xây dựng sẵn trong R đều cho kết quả đầu ra dưới dạng <span class="math inline">\(list\)</span>. Bạn đọc quan sát giá trị đầu ra của hàm có tên là <code><a href="https://rdrr.io/r/stats/uniroot.html">uniroot()</a></code> như sau</p>
<div class="sourceCode" id="cb357"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">f</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="va">x</span><span class="op">^</span><span class="fl">2</span> <span class="op">-</span> <span class="fl">1</span><span class="op">/</span><span class="fl">4</span></span>
<span><span class="va">result</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/uniroot.html">uniroot</a></span><span class="op">(</span><span class="va">f</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span> <span class="co"># đối tượng result có kiểu list</span></span></code></pre></div>
<pre><code>## [1] "list"</code></pre>
<div class="sourceCode" id="cb359"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span> <span class="co"># xem cấu trúc của đối tượng result</span></span></code></pre></div>
<pre><code>## List of 5
##  $ root      : num 0.5
##  $ f.root    : num -2.85e-05
##  $ iter      : int 6
##  $ init.it   : int NA
##  $ estim.prec: num 6.1e-05</code></pre>
<p>Hàm <code><a href="https://rdrr.io/r/stats/uniroot.html">uniroot()</a></code> được sử dụng để tìm nghiệm duy nhất của một hàm số trên một khoảng. Đoạn câu lệnh ở trên sử dụng hàm <span class="math inline">\(uniroot()\)</span> để tìm nghiệm duy nhất của phương trình <span class="math inline">\(x^2 - 1/4 = 0\)</span> trên khoảng <span class="math inline">\((0,1)\)</span>. Kết quả của hàm <code><a href="https://rdrr.io/r/stats/uniroot.html">uniroot()</a></code> là một list có 5 phần tử đều là các biến kiểu số với tên tương ứng là <span class="math inline">\(root\)</span>, <span class="math inline">\(f.root\)</span>, <span class="math inline">\(iter\)</span>, <span class="math inline">\(init.it\)</span>, và $ estim.prec$. Các hàm số phức tạp hơn sẽ có cấu trúc của kết quả đầu ra phức tạp hơn rất nhiều. Bạn đọc cần đọc kỹ hướng dẫn của các hàm để hiểu mỗi đối tượng con của kết quả đầu ra có ý nghĩa như thế nào.</p>
<p>Bạn đọc cũng nên sử dụng kiểu <span class="math inline">\(list\)</span> để làm đầu ra cho các hàm số tự xây dựng. Chúng ta sẽ quay trở lại ví dụ về xây dựng hàm số <span class="math inline">\(PV\)</span> để tính giá trị hiện tại của một dòng tiền. Đối với một dòng tiền tương lai, ngoài giá trị hiện tại, bạn đọc có thể quan tâm đến các giá trị khác như Macaulay Duration, Modified Duration, Dollar Duration, Convexity (ý nghĩa và cách tính các giá trị này ở trong phần phụ lục của chương này).</p>
<div class="sourceCode" id="cb361"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">summaryCF</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">i</span>,<span class="va">CF</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">n</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">CF</span><span class="op">)</span></span>
<span>  <span class="va">PV</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">CF</span><span class="op">/</span><span class="op">(</span><span class="op">(</span><span class="fl">1</span><span class="op">+</span><span class="va">i</span><span class="op">)</span><span class="op">^</span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">n</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">Mac_D</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">CF</span><span class="op">*</span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">n</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="op">(</span><span class="fl">1</span><span class="op">+</span><span class="va">i</span><span class="op">)</span><span class="op">^</span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">n</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="va">PV</span></span>
<span>  <span class="va">Mod_D</span><span class="op">&lt;-</span><span class="va">Mac_D</span><span class="op">/</span><span class="op">(</span><span class="fl">1</span><span class="op">+</span><span class="va">i</span><span class="op">)</span></span>
<span>  <span class="va">Dollar_D</span><span class="op">&lt;-</span><span class="va">PV</span><span class="op">*</span><span class="va">Mod_D</span><span class="op">*</span><span class="fl">100</span></span>
<span>  <span class="va">Convexity</span><span class="op">&lt;-</span><span class="va">Mod_D</span></span>
<span>  <span class="va">ket_qua</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>PV <span class="op">=</span> <span class="va">PV</span>, Mac_D <span class="op">=</span> <span class="va">Mac_D</span>, Mod_D <span class="op">=</span> <span class="va">Mod_D</span>, </span>
<span>               Dollar_D <span class="op">=</span> <span class="va">Dollar_D</span>, Convexity <span class="op">=</span> <span class="va">Convexity</span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">ket_qua</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<p>Chúng ta có thể sử dụng hàm <code>summary_CF()</code> để tính toán các đặc trưng của một trái phiếu với các thông số như sau:</p>
<div class="inline-table"><table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-174">Table 2.1: </span>Các thông số của một trái phiếu
</caption>
<thead><tr>
<th style="text-align:left;">
Thông số trái phiếu
</th>
<th style="text-align:left;">
Giá trị
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Ngày hiện tại
</td>
<td style="text-align:left;">
Ngày 01 tháng 10 năm 2023
</td>
</tr>
<tr>
<td style="text-align:left;">
Ngày đáo hạn
</td>
<td style="text-align:left;">
Ngày 30 tháng 09 năm 2035
</td>
</tr>
<tr>
<td style="text-align:left;">
Mệnh giá
</td>
<td style="text-align:left;">
10 tỷ Vnd
</td>
</tr>
<tr>
<td style="text-align:left;">
Lãi suất Coupon
</td>
<td style="text-align:left;">
9,25%
</td>
</tr>
<tr>
<td style="text-align:left;">
Số lần trả coupon trong năm
</td>
<td style="text-align:left;">
1 lần/năm
</td>
</tr>
<tr>
<td style="text-align:left;">
Lãi suất chiết khấu
</td>
<td style="text-align:left;">
5,00%
</td>
</tr>
</tbody>
</table></div>
<p>Chúng ta tạo ra dòng tiền tương lai của trái phiếu với các thông số như trên và sau đó sử dụng hàm <code>summary_CF()</code></p>
<div class="sourceCode" id="cb362"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Nhập liệu</span></span>
<span><span class="cn">F</span><span class="op">&lt;-</span><span class="fl">10</span> <span class="co"># mệnh giá trái phiếu, đơn vị tỷ đồng </span></span>
<span><span class="cn">T</span><span class="op">&lt;-</span><span class="fl">12</span> <span class="co"># 12 cho đến ngày đáo hạn</span></span>
<span><span class="va">c</span><span class="op">&lt;-</span><span class="fl">9.25</span><span class="op">/</span><span class="fl">100</span> <span class="co"># lãi suất coupon</span></span>
<span><span class="va">i</span><span class="op">&lt;-</span><span class="fl">5</span><span class="op">/</span><span class="fl">100</span> <span class="co"># lãi suất dùng để chiết khấu</span></span>
<span><span class="va">CF</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="va">c</span><span class="op">*</span><span class="cn">F</span>,<span class="op">(</span><span class="cn">T</span><span class="op">-</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span>,<span class="va">c</span><span class="op">*</span><span class="cn">F</span><span class="op">+</span><span class="cn">F</span><span class="op">)</span> <span class="co"># Dòng tiền tương lai của trái phiếu</span></span>
<span><span class="fu">summaryCF</span><span class="op">(</span><span class="va">i</span>,<span class="va">CF</span><span class="op">)</span></span></code></pre></div>
<pre><code>## $PV
## [1] 13.53023
## 
## $Mac_D
## [1] 7.884908
## 
## $Mod_D
## [1] 7.509436
## 
## $Dollar_D
## [1] 10160.44
## 
## $Convexity
## [1] 7.509436</code></pre>
<p>Chuyển sang một ví dụ khác khi sử dụng <span class="math inline">\(list\)</span> làm đầu ra cho một hàm số tự xây dựng. Khi bạn đọc tìm hiểu về giá trị của một véc-tơ kiểu số, chúng ta thường tính toán các giá trị đặc trưng như giá trị trung bình, giá trị lớn nhất, nhỏ nhất, các phân vị, và muốn xem phân phối các giá trị trong véc-tơ đó như thế nào. Chúng ta có thể tự viết một hàm số để thực hiện việc này với đầu ra là một <span class="math inline">\(list\)</span></p>
<div class="sourceCode" id="cb364"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">summary_vec</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">{</span></span>
<span>  <span class="va">do_dai</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="co"># độ dài của véc-tơ</span></span>
<span>  <span class="va">ty_le_na</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="va">do_dai</span><span class="op">*</span><span class="fl">100</span>,<span class="fl">2</span><span class="op">)</span>,<span class="st">"%"</span><span class="op">)</span> <span class="co"># % giá trị không quan sát được</span></span>
<span>  <span class="va">gioi_han</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">x</span>,na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">x</span>,na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="co"># lớn nhất và nhỏ nhất</span></span>
<span>  <span class="va">trung_binh</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span>,na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="va">do_lech_chuan</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">x</span>,na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="va">phan_vi</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">x</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.01</span>,<span class="fl">0.1</span>,<span class="fl">0.25</span>,<span class="fl">0.5</span>,<span class="fl">0.75</span>,<span class="fl">0.9</span>,<span class="fl">0.99</span><span class="op">)</span>,na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></span>
<span>  <span class="va">do_thi</span><span class="op">&lt;-</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">x</span><span class="op">)</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"black"</span>, fill <span class="op">=</span> <span class="st">"blue"</span>,alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">""</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">""</span><span class="op">)</span></span>
<span>  <span class="va">result</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>do_dai <span class="op">=</span> <span class="va">do_dai</span>, ty_le_na <span class="op">=</span> <span class="va">ty_le_na</span>, gioi_han <span class="op">=</span> <span class="va">gioi_han</span>,</span>
<span>               trung_binh <span class="op">=</span> <span class="va">trung_binh</span>, do_lech_chuan <span class="op">=</span> <span class="va">do_lech_chuan</span>, </span>
<span>               phan_vi <span class="op">=</span> <span class="va">phan_vi</span>, do_thi <span class="op">=</span> <span class="va">do_thi</span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">result</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<p>Chúng ta có thể sử dụng hàm <code>summary_vec()</code> để tổng hợp thông tin về lợi suất tính theo ngày của chỉ số FTSE (chỉ số cổ phiếu của 100 công ty có giá trị vốn hóa thị trường lớn nhất niêm yết trên Sở giao dịch chứng khoán London) trong năm 1991 đến năm 1999. Chỉ số này được lưu trong dữ liệu <span class="math inline">\(EuStockMarkets\)</span> có sẵn trong R.</p>
<div class="sourceCode" id="cb365"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">chi_so</span><span class="op">&lt;-</span><span class="va">EuStockMarkets</span><span class="op">[</span>,<span class="fl">4</span><span class="op">]</span> <span class="co"># lấy chỉ số FTSE ra từ cột thứ 4 của EuStockMarkets</span></span>
<span><span class="va">n</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">chi_so</span><span class="op">)</span> <span class="co"># độ dài của chuỗi chỉ số chứng khoán</span></span>
<span><span class="va">loi_suat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">chi_so</span><span class="op">[</span><span class="fl">2</span><span class="op">:</span><span class="va">n</span><span class="op">]</span><span class="op">/</span><span class="va">chi_so</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="op">(</span><span class="va">n</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">]</span><span class="op">)</span> <span class="co"># lợi suất của chỉ số</span></span>
<span><span class="fu">summary_vec</span><span class="op">(</span><span class="va">loi_suat</span><span class="op">)</span></span></code></pre></div>
<pre><code>## $do_dai
## [1] 1859
## 
## $ty_le_na
## [1] "0 %"
## 
## $gioi_han
## [1] -0.04139903  0.05439552
## 
## $trung_binh
## [1] 0.0004319851
## 
## $do_lech_chuan
## [1] 0.007957728
## 
## $phan_vi
##            1%           10%           25%           50%           75% 
## -2.060655e-02 -9.139666e-03 -4.318778e-03  8.021069e-05  5.253592e-03 
##           90%           99% 
##  9.714781e-03  1.931723e-02 
## 
## $do_thi</code></pre>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-177-1.png" width="672"></div>
<p>Một lợi thế khác của đối tượng kiểu <span class="math inline">\(list\)</span> là đẩy nhanh tốc độ tính toán khi dùng các hàm họ <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>. Chúng ta sẽ thảo luận vấn đề này trong phần tiếp theo của cuốn sách.</p>
</div>
</div>
<div id="các-hàm-họ-apply" class="section level2" number="2.4">
<h2>
<span class="header-section-number">2.4</span> Các hàm họ <code>apply()</code><a class="anchor" aria-label="anchor" href="#c%C3%A1c-h%C3%A0m-h%E1%BB%8D-apply"><i class="fas fa-link"></i></a>
</h2>
<p>Nhóm hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> là nhóm hàm có sẵn trong R cho phép bạn đọc thực hiện lặp đi lặp lại một hàm số trên nhiều đối tượng. Về cơ bản nhóm hàm này hoạt động giống như một vòng lặp nhưng câu lệnh viết bằng nhóm hàm này sẽ chạy nhanh hơn và đơn giản hơn viết vòng lặp rất nhiểu.</p>
<p>Các hàm mà chúng tôi sẽ giới thiệu đến bạn đọc trong phần này bao gồm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>, <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> và <code>sapply</code>. Còn nhiều hàm khác thuộc nhóm hàm này như <code><a href="https://rdrr.io/r/base/lapply.html">vapply()</a></code>, <code><a href="https://rdrr.io/r/base/tapply.html">tapply()</a></code>, <code><a href="https://rdrr.io/r/base/mapply.html">mapply()</a></code>, …, nhưng về nguyên tắc hoạt động của các hàm này là tương tự và chỉ khác ở chỗ chúng áp dụng trên các loại đối tượng khác nhau nên bạn đọc có thể tự tìm hiểu mà không gặp khó khăn nào.</p>
<div id="hàm-apply" class="section level3" number="2.4.1">
<h3>
<span class="header-section-number">2.4.1</span> Hàm <code>apply()</code><a class="anchor" aria-label="anchor" href="#h%C3%A0m-apply"><i class="fas fa-link"></i></a>
</h3>
<p>Cho một véc-tơ <span class="math inline">\(x\)</span> kiểu số và một hàm <span class="math inline">\(f\)</span>, chẳng hạn như <span class="math inline">\(f(x) = x^2\)</span>. Khi bạn đọc viết <code>f(x)</code> R sẽ hiểu rằng bạn đang thực hiện hàm số <span class="math inline">\(f\)</span> cho từng phần tử của véc-tơ <span class="math inline">\(x\)</span> và sẽ trả lại giá trị là một véc-tơ mà từng phần tử tương ứng là bình phương của các phần tử trong <span class="math inline">\(x\)</span>. Việc thực hiện hàm <span class="math inline">\(f\)</span> trên véc-tơ <span class="math inline">\(x\)</span> diễn ra một cách đồng thời và hiệu quả hơn so với việc viết một vòng lặp để tính hàm <span class="math inline">\(f\)</span> trên từng phần tử của <span class="math inline">\(x\)</span>.</p>
<div class="sourceCode" id="cb367"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">x</span><span class="op">&lt;-</span><span class="fl">1</span><span class="op">:</span><span class="fl">5</span>; <span class="va">f</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="va">x</span><span class="op">^</span><span class="fl">2</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/pryr/man/f.html">f</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="co"># f được áp dụng trên từng phần tử của x</span></span></code></pre></div>
<pre><code>## [1]  1  4  9 16 25</code></pre>
<p>Điều gì xảy ra khi <span class="math inline">\(x\)</span> không phải là một véc-tơ đồng các phần tử con của <span class="math inline">\(x\)</span> không phải là một biến, chẳng hạn như</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(x\)</span> là một ma trận và bạn muốn tính toán một hàm <span class="math inline">\(f\)</span> trên các phần tử con của <span class="math inline">\(x\)</span> là một véc-tơ hàng hoặc một véc-tơ cột.</p></li>
<li><p><span class="math inline">\(x\)</span> là một dữ liệu và bạn muốn thực hiện một hàm <span class="math inline">\(f\)</span> trên tất cả các cột dữ liệu.</p></li>
<li><p><span class="math inline">\(x\)</span> là một list và bạn muốn thực hiện một hàm <span class="math inline">\(f\)</span> trên tất cả các đối tượng con của <span class="math inline">\(x\)</span>.</p></li>
</ol>
<p>Các hàm thuộc họ <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> sẽ giúp bạn đọc thực hiện tác tính toán như vậy. Cách viết hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> như sau:</p>
<div class="sourceCode" id="cb369"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">MARGIN</span>, <span class="va">FUN</span>, <span class="va">...</span><span class="op">)</span></span></code></pre></div>
<p>trong đó <span class="math inline">\(x\)</span> là một ma trận, một mảng nhiều chiều, hoặc một dữ liệu; <span class="math inline">\(MARGIN\)</span> là một số, hoặc véc-tơ chỉ số cho biết hàm sẽ áp dụng trên chiều (hoặc các chiều) nào, và <span class="math inline">\(FUN\)</span> là hàm số mà bạn muốn thực hiện. Ví dụ như bạn đọc muốn tính giá trị trung bình của mỗi cột của một ma trận <span class="math inline">\(M\)</span>, hãy sử dụng câu lệnh như sau</p>
<div class="sourceCode" id="cb370"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">100</span>,<span class="fl">20</span>,<span class="fl">5</span><span class="op">)</span> <span class="co"># ma trận kích thước 20 * 5</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">M</span>, MARGIN <span class="op">=</span> <span class="fl">2</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span> <span class="co"># MARGIN = 2 nghĩa là áp dụng theo cột (1 nghĩa là theo hàng)  </span></span></code></pre></div>
<pre><code>## [1] 10.5 30.5 50.5 70.5 90.5</code></pre>
<p>Do ma trận <span class="math inline">\(M\)</span> có 5 cột nên giá trị trả lại là một véc-tơ kiểu số có độ dài bằng 5. Véc-tơ này chứa giá trị là trung bình của các cột thứ tự 1, 2, 3, 4, và 5 của ma trận <span class="math inline">\(M\)</span>.</p>
<p>Về nguyên tắc đối tượng sử dụng trong hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> là ma trận hoặc mảng nhiều chiều. Bạn đọc cũng có thể sử dụng hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> trên đối tượng là dữ liệu (data.frame). Khi đối tượng của hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> có từ 3 chiều trở lên, giá trị của tùy biến <span class="math inline">\(MARGIN\)</span> có thể là một số hoặc một véc-tơ. Thật vậy,</p>
<div class="sourceCode" id="cb372"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">Ar</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">array</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">20</span>,dim<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="co"># mảng kích thước 5 * 2 * 2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">Ar</span>, MARGIN <span class="op">=</span> <span class="fl">3</span>, FUN <span class="op">=</span> <span class="va">mean</span><span class="op">)</span> <span class="co"># MARGIN = 3 nghĩa là áp dụng hàm mean theo chiều thứ 3  </span></span></code></pre></div>
<pre><code>## [1]  5.5 15.5</code></pre>
<p>Giá trị trả lại sẽ là một véc-tơ có độ dài là 2, phần tử thứ nhất là giá trị trung bình của các phần tử thuộc ma trận kích thước <span class="math inline">\(5 \times 2\)</span> thứ nhất (ma trận <span class="math inline">\(Ar[,,1]\)</span>) và phần tử thứ hai là giá trị trung bình của các phần tử thuộc ma trận kích thước <span class="math inline">\(5 \times 2\)</span> thứ hai (ma trận <span class="math inline">\(Ar[,,2]\)</span>). Chúng ta có thể kiểm tra kết quả như sau:</p>
<div class="sourceCode" id="cb374"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Ar</span><span class="op">[</span>,,<span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="co"># bằng phần tử thứ nhất khi dùng apply</span></span></code></pre></div>
<pre><code>## [1] 5.5</code></pre>
<div class="sourceCode" id="cb376"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Ar</span><span class="op">[</span>,,<span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="co"># bằng phần tử thứ hai khi dùng apply</span></span></code></pre></div>
<pre><code>## [1] 15.5</code></pre>
<p>Chúng ta có thể áp dụng đồng thời hàm <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> theo chiều thứ 2 và chiều thứ 3 trên mảng <span class="math inline">\(Ar\)</span> như sau</p>
<div class="sourceCode" id="cb378"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">Ar</span>, MARGIN <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">3</span><span class="op">)</span>, <span class="va">mean</span><span class="op">)</span> <span class="co"># MARGIN = c(2,3) nghĩa là áp dụng hàm mean theo chiều thứ 2 và 3  </span></span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    3   13
## [2,]    8   18</code></pre>
<p>Kết quả thu được sẽ là một ma trận kích thước <span class="math inline">\(2 \times 2\)</span> mà các phần tử sẽ tương ứng với giá trị trung bình:</p>
<ul>
<li><p>Phần tử ở vị trí [1,1] của ma trận kết quả là giá trị trung bình của véc-tơ <span class="math inline">\(Ar[,1,1]\)</span></p></li>
<li><p>Phần tử ở vị trí [1,2] của ma trận kết quả là giá trị trung bình của véc-tơ <span class="math inline">\(Ar[,1,2]\)</span></p></li>
<li><p>Phần tử ở vị trí [2,1] của ma trận kết quả là giá trị trung bình của véc-tơ <span class="math inline">\(Ar[,2,1]\)</span></p></li>
<li><p>Phần tử ở vị trí [2,2] của ma trận kết quả là giá trị trung bình của véc-tơ <span class="math inline">\(Ar[,2,2]\)</span></p></li>
</ul>
<p>Chúng ta có thể so sánh giá trị trung bình của các véc-tơ với ma trận kết quả của hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>:</p>
<div class="sourceCode" id="cb380"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Ar</span><span class="op">[</span>,<span class="fl">1</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="co"># bằng phần tử ở vị trí [1,1] của ma trận kết quả</span></span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb382"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Ar</span><span class="op">[</span>,<span class="fl">1</span>,<span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="co"># bằng phần tử ở vị trí [1,2] của ma trận kết quả</span></span></code></pre></div>
<pre><code>## [1] 13</code></pre>
<div class="sourceCode" id="cb384"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Ar</span><span class="op">[</span>,<span class="fl">2</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="co"># bằng phần tử ở vị trí [1,2] của ma trận kết quả</span></span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<div class="sourceCode" id="cb386"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Ar</span><span class="op">[</span>,<span class="fl">2</span>,<span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="co"># bằng phần tử ở vị trí [1,2] của ma trận kết quả</span></span></code></pre></div>
<pre><code>## [1] 18</code></pre>
<p>Hàm số sử dụng với tùy biến <span class="math inline">\(FUN\)</span> có thể là hàm số có sẵn trong R và các thư viện cài đặt bổ sung, hoặc cũng có thể là một hàm số mà bạn đọc tự xây dựng. Khi các câu lệnh của hàm số tự xây dựng ngắn gọn, bạn đọc có thể định nghĩa hàm số đó bên trong hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>. Giá trị đầu ra của hàm số được tự định nghĩa cũng có thể là một véc-tơ, thậm chí là một ma trận hay là một mảng nhiều chiều, thậm chí là một <span class="math inline">\(list\)</span>. Nếu kết quả đầu ra của hàm sử dụng trong <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> là một ma trận hoặc mảng nhiều chiều, R sẽ chuyển ma trận hoặc mảng nhiều chiều về dạng véc-tơ. Trong trường hợp đầu ra của hàm tự định nghĩa là một <span class="math inline">\(list\)</span>, giá trị đầu ra sẽ là một ma trận hoặc mảng nhiều chiều mà mỗi phần tử con là một list. Dưới đây là một ví dụ mà giá trị đầu ra là một véc-tơ ba chiều.</p>
<div class="sourceCode" id="cb388"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">M</span>, <span class="fl">2</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]  [,5]
## [1,]  1.0 21.0 41.0 61.0  81.0
## [2,] 10.5 30.5 50.5 70.5  90.5
## [3,] 20.0 40.0 60.0 80.0 100.0</code></pre>
<p>Kết quả nhận được sẽ là một ma trận kích thước <span class="math inline">\(3 \times 5\)</span>. Cột thứ nhất của ma trận kết quả nhận giá trị (1, 10.5, 20) tương ứng với các giá trị <span class="math inline">\(min\)</span>, <span class="math inline">\(mean\)</span>, và <span class="math inline">\(max\)</span> của véc-tơ <span class="math inline">\(M[,1]\)</span>.</p>
<div class="sourceCode" id="cb390"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span></span></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20</code></pre>
<div class="sourceCode" id="cb392"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">M</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">M</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">M</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1]  1.0 10.5 20.0</code></pre>
<p>Bạn đọc cũng có thể tự xây dựng hàm số trên môi trường chung sau đó gọi tên hàm số này trong hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>. Nếu hàm số tự xây dựng là hàm số có tham số khác ngoài <span class="math inline">\(x\)</span>, bạn đọc cần phải khai báo giá trị cho tham số đó trong môi trường cục bộ của hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>:</p>
<div class="sourceCode" id="cb394"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">my_range</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">a</span><span class="op">)</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">x</span><span class="op">^</span><span class="va">a</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">x</span><span class="op">^</span><span class="va">a</span><span class="op">)</span><span class="op">)</span> <span class="co"># hàm số có tham số khác là a</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">M</span>, <span class="fl">2</span>, <span class="va">my_range</span>, a <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="co"># cần khai báo giá trị tham số a của my_range trong hàm apply</span></span></code></pre></div>
<pre><code>## [1]  399 1159 1919 2679 3439</code></pre>
<p>Khi tham số của hàm số mà bạn đọc muốn áp dụng trên ma trận là không cố định mà thay đổi theo một chiều của <span class="math inline">\(x\)</span> thì không nên khai báo giá trị của tham số theo dạng véc-tơ trong hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>. Thật vậy, giả sử bạn đọc muốn tính các giá trị phân vị ở mức xác suất 10% và 90% lần lượt của véc-tơ hàng thứ nhất và véc-tơ hàng thứ hai của một ma trận M kích thước <span class="math inline">\(2 \times 10\)</span>. Hàm số <code>quantile(x, probs = p)</code> là hàm số có sẵn trong R được sử dụng để tính giá trị phân vị tại mức xác suất <span class="math inline">\(p\)</span> của véc-tơ số <span class="math inline">\(x\)</span>. Hãy quan sát kết quả của hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> khi sử dụng tham số <span class="math inline">\(probs\)</span> của hàm <code><a href="https://rdrr.io/r/stats/quantile.html">quantile()</a></code> dưới dạng véc-tơ:</p>
<div class="sourceCode" id="cb396"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">20</span>,<span class="fl">2</span>,<span class="fl">10</span><span class="op">)</span> <span class="co"># ma trận 2 * 10</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">M</span>, <span class="fl">1</span>, <span class="va">quantile</span>, probs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.1</span>,<span class="fl">0.9</span><span class="op">)</span><span class="op">)</span> <span class="co"># MARGIN = 1 nghĩa là tính theo các hàng của M</span></span></code></pre></div>
<pre><code>##     [,1] [,2]
## 10%  2.8  3.8
## 90% 17.2 18.2</code></pre>
<div class="sourceCode" id="cb398"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">M</span><span class="op">[</span><span class="fl">1</span>,<span class="op">]</span>,<span class="fl">0.1</span><span class="op">)</span> <span class="co"># giá trị mong muốn</span></span></code></pre></div>
<pre><code>## 10% 
## 2.8</code></pre>
<div class="sourceCode" id="cb400"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">M</span><span class="op">[</span><span class="fl">2</span>,<span class="op">]</span>,<span class="fl">0.9</span><span class="op">)</span> <span class="co"># giá trị mong muốn</span></span></code></pre></div>
<pre><code>##  90% 
## 18.2</code></pre>
<p>Bạn đọc có thể thấy rằng kết quả của hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> khi tham số <span class="math inline">\(probs\)</span> là một véc-tơ là một ma trận, trong đó cột thứ nhất là giá trị phân vị tại các mức xác suất 10% và 90% của véc-tơ <span class="math inline">\(M[1,]\)</span> và cột thứ hai giá trị phân vị tại các mức xác suất 10% và 90% của véc-tơ <span class="math inline">\(M[2,]\)</span>. Giá trị chúng ta mong muốn lấy ra chính là các số nằm trên đường chéo chính của ma trận kết quả. Sẽ không có khó khăn gì nếu số lượng hàng của ma trận <span class="math inline">\(M\)</span> nhỏ. Bạn đọc sẽ gặp vấn đề khi số lượng véc-tơ được áp dụng là lớn bởi kích thước của ma trận kết quả sẽ tăng lên theo cấp số nhân. Thật vậy, nếu <span class="math inline">\(M\)</span> có <span class="math inline">\(n\)</span> hàng và hàm số được áp dụng có 1 tham số, ma trận kết quả sẽ có kích thước sẽ là $ n n$ nếu bạn đọc sử dụng trực tiếp hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>. Chẳng hạn như bạn muốn tính giá trị phân vị ở các mức xác suất 10%, 30%, 50%, 70%, và 90% của lần lượt các véc-tơ hàng thứ 1, 2, 3, 4, và 5 của một ma trận <span class="math inline">\(M\)</span> kích thước <span class="math inline">\(5 \times 10\)</span>.</p>
<div class="sourceCode" id="cb402"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">50</span>,<span class="fl">5</span>,<span class="fl">10</span><span class="op">)</span> <span class="co"># ma trận 5 * 10</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">M</span>, <span class="fl">1</span>, <span class="va">quantile</span>, probs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.1</span>,<span class="fl">0.3</span>,<span class="fl">0.5</span>,<span class="fl">0.7</span>,<span class="fl">0.9</span><span class="op">)</span><span class="op">)</span> <span class="co"># ma trận kết quả kích thước 5 * 5</span></span></code></pre></div>
<pre><code>##     [,1] [,2] [,3] [,4] [,5]
## 10%  5.5  6.5  7.5  8.5  9.5
## 30% 14.5 15.5 16.5 17.5 18.5
## 50% 23.5 24.5 25.5 26.5 27.5
## 70% 32.5 33.5 34.5 35.5 36.5
## 90% 41.5 42.5 43.5 44.5 45.5</code></pre>
<div class="sourceCode" id="cb404"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">M</span>, <span class="fl">1</span>, <span class="va">quantile</span>, probs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.1</span>,<span class="fl">0.3</span>,<span class="fl">0.5</span>,<span class="fl">0.7</span>,<span class="fl">0.9</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="co"># lấy ra đường chéo chính</span></span></code></pre></div>
<pre><code>## [1]  5.5 15.5 25.5 35.5 45.5</code></pre>
<p>Điều gì xảy ra khi ma trận <span class="math inline">\(M\)</span> có <span class="math inline">\(10^4\)</span> véc-tơ hàng? Ma trận kết quả sẽ có kích thước là <span class="math inline">\(10^4 \times 10^4\)</span>. Khi ma trận <span class="math inline">\(M\)</span> có <span class="math inline">\(10^5\)</span> véc-tơ hàng? Ma trận kết quả sẽ có kích thước là <span class="math inline">\(10^5 \times 10^5\)</span> và R sẽ báo lỗi vì bộ nhớ không đủ để lưu một ma trận có kích thước như vậy.</p>
<p>Một cách đơn giản để tiết kiệm thời gian và bộ nhớ khi áp dụng hàm số có tham số là hãy thêm tham số vào như là một phần của ma trận <span class="math inline">\(M\)</span> và điều chỉnh lại hàm <code><a href="https://rdrr.io/r/stats/quantile.html">quantile()</a></code> trước khi sử dụng hàm <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code></p>
<div class="sourceCode" id="cb406"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">M1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">M</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.1</span>,<span class="fl">0.3</span>,<span class="fl">0.5</span>,<span class="fl">0.7</span>,<span class="fl">0.9</span><span class="op">)</span><span class="op">)</span> <span class="co"># thêm tham số vào cột cuối của ma trận M</span></span>
<span><span class="va">my_quantile</span><span class="op">&lt;-</span><span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">{</span> <span class="co"># định nghĩa lại hàm quantile mà tham số p là giá trị cuối cùng trong véc-tơ</span></span>
<span>  <span class="va">n</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">x</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="op">(</span><span class="va">n</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">]</span>, <span class="va">x</span><span class="op">[</span><span class="va">n</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">M1</span>, <span class="fl">1</span>, <span class="va">my_quantile</span><span class="op">)</span> <span class="co"># áp dụng hàm mới trên ma trận mới</span></span></code></pre></div>
<pre><code>## [1]  5.5 15.5 25.5 35.5 45.5</code></pre>
</div>
<div id="hàm-lapply-và-sapply." class="section level3" number="2.4.2">
<h3>
<span class="header-section-number">2.4.2</span> Hàm <code>lapply()</code> và <code>sapply()</code>.<a class="anchor" aria-label="anchor" href="#h%C3%A0m-lapply-v%C3%A0-sapply."><i class="fas fa-link"></i></a>
</h3>
<p>Cơ chế hoạt động của <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> tương tự như <code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code> và chỉ khác ở đối tượng áp dụng và cấu trúc của kết quả đầu ra. <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> thường áp dụng trên các đối tượng kiểu <span class="math inline">\(list\)</span> hoặc các kiểu đối tượng mà có thể sử dụng ký hiệu <span class="math inline">\(\$\)</span> để gọi phần tử con chẳng hạn như <span class="math inline">\(data.frame\)</span> hoặc <span class="math inline">\(tibbles\)</span>. Chúng ta sẽ thảo luận về các đối tượng này ở phần sau của cuốn sách. Khi bạn đọc sử dụng hàm <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code>, bạn không cần phải sử dụng tùy biến <span class="math inline">\(MARGIN\)</span> bởi vì <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> sẽ luôn luôn hiểu các đối tượng được tác động đến là tất cả các đối tượng con của <span class="math inline">\(list\)</span>.</p>
<div class="sourceCode" id="cb408"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>x1 <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">10</span>, </span>
<span>          x2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="cn">TRUE</span>,<span class="cn">FALSE</span>,<span class="cn">TRUE</span>,<span class="cn">TRUE</span><span class="op">)</span>, </span>
<span>          x3 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">6</span>,<span class="fl">2</span>,<span class="fl">3</span><span class="op">)</span>, </span>
<span>          x4 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>x41 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span>, x42 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span> <span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">mean</span><span class="op">)</span> <span class="co"># áp dụng hàm mean trên tất cả các phần tử con của x</span></span></code></pre></div>
<pre><code>## $x1
## [1] 5.5
## 
## $x2
## [1] 0.75
## 
## $x3
## [1] 3.5
## 
## $x4
## [1] NA</code></pre>
<p>Kết quả của <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> là một list có số lượng phần tử và tên các phần tử con giống với véc-tơ <span class="math inline">\(x\)</span>. Trong trường hợp áp dụng hàm <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, mỗi giá trị nằm trong <span class="math inline">\(list\)</span> kết quả là giá trị trung bình của phần tử có tên tương ứng nằm trong <span class="math inline">\(list\)</span> ban đầu. Do hàm <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> không thể sử dụng với một <span class="math inline">\(list\)</span> nên phần tử <span class="math inline">\(x4\)</span> của kết quả nhận giá trị <span class="math inline">\(NA\)</span>.</p>
<p>Hàm <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code> có cơ chế hoạt động hoàn toàn tương tự như <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> và chỉ khác ở chỗ kết quả đầu ra là dưới dạng véc-tơ, ma trận, hoặc mảng. Thật vậy, vẫn với đối tượng <span class="math inline">\(x\)</span> kiểu <span class="math inline">\(list\)</span> ở trên, chúng ta sử dụng <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code> thay vì <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> sẽ cho kết quả dưới dạng véc-tơ thay vì dưới dạng <span class="math inline">\(list\)</span></p>
<div class="sourceCode" id="cb410"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">mean</span><span class="op">)</span> <span class="co"># áp dụng hàm mean trên tất cả các phần tử con của x</span></span></code></pre></div>
<pre><code>##   x1   x2   x3   x4 
## 5.50 0.75 3.50   NA</code></pre>
<p>Các hàm <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> và <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code> thường xuyên được sử dụng khi làm việc với dữ liệu vì R lưu dữ liệu dưới dạng các <span class="math inline">\(data.frame\)</span> hoặc <span class="math inline">\(tibbles\)</span>. Khi sử dụng các hàm <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> và <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code> với dữ liệu, các đối tượng được tác động đến sẽ luôn luôn là các véc-tơ cột. Hãy quan sát ví dụ dưới đây khi sử dụng <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code> để tính tỷ lệ giá trị không quan sát được của mỗi véc-tơ cột của một dữ liệu có tên là <span class="math inline">\(gapminder\)</span> nằm trong thư viện <span class="math inline">\(dslabs\)</span>.</p>
<div class="sourceCode" id="cb412"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">dslabs</span><span class="op">)</span></span>
<span><span class="va">s1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">gapminder</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="co"># tỷ lệ không quan sát được của mỗi cột trong dữ liệu</span></span>
<span><span class="va">s1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="va">s1</span><span class="op">)</span> <span class="co"># sắp xếp s1 theo thứ tự tăng dần</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">s1</span><span class="op">)</span> <span class="co"># hiển thị s1</span></span></code></pre></div>
<pre><code>##          country             year  life_expectancy        continent 
##       0.00000000       0.00000000       0.00000000       0.00000000 
##           region       population        fertility infant_mortality 
##       0.00000000       0.01754386       0.01773352       0.13779042 
##              gdp 
##       0.28183973</code></pre>
<div class="sourceCode" id="cb414"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span><span class="op">(</span><span class="va">s1</span>,col <span class="op">=</span> <span class="st">"lightskyblue"</span>, </span>
<span>        ylab <span class="op">=</span> <span class="st">"Tỷ lệ"</span>,</span>
<span>        xlab <span class="op">=</span> <span class="st">"Tên biến/cột"</span>,</span>
<span>        main <span class="op">=</span> <span class="st">"Tỷ lệ missing value của các cột dữ liệu Gapminder"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="07-lap-trinh-co-ban-voi-R_files/figure-html/unnamed-chunk-193-1.png" width="672"></div>
</div>
</div>
<div id="phụ-lục-1" class="section level2" number="2.5">
<h2>
<span class="header-section-number">2.5</span> Phụ lục<a class="anchor" aria-label="anchor" href="#ph%E1%BB%A5-l%E1%BB%A5c-1"><i class="fas fa-link"></i></a>
</h2>
<div id="kiến-thức-nâng-cao-liên-quan-đến-ma-trận" class="section level3" number="2.5.1">
<h3>
<span class="header-section-number">2.5.1</span> Kiến thức nâng cao liên quan đến ma trận<a class="anchor" aria-label="anchor" href="#ki%E1%BA%BFn-th%E1%BB%A9c-n%C3%A2ng-cao-li%C3%AAn-quan-%C4%91%E1%BA%BFn-ma-tr%E1%BA%ADn"><i class="fas fa-link"></i></a>
</h3>
<p>Các kiến thức liên quan đến ma trận trong phần này đòi hỏi bạn đọc cần có kiến thức nâng cao hơn. Nếu bạn đọc cảm thấy không cần thiết có thể bỏ qua vì các kiến thức được sử dụng trong phần này sẽ được nhắc lại khi có ứng dụng cụ thể.</p>
<div id="giá-trị-riêng-và-véc-tơ-riêng-của-ma-trận" class="section level4" number="2.5.1.1">
<h4>
<span class="header-section-number">2.5.1.1</span> Giá trị riêng và véc-tơ riêng của ma trận<a class="anchor" aria-label="anchor" href="#gi%C3%A1-tr%E1%BB%8B-ri%C3%AAng-v%C3%A0-v%C3%A9c-t%C6%A1-ri%C3%AAng-c%E1%BB%A7a-ma-tr%E1%BA%ADn"><i class="fas fa-link"></i></a>
</h4>
</div>
<div id="ma-trận-hiệp-phương-sai" class="section level4" number="2.5.1.2">
<h4>
<span class="header-section-number">2.5.1.2</span> Ma trận hiệp phương sai<a class="anchor" aria-label="anchor" href="#ma-tr%E1%BA%ADn-hi%E1%BB%87p-ph%C6%B0%C6%A1ng-sai"><i class="fas fa-link"></i></a>
</h4>
</div>
</div>
<div id="các-giá-trị-đặc-trưng-của-một-dòng-tiền-tương-lai" class="section level3" number="2.5.2">
<h3>
<span class="header-section-number">2.5.2</span> Các giá trị đặc trưng của một dòng tiền tương lai<a class="anchor" aria-label="anchor" href="#c%C3%A1c-gi%C3%A1-tr%E1%BB%8B-%C4%91%E1%BA%B7c-tr%C6%B0ng-c%E1%BB%A7a-m%E1%BB%99t-d%C3%B2ng-ti%E1%BB%81n-t%C6%B0%C6%A1ng-lai"><i class="fas fa-link"></i></a>
</h3>
<div id="giá-trị-hiện-tại-và-tỷ-suất-sinh-lời-nội-bộ" class="section level4" number="2.5.2.1">
<h4>
<span class="header-section-number">2.5.2.1</span> Giá trị hiện tại và tỷ suất sinh lời nội bộ<a class="anchor" aria-label="anchor" href="#gi%C3%A1-tr%E1%BB%8B-hi%E1%BB%87n-t%E1%BA%A1i-v%C3%A0-t%E1%BB%B7-su%E1%BA%A5t-sinh-l%E1%BB%9Di-n%E1%BB%99i-b%E1%BB%99"><i class="fas fa-link"></i></a>
</h4>
<p>Giá trị hiện tại của một dòng tiền <span class="math inline">\(CF\)</span> với lãi suất <span class="math inline">\(i\)</span> tính theo kiểu gộp được tính như sau
<span class="math display">\[\begin{align}
PV(CF) = \sum\limits_{t=1}^n \ \cfrac{CF_t}{(1+i)^t}
\end{align}\]</span></p>
<p>Giá trị hiện tại của một dòng tiền là một thước đo cho giá trị của tài sản tạo ra dòng tiền đó. Nhìn chung, tài sản nào có giá trị hiện tại lớn hơn thì có giá trị cao hơn.</p>
<p>Tỷ suất sinh lời nội bộ (Internal rate of return hay IRR) là mức lãi suất <span class="math inline">\(i_0\)</span> mà tính theo mức lãi suất này giá trị hiện tại của một dòng tiền bằng 0. Tỷ suất sinh lời nội bộ không tồn tại nếu dòng tiền tương lai của một tài sản chỉ có giá trị dương (hoặc âm).</p>
</div>
<div id="durations-và-convexity" class="section level4" number="2.5.2.2">
<h4>
<span class="header-section-number">2.5.2.2</span> Durations và convexity<a class="anchor" aria-label="anchor" href="#durations-v%C3%A0-convexity"><i class="fas fa-link"></i></a>
</h4>
<p>Duration không phải là thước đo thời gian từ lúc bắt đầu đến lúc đáo hạn của dòng tiền mà là một thước đo cho sự nhạy cảm của giá trị hiện tại của dòng tiền theo sự thay đổi của lãi suất.</p>
<!-- # REFERENCE -->
<!-- ### Source from thesis -->
<!-- **1.** Chen, Chun-houh, Wolfgang Karl Härdle, and Antony Unwin, eds (2007). *Handbook of data visualization.* \ -->
<!-- **2.** Aparicio, Manuela, and Carlos J. Costa. (2015). *Data visualization - Communication design quarterly review.* \ -->
<!-- **3.** Hadley Wickham. (2010). *A Layered Grammar of Graphics.* \ -->
<!-- ### Souce from website -->
<!-- **4.** [https://www.tableau.com/learn/articles/data-visualization](https://www.tableau.com/learn/articles/data-visualization) \ -->
<!-- **5.** [https://www.r-graph-gallery.com/ggplot2-package.html](https://www.r-graph-gallery.com/ggplot2-package.html) \ -->
<!-- **6.** [http://r-statistics.co/ggplot2-Tutorial-With-R.html](http://r-statistics.co/ggplot2-Tutorial-With-R.html) \ -->
<!-- **7.** [https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf](https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf) \ -->
<!-- **8.** [https://www.kaggle.com/](https://www.kaggle.com/) \ -->

<pre><code>## 
## Attaching package: 'dplyr'</code></pre>
<pre><code>## The following object is masked from 'package:gridExtra':
## 
##     combine</code></pre>
<pre><code>## The following object is masked from 'package:kableExtra':
## 
##     group_rows</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre><code>## 
## Attaching package: 'lubridate'</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     date, intersect, setdiff, union</code></pre>
</div>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="index.html"><span class="header-section-number">1</span> Kiến thức R cơ bản</a></div>
<div class="next"><a href="ph%C3%A2n-t%C3%ADch-d%E1%BB%AF-li%E1%BB%87u-b%E1%BA%B1ng-r.html"><span class="header-section-number">3</span> Phân tích dữ liệu bằng R</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#ma-tr%E1%BA%ADn-m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u-v%C3%A0-list"><span class="header-section-number">2</span> Ma trận, mảng nhiều chiều và \(list\)</a></li>
<li>
<a class="nav-link" href="#ma-tr%E1%BA%ADn"><span class="header-section-number">2.1</span> Ma trận</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#kh%E1%BB%9Fi-t%E1%BA%A1o-ma-tr%E1%BA%ADn"><span class="header-section-number">2.1.1</span> Khởi tạo ma trận</a></li>
<li><a class="nav-link" href="#c%C3%A1ch-l%E1%BA%A5y-ph%E1%BA%A7n-t%E1%BB%AD-con-v%C3%A0-ma-tr%E1%BA%ADn-con-c%E1%BB%A7a-ma-tr%E1%BA%ADn."><span class="header-section-number">2.1.2</span> Cách lấy phần tử con và ma trận con của ma trận.</a></li>
<li><a class="nav-link" href="#c%C3%A1c-ph%C3%A9p-to%C3%A1n-tr%C3%AAn-ma-tr%E1%BA%ADn."><span class="header-section-number">2.1.3</span> Các phép toán trên ma trận.</a></li>
<li><a class="nav-link" href="#ph%C3%A9p-nh%C3%A2n-ma-tr%E1%BA%ADn"><span class="header-section-number">2.1.4</span> Phép nhân ma trận</a></li>
<li><a class="nav-link" href="#ma-tr%E1%BA%ADn-%C4%91%C6%B0%E1%BB%9Dng-ch%C3%A9o-v%C3%A0-ma-tr%E1%BA%ADn-%C4%91%C6%A1n-v%E1%BB%8B."><span class="header-section-number">2.1.5</span> Ma trận đường chéo và ma trận đơn vị.</a></li>
<li><a class="nav-link" href="#%C4%91%E1%BB%8Bnh-th%E1%BB%A9c-c%E1%BB%A7a-ma-tr%E1%BA%ADn"><span class="header-section-number">2.1.6</span> Định thức của ma trận</a></li>
<li><a class="nav-link" href="#ma-tr%E1%BA%ADn-ngh%E1%BB%8Bch-%C4%91%E1%BA%A3o"><span class="header-section-number">2.1.7</span> Ma trận nghịch đảo</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u"><span class="header-section-number">2.2</span> Mảng nhiều chiều</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#kh%E1%BB%9Fi-t%E1%BA%A1o-m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u"><span class="header-section-number">2.2.1</span> Khởi tạo mảng nhiều chiều</a></li>
<li><a class="nav-link" href="#s%E1%BB%AD-d%E1%BB%A5ng-m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u-%C4%91%E1%BB%83-bi%E1%BA%BFn-%C4%91%E1%BB%95i-d%E1%BB%AF-li%E1%BB%87u-ki%E1%BB%83u-h%C3%ACnh-%E1%BA%A3nh"><span class="header-section-number">2.2.2</span> Sử dụng mảng nhiều chiều để biến đổi dữ liệu kiểu hình ảnh</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#list"><span class="header-section-number">2.3</span> List</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#kh%E1%BB%9Fi-t%E1%BA%A1o-list-v%C3%A0-ch%E1%BB%89-s%E1%BB%91-c%E1%BB%A7a-list."><span class="header-section-number">2.3.1</span> Khởi tạo \(list\) và chỉ số của \(list\).</a></li>
<li><a class="nav-link" href="#s%E1%BB%AD-d%E1%BB%A5ng-list-v%E1%BB%9Bi-h%C3%A0m-s%E1%BB%91"><span class="header-section-number">2.3.2</span> Sử dụng \(list\) với hàm số</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#c%C3%A1c-h%C3%A0m-h%E1%BB%8D-apply"><span class="header-section-number">2.4</span> Các hàm họ apply()</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#h%C3%A0m-apply"><span class="header-section-number">2.4.1</span> Hàm apply()</a></li>
<li><a class="nav-link" href="#h%C3%A0m-lapply-v%C3%A0-sapply."><span class="header-section-number">2.4.2</span> Hàm lapply() và sapply().</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#ph%E1%BB%A5-l%E1%BB%A5c-1"><span class="header-section-number">2.5</span> Phụ lục</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#ki%E1%BA%BFn-th%E1%BB%A9c-n%C3%A2ng-cao-li%C3%AAn-quan-%C4%91%E1%BA%BFn-ma-tr%E1%BA%ADn"><span class="header-section-number">2.5.1</span> Kiến thức nâng cao liên quan đến ma trận</a></li>
<li><a class="nav-link" href="#c%C3%A1c-gi%C3%A1-tr%E1%BB%8B-%C4%91%E1%BA%B7c-tr%C6%B0ng-c%E1%BB%A7a-m%E1%BB%99t-d%C3%B2ng-ti%E1%BB%81n-t%C6%B0%C6%A1ng-lai"><span class="header-section-number">2.5.2</span> Các giá trị đặc trưng của một dòng tiền tương lai</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/dgrtwo/tidy-text-mining/blob/master/07-lap-trinh-co-ban-voi-R.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/dgrtwo/tidy-text-mining/edit/master/07-lap-trinh-co-ban-voi-R.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong></strong>" was written by . </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
