<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chương 10 Mô hình tuyến tính tổng quát. | index</title>
<meta name="generator" content="bookdown 0.37 with bs4_book()">
<meta property="og:title" content="Chương 10 Mô hình tuyến tính tổng quát. | index">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chương 10 Mô hình tuyến tính tổng quát. | index">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/Roboto-0.4.2/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.4.0/transition.js"></script><script src="libs/bs3compat-0.4.0/tabs.js"></script><script src="libs/bs3compat-0.4.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.1/htmlwidgets.js"></script><script src="libs/d3-bundle-5.16.0/d3-bundle.min.js"></script><script src="libs/d3-lasso-0.0.5/d3-lasso.min.js"></script><script src="libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js"></script><script src="libs/flatbush-4.0.0/flatbush.min.js"></script><link href="libs/ggiraphjs-0.4.6/ggiraphjs.min.css" rel="stylesheet">
<script src="libs/ggiraphjs-0.4.6/ggiraphjs.min.js"></script><script src="libs/girafe-binding-0.8.8/girafe.js"></script><script src="libs/plotly-binding-4.10.1/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<meta name="description" content="Mô hình tuyến tính tổng quát, Generalized Linear Model hay viết tắt là GLM, được sử dụng rộng rãi trong các doanh nghiệp, các cơ quan tổ chức hoạt động trong lĩnh vực tài chính, ngân hàng, và bảo...">
<meta property="og:description" content="Mô hình tuyến tính tổng quát, Generalized Linear Model hay viết tắt là GLM, được sử dụng rộng rãi trong các doanh nghiệp, các cơ quan tổ chức hoạt động trong lĩnh vực tài chính, ngân hàng, và bảo...">
<meta name="twitter:description" content="Mô hình tuyến tính tổng quát, Generalized Linear Model hay viết tắt là GLM, được sử dụng rộng rãi trong các doanh nghiệp, các cơ quan tổ chức hoạt động trong lĩnh vực tài chính, ngân hàng, và bảo...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title=""></a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Kiến thức R cơ bản</a></li>
<li><a class="" href="ma-tr%E1%BA%ADn-m%E1%BA%A3ng-nhi%E1%BB%81u-chi%E1%BB%81u-v%C3%A0-list.html"><span class="header-section-number">2</span> Ma trận, mảng nhiều chiều và \(list\)</a></li>
<li><a class="" href="ph%C3%A2n-t%C3%ADch-d%E1%BB%AF-li%E1%BB%87u-b%E1%BA%B1ng-r.html"><span class="header-section-number">3</span> Phân tích dữ liệu bằng R</a></li>
<li><a class="" href="nh%E1%BA%ADp-d%E1%BB%AF-li%E1%BB%87u-t%E1%BB%AB-c%C3%A1c-ngu%E1%BB%93n-kh%C3%A1c-nhau-v%C3%A0o-r.html"><span class="header-section-number">4</span> Nhập dữ liệu từ các nguồn khác nhau vào R</a></li>
<li><a class="" href="ti%E1%BB%81n-x%E1%BB%AD-l%C3%BD-d%E1%BB%AF-li%E1%BB%87u.html"><span class="header-section-number">5</span> Tiền xử lý dữ liệu</a></li>
<li><a class="" href="bi%E1%BA%BFn-%C4%91%E1%BB%95i-d%E1%BB%AF-li%E1%BB%87u-b%E1%BA%B1ng-th%C6%B0-vi%E1%BB%87n-dplyr.html"><span class="header-section-number">6</span> Biến đổi dữ liệu bằng thư viện \(dplyr\)</a></li>
<li><a class="" href="tr%E1%BB%B1c-quan-h%C3%B3a-d%E1%BB%AF-li%E1%BB%87u.html"><span class="header-section-number">7</span> Trực quan hóa dữ liệu</a></li>
<li><a class="" href="tr%E1%BB%B1c-quan-h%C3%B3a-d%E1%BB%AF-li%E1%BB%87u-1.html"><span class="header-section-number">8</span> Trực quan hóa dữ liệu</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-h%E1%BB%93i-quy-tuy%E1%BA%BFn-t%C3%ADnh.html"><span class="header-section-number">9</span> Mô hình hồi quy tuyến tính</a></li>
<li><a class="active" href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html"><span class="header-section-number">10</span> Mô hình tuyến tính tổng quát.</a></li>
<li><a class="" href="reference.html"><span class="header-section-number">11</span> REFERENCE</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-d%E1%BA%A1ng-c%C3%A2y.html"><span class="header-section-number">12</span> Mô hình dạng cây</a></li>
<li><a class="" href="m%C3%B4-h%C3%ACnh-m%E1%BA%A1ng-neural-network.html"><span class="header-section-number">13</span> Mô hình mạng neural network</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/dgrtwo/tidy-text-mining">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="mô-hình-tuyến-tính-tổng-quát." class="section level1" number="10">
<h1>
<span class="header-section-number">Chương 10</span> Mô hình tuyến tính tổng quát.<a class="anchor" aria-label="anchor" href="#m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t."><i class="fas fa-link"></i></a>
</h1>
<p>Mô hình tuyến tính tổng quát, Generalized Linear Model hay viết tắt là GLM, được sử dụng rộng rãi trong các doanh nghiệp, các cơ quan tổ chức hoạt động trong lĩnh vực tài chính, ngân hàng, và bảo hiểm. Các chuyên gia quản trị rủi ro trong các ngân hàng sử dụng GLM để chấm điểm tín dụng khách hàng và quyết định phê duyệt tín dụng. Các chuyên gia tính toán thường xuyên sử dụng mô hình GLM để xác định phí thuần của các sản phẩm bảo hiểm, để xác định dự phòng nghiệp vụ, hoặc để phân loại rủi ro mà công ty phải đối mặt. Khái niệm GLM lần đầu tiên được sử dụng trong nghiên cứu của Nelder và Wedderburn (1972) và từ đó đến nay đã có nhiều sách tham khảo tin cậy cho mô hình này như Alan Agresti (2015) hay Annette J. Dobson and Adrian G. Barnett (2018). Đa số các tài liệu tham khảo giới thiệu GLM dưới góc độ toán học và mang nhiều tính lý thuyết. Chương sách này sẽ cố gắng giải thích và tiếp cận GLM từ một góc nhìn mang tính thực hành nhiều hơn. Chúng tôi sẽ không quá đi sâu vào các khía cạnh như giả thiết hay phương pháp ước lượng của mô hình GLM, mà sẽ tập trung vào hướng dẫn bạn đọc ứng dụng GLM trên nhiều kiểu dữ liệu nhất có thể.</p>
<p>Mô hình tuyến tính tổng quát được phát biểu dưới dạng công thức như sau:
<span class="math display" id="eq:glm1">\[\begin{align}
&amp; Y \sim  \mathcal{F}_{\boldsymbol{\theta}} \\
&amp; \mathbb{E}(Y|\textbf{X} = \textbf{x}_i) = \mu_i \\
&amp; g(\mu_i) = \beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p} \\
&amp; \mu_i = g^{-1}\left(\beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p} \right)
\tag{10.1}
\end{align}\]</span>
với <span class="math inline">\(Y\)</span> là biến mục tiêu, <span class="math inline">\(\mathcal{F}_{\boldsymbol{\theta}}\)</span> là một phân phối xác suất có tham số là một véc-tơ <span class="math inline">\(\boldsymbol{\theta}\)</span>. Giá trị trung bình của biến mục tiêu <span class="math inline">\(Y\)</span> phụ thuộc vào giá trị của (các) biến độc lập như sau: với điều kiện véc-tơ biến độc lập <span class="math inline">\(\textbf{X} = (X_1, X_2, \cdots, X_p)\)</span> nhận giá trị <span class="math inline">\(\textbf{x_i} = (x_{i,1}, x_{i,2}, \cdots, x_{i,p})\)</span>, giá trị trung bình của biến phụ thuộc với điều kiện <span class="math inline">\(\textbf{X} = x_i\)</span>, ký hiệu <span class="math inline">\(Y|\textbf{X} = x_i\)</span> hoặc ngắn gọn hơn là <span class="math inline">\(Y_i\)</span>, được xác định bằng giá trị một hàm số ngược của một hàm số thực <span class="math inline">\(g\)</span>, ký hiệu là hàm <span class="math inline">\(g^{-1}\)</span>, tính tại một tổ hợp tuyến tính của các giá trị <span class="math inline">\((x_{i,1}, x_{i,2}, \cdots, x_{i,p})\)</span>.</p>
<p>Thay vì cố gắng hiểu các khái niệm toán học ở trên, chúng ta hãy thử áp dụng mô hình kể trên trong một trường hợp cụ thể. Chúng ta sẽ xây dựng một mô hình tuyến tính tổng quát mà trong đó biến mục tiêu <span class="math inline">\(Y\)</span> cho biết người mua bảo hiểm xe ô tô có hay không lựa chọn đầy đủ các quyền lợi bảo hiểm khi ký hợp đồng mua bảo hiểm trách nhiệm dân sự. Dữ liệu được sử dụng có tên là <span class="math inline">\(MotoInsurance.csv\)</span>. Dữ liệu có 6 biến độc lập là:</p>
<ul>
<li><ol style="list-style-type: decimal">
<li>Độ tuổi của người lái xe, biến <span class="math inline">\(age\)</span>, nhận giá trị là các số nguyên dương từ 15 đến 92 tuổi.</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>Kinh nghiệm lái xe, biến <span class="math inline">\(seniority\)</span>, cho biết số năm kinh nghiệm lái xe, giá trị là các số nguyên từ 2 đến 40 năm.</li>
</ol></li>
<li><ol start="3" style="list-style-type: decimal">
<li>Giới tính của người lái xe, biến <span class="math inline">\(sex\)</span>, nhận giá trị “M” nếu người lái xe là nam giới và “F” nếu người lái xe là nữ giới.</li>
</ol></li>
<li><ol start="4" style="list-style-type: decimal">
<li>Nơi xe được đăng ký, biến <span class="math inline">\(urban\)</span>, nhận giá trị là 1 nếu xe được đăng ký tại khu vực thành phố và nhận giá trị 0 trong các trường hợp còn lại.</li>
</ol></li>
<li><ol start="5" style="list-style-type: decimal">
<li>Loại hình đăng ký xe, biến <span class="math inline">\(private\)</span>, nhận giá trị là 1 nếu xe mua bảo hiểm là xe đăng ký theo cá nhân và nhận giá trị 0 trong các trường hợp còn lại.</li>
</ol></li>
<li><ol start="6" style="list-style-type: decimal">
<li>Tình trạng hôn nhân của người lái xe, biến <span class="math inline">\(marital\)</span>, nhận giá trị “C” nếu đã kết hôn, “S” tương ứng với chưa kết hôn, và “O” tương ứng với đã ly dị.</li>
</ol></li>
</ul>
<p>Biến mục tiêu hay biến phụ thuộc là biến <span class="math inline">\(Y\)</span> nhận một trong hai giá trị, “Yes” nếu người mua bảo hiểm trách nhiệm dân sự đồng ý lựa thêm quyền lợi bảo hiểm bổ sung và “No” nếu người mua bảo hiểm trách nhiệm dân sự không lựa chọn mua quyền lợi bổ sung. Để mô hình ở dạng đơn giản nhất có thể, chúng tôi lựa chọn hai biến độc lập để xây dựng mô hình là biến <span class="math inline">\(age\)</span> và biến <span class="math inline">\(sex\)</span>. Chúng ta sẽ sử dụng biến <span class="math inline">\(age\)</span> như một biến kiểu số, trong khi biến <span class="math inline">\(sex\)</span> là một biến kiểu phân loại/rời rạc nhận một trong hai giá trị là “M” tương ứng với nam giới và “F” tương ứng với nữ giới.</p>
<p>Đoạn lệnh R dưới đây được sử dụng để lấy dữ liệu và phân tích nhanh ảnh hưởng của các biến <span class="math inline">\(age\)</span> và <span class="math inline">\(sex\)</span> lên quyết định mua bảo hiểm bổ sung của người sở hữu xe ô tô.</p>
<div class="sourceCode" id="cb646"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD/Dataset/MotoInsurance.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Đổi các biến Y và sex sang kiểu factor</span></span>
<span><span class="va">dat</span><span class="op">$</span><span class="va">Y</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">Y</span><span class="op">)</span></span>
<span><span class="va">dat</span><span class="op">$</span><span class="va">sex</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">sex</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Thực hiện các phân tích khai phá</span></span>
<span><span class="va">p1</span><span class="op">&lt;-</span><span class="va">dat</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">Y</span>, y <span class="op">=</span> <span class="va">age</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Mối liên hệ giữa biến age và biến Y"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p2</span><span class="op">&lt;-</span><span class="va">dat</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">sex</span>, fill <span class="op">=</span> <span class="va">Y</span><span class="op">)</span>,col <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Mối liên hệ giữa biến sex và biến Y"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"white"</span>,<span class="st">"grey"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/gridExtra/man/arrangeGrob.html">grid.arrange</a></span><span class="op">(</span><span class="va">p1</span>,<span class="va">p2</span>, ncol <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="10-mo-hinh-tuyen-tinh-tong-quat_files/figure-html/unnamed-chunk-3-1.png" width="1152" style="display: block; margin: auto;"></div>
<p>Bạn đọc có thể thấy rằng: đồ thị bên trái cho thấy những người trẻ tuổi hơn có xu hướng đồng ý mua bảo hiểm bổ sung hơn những người nhiều tuổi; đồ thị bên phải cho thấy nữ giới có xu hướng mua bảo hiểm bổ sung cao hơn so với nam giới.</p>
<p>Chúng ta sẽ xây dựng một mô hình tuyến tính tổng quát để xác nhận lại các phân tích ở trên và lượng hóa được ảnh hưởng của các biến <span class="math inline">\(age\)</span> và <span class="math inline">\(sex\)</span> lên quyết định mua bảo hiểm bổ sung. Hàm số dùng để xây dựng và ước lượng mô hình tuyến tính tổng quát trong R là hàm <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> của thư viện <span class="math inline">\(stat\)</span>:</p>
<div class="sourceCode" id="cb647"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Biến Y có phân phối nhị thức</span></span>
<span><span class="co"># Hàm g là hàm probit</span></span>
<span><span class="va">glm1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span>, data<span class="op">=</span><span class="va">dat</span>, </span>
<span>          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"probit"</span><span class="op">)</span><span class="op">)</span> <span class="co"># khai báo hàm g</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm1</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Y ~ age + sex, family = binomial(link = "probit"), 
##     data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4495  -0.9278  -0.7382   1.2584   2.0391  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.678644   0.079138   8.575   &lt;2e-16 ***
## age         -0.016257   0.001619 -10.041   &lt;2e-16 ***
## sexM        -0.446783   0.047421  -9.422   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 5163.3  on 3999  degrees of freedom
## Residual deviance: 4933.9  on 3997  degrees of freedom
## AIC: 4939.9
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Chúng ta có thể thấy rằng các hệ số của biến <span class="math inline">\(age\)</span> và <span class="math inline">\(sex\)</span> đều có ý nghĩa thống kê khi các giá trị <span class="math inline">\(p-value\)</span> đều rất nhỏ. Đúng như chúng nhận định từ phần phân tích khai phá, hệ số tuyến tính của biến <span class="math inline">\(age\)</span> là số âm, bằng -0.016, cho biết người trẻ tuổi hơn có khả năng đồng ý mua bảo hiểm bổ sung cao hơn. Hệ số ứng với biến giới tính nam là số âm, bằng -0.447, điều này cho biết khả năng nam giới đồng ý mua bảo hiểm bổ sung là thấp hơn so với nữ giới.</p>
<p>Chúng ta có thể viết các thành phần của mô hình tuyến tính tổng quát đã xây dựng ở trên như sau</p>
<p><span class="math display" id="eq:glm2">\[\begin{align}
&amp; Y \sim  \mathcal{B}(\rho) \\
&amp; \mathbb{E}(Y_i) = \mathbb{E}\left(Y|(age_i, sex_i)\right) = \rho_i \\
&amp; \Phi^{-1}\left(\rho_i\right) = 0.678 - 0.016 \times age_i - 0.447 \times sex_i \\
&amp; \rho_i = \Phi\left(0.678 - 0.016 \times age_i - 0.447 \times sex_i\right)
\tag{10.2}
\end{align}\]</span>
trong đó <span class="math inline">\(\rho_i\)</span> là xác suất hay khả năng người <span class="math inline">\(i\)</span> mua đầy đủ các quyền lợi của bảo hiểm sau khi đã mua bảo hiểm trách nhiệm dân sự. Hàm <span class="math inline">\(\Phi\)</span> là hàm phân phối xác suất của biến ngẫu nhiên phân phối chuẩn có trung bình 0 va phương sai bằng 1. Đây là hàm số mà chúng ta lựa chọn để liên kết giữa xác suất mua bảo hiểm bổ sung đến tổ hợp tuyến tính của các biến độc lập.</p>
<p>Từ kết quả của mô hình, chúng ta có thể kết luận rằng khả năng mua bảo hiểm bổ sung phụ thuộc một cách có ý nghĩa thống kê biến độ tuổi (<span class="math inline">\(age\)</span>) và giới tính (<span class="math inline">\(sex\)</span>) của người tham gia bảo hiểm trách nhiệm dân sự bắt buộc. Sự phụ thuộc này cụ thể như sau:</p>
<ol style="list-style-type: decimal">
<li><p>Xác suất mà một người mua đầy đủ các quyền lợi bảo hiểm sau khi mua bảo hiểm bắt buộc sẽ GIẢM nếu tuổi của người tham gia bảo hiểm TĂNG, điều này có nghĩa là những người trẻ tuổi hơn thường có nhu cầu mua đầy đủ các quyền lợi bảo hiểm hơn những người lớn tuổi.</p></li>
<li><p>Nam giới ít có khả năng mua đầy đủ quyền lợi bảo hiểm như nữ giới.</p></li>
</ol>
<p>Mối liên hệ giữa xác suất mua bảo hiểm đầy đủ và các thuộc tính của người được quan sát được mô tả một cách định lượng thông qua phương trình
<span class="math display" id="eq:glm3">\[\begin{align}
\rho_i = \Phi\left(0.678 - 0.016 \times age_i - 0.447 \times sex_i\right)
\tag{10.3}
\end{align}\]</span>
trong đó
<span class="math inline">\(age_i\)</span> là tuổi của người tham gia bảo hiểm; <span class="math inline">\(sex_i\)</span> nhận giá trị bằng 1 nếu người đó là nam giới và 0 nếu người đó là nữ giới; và <span class="math inline">\(\Phi\)</span> là hàm phân phối xác suất của biến ngẫu nhiên phân phối chuẩn <span class="math inline">\(\mathcal{N}(0,1)\)</span>; miền giá trị của hàm số này đảm bảo cho giá trị xác suất <span class="math inline">\(\rho_i\)</span> được tính ra nằm trong khoảng (0,1).</p>
<p>Bạn đọc có thể nhận thấy được sự khác biệt giữa mô hình tuyến tính tổng quát ở trên với mô hình tuyến tính thông thường ở hai điểm:</p>
<ul>
<li><ol style="list-style-type: decimal">
<li>Phân phối xác suất của biến mục tiêu <span class="math inline">\(Y\)</span> là phân phối nhị thức chứ không phải là phân phối chuẩn.</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>Mối liên kết giữa giá trị trung bình của biến mục tiêu <span class="math inline">\(Y\)</span> và tổ hợp tuyến tính của các biến độc lập được thể hiện thông qua một hàm số, trong trường hợp này là hàm <span class="math inline">\(\Phi\)</span>. Trong mô hình tuyến tính thông thường, giá trị trunh bình của biến mục tiêu được mô tả trực tiếp bằng tổ hợp tuyến tính của các biến độc lập.</li>
</ol></li>
</ul>
<p>Hải điểm nêu trên cũng chính là hai cải tiến quan trọng của mô hình tuyến tính tổng so với mô hình hồi quy tuyến tính thông thường. Việc tổng quát hóa phân phối của biến phụ thuộc và thiết lập một hàm liên kết giữa giá trị trung bình của biến phụ thuộc và với các biến độc lập giúp cho mô hình tuyến tính tổng quát linh hoạt hơn rất nhiều khi làm việc với các dữ liệu cụ thể và vẫn giữ được khả năng suy diễn giống như mô hình hồi quy tuyến tính thông thường. Trong phần tiếp theo của chương chúng ta sẽ thảo luận kỹ hơn về các vấn đề này.</p>
<div id="các-nhược-điểm-của-mô-hình-hồi-quy-tuyến-tính." class="section level2" number="10.1">
<h2>
<span class="header-section-number">10.1</span> Các nhược điểm của mô hình hồi quy tuyến tính.<a class="anchor" aria-label="anchor" href="#c%C3%A1c-nh%C6%B0%E1%BB%A3c-%C4%91i%E1%BB%83m-c%E1%BB%A7a-m%C3%B4-h%C3%ACnh-h%E1%BB%93i-quy-tuy%E1%BA%BFn-t%C3%ADnh."><i class="fas fa-link"></i></a>
</h2>
<p>Mô hình hồi quy tuyến tính là nền tảng quan trọng cho hầu hết các mô hình học máy và các mô hình trí tuệ nhân tạo hiện tại. Trước khi những mô hình học máy được nghiên cứu và phát triển mạnh mẽ như hiện nay, những người xây dựng mô hình luôn gặp khó khăn khi sử dụng mô hình hồi quy tuyến tính trong nhiều hoàn cảnh. Nguyên nhân là do giả thiết về phân phối xác suất của biến mục tiêu và miền giá trị trung bình của biến mục tiêu của mô hình hồi quy tuyến tính thông thường là không phù hợp với đa số dữ liệu thực tế.</p>
<p>Thật vậy, mô hình hồi quy tuyến tính được thảo luận trong phần trước của cuốn sách có thể được tóm tắt như sau: người xây dựng mô hình cố gắng nghiên cứu mối quan hệ giữa một biến mục tiêu <span class="math inline">\(Y\)</span> với véc-tơ biến độc lập <span class="math inline">\(\textbf{X} = (X_1, X_2, \cdots, X_p)\)</span> bằng cách cho rằng mối liên hệ giữa <span class="math inline">\(Y\)</span> và <span class="math inline">\(\textbf{X}\)</span> là một hàm tuyến tính. Mối liên hệ đó không đồng nhất nên sai số sẽ tồn tại và những người xây dựng mô hình cho rằng sai số có phân phối chuẩn với trung bình bằng 0 và độ lệch chuẩn là một hằng số <span class="math inline">\(\sigma &gt; 0\)</span>. Chúng ta biểu diễn mô hình tuyến tính thông thương như sau</p>
<p><span class="math display" id="eq:glm4">\[\begin{align}
&amp; Y = \beta_0 + \beta_1 \cdot X_1 + \beta_2 \cdot X_2 + \cdots + \beta_p \cdot X_p + \epsilon \\
&amp; \epsilon \sim \mathcal{N}(0, \sigma^2)
\tag{10.4}
\end{align}\]</span></p>
<p>Bạn đọc có thể thấy rằng trong mô hình hồi quy tuyến tính, biến phụ thuộc <span class="math inline">\(Y\)</span> là biến ngẫu nhiên có phân phối chuẩn có phương sai là <span class="math inline">\(\sigma^2\)</span> và giá trị trung bình phụ thuộc vào véc-tơ biến độc lập <span class="math inline">\(\textbf{X}_i\)</span>. Với điều kiện biến độc lập nhận giá trị là <span class="math inline">\(\textbf{x}_i = (x_{i,1}, x_{i,2}, \cdots, x_{i,p})\)</span>; chúng ta có mô hình hồi quy tuyến tính như sau:</p>
<p><span class="math display" id="eq:glm5">\[\begin{align}
&amp; Y_i \sim  \mathcal{N}(\mu_i, \sigma^2) \\
&amp; \mu_i = \beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p}
\tag{10.5}
\end{align}\]</span></p>
<p>Ngoài giả thiết về phân phối chuẩn của <span class="math inline">\(Y\)</span>, mô hình hồi quy tuyến tính thông thường còn cho rằng giá trị trung bình của biến ngẫu nhiên <span class="math inline">\(Y\)</span> với điều kiện các biến độc lập nhận giá trị <span class="math inline">\(\textbf{x}_i\)</span>, ký hiệu <span class="math inline">\(\mu_i\)</span>, là một tổ hợp tuyến tính của các biến độc lập. Khi các biến độc lập nhận các giá trị bất kỳ, miền giá trị của <span class="math inline">\(\mu_i\)</span> sẽ là (toàn bộ) tập các số thực <span class="math inline">\(\mathbb{R}\)</span>.</p>
<p>Câu hỏi đặt ra là: làm như thế nào để áp dụng mô hình hồi quy tuyến tính trong các trường hợp như sau?</p>
<ol style="list-style-type: decimal">
<li><p>Biến mục tiêu <span class="math inline">\(Y\)</span> chỉ nhận hai giá trị là 0 hoặc 1. Đây là trường hợp rất thường gặp phải trong nhiều lĩnh vực khi thực hiện phân tích dữ liệu. Có thể kể đến như: khi biến <span class="math inline">\(Y\)</span> đại diện cho sự kiện một người có hay không tham gia bảo hiểm xã hội; một người có hay không thực hiện rút bảo hiểm xã hội một lần trong thời gian một khoảng thời gian; một khách hàng có hay không gửi yêu cầu thanh toán bảo hiểm; hay tương tự như ví dụ trong phần đầu của cuốn sách, một khách hàng đã mua bảo hiểm bắt buộc có hay không mua thêm các quyền lợi bảo hiểm bổ sung. Ngoài lĩnh vực bảo hiểm, biến mục tiêu <span class="math inline">\(Y\)</span> chỉ nhận giá trị 0 hoặc 1 còn xuất hiện trong lĩnh vực ngân hàng tài chính: biến mục tiêu cho biết một giao dịch trực tuyến có phải là một giao dịch gian lận hay không; một khách hàng có hay không tiếp nhận sản phẩm dịch vụ tài chính với mới; một khách hàng có hay không hoàn trả khoản nợ thẻ tín dụng trong thời gian tới,… Trong tất cả các trường hợp kể trên không thể giả thiết phân phối xác suất của biến mục tiêu là phân phối chuẩn. Hơn thế nữa, giá trị trung bình của biến mục tiêu sẽ luôn nằm trong khoảng 0 đến 1, chứ không phải toàn bộ trục số thực. Nếu sử dụng một tổ hợp tuyến tính của các biến độc lập để tính toán giá trị trung bình của biến mục tiêu, chúng ta sẽ có thể gặp các giá trị nhỏ hơn 0 hoặc các giá trị lớn hơn 1.</p></li>
<li><p>Biến mục tiêu <span class="math inline">\(Y\)</span> là biến dạng đếm. Chẳng hạn như <span class="math inline">\(Y\)</span> cho biết một người tham gia bảo hiểm xã hội gửi yêu cầu bồi thường bao nhiêu lần trong một năm; biến <span class="math inline">\(Y\)</span> cho biết một khách hàng mua bảo hiểm xe ô tô gây ra bao nhiêu tai nạn trong thời gian được bảo hiểm,… Trong trường hợp này, <span class="math inline">\(Y\)</span> sẽ nhận giá trị kiểu số đếm: <span class="math inline">\(0, 1, 2, \cdots\)</span> tương ứng với số lần khách hàng gửi yêu cầu bảo hiểm. Không thể sử dụng mô hình hồi quy tuyến tính thông thường do biến <span class="math inline">\(Y\)</span> là biến rời rạc đồng thời giá trị trung bình của <span class="math inline">\(Y\)</span> là một số lớn hơn 0.</p></li>
<li><p>Ngay cả khi trong các trường hợp biến phụ thuộc <span class="math inline">\(Y\)</span> là biến liên tục, sử dụng mô hình tuyến tính thông thường cũng sẽ gặp phải vấn đề. Chẳng hạn như khi <span class="math inline">\(Y\)</span> là số tiền khách hàng yêu cầu bồi thường cho xe ô tô trong trường hợp xảy ra tai nạn. Biến <span class="math inline">\(Y\)</span> chỉ nhận giá trị là số dương và thường có phân phối xác suất lệch phải với đuôi lớn. Sử dụng giả thiết phân phối chuẩn cho biến <span class="math inline">\(Y\)</span> sẽ làm cho mô hình không đánh giá đúng khả mức độ nghiêm trọng của yêu cầu bồi thường do phân phối chuẩn không có khả năng mô tả các rủi ro có đuôi lớn. Đồng thời, giá trị trung bình của số tiền yêu cầu bồi thường luôn là số dương, do đó cũng không thể sử dụng tổ hợp tuyến tính của các biến độc lập để trực tiếp mô tả giá trị trung bình của <span class="math inline">\(Y\)</span>.</p></li>
</ol>
<p>Có thể tổng kết rằng hai vấn đề thường gặp phải khi sử dụng mô hình hồi quy tuyến tính thông thường trên dữ liệu thực tế là</p>
<ul>
<li><p>Thứ nhất: sự không phù hợp của giả thiết phân phối chuẩn đối với biến mục tiêu <span class="math inline">\(Y\)</span>; và</p></li>
<li><p>Thứ hai: miền giá trị trung bình của biến mục tiêu <span class="math inline">\(Y\)</span> không phù hợp với miền giá trị của tổ hợp tuyến tính của biến độc lập. Giá trị <span class="math inline">\(\textbf{x}_i^{'} \boldsymbol{\beta} = \beta_0 + \beta_1 \ x_{i,1} + \beta_2 \ x_{i,2} + \cdots + \beta_p \ x_{i,p}\)</span> có thể nhận bất kỳ giá trị nào trong <span class="math inline">\(\mathbb{R}\)</span>, trong khi giá trị trung bình của biến mục tiêu <span class="math inline">\(Y\)</span> trong các dữ liệu thực tế lại thường chỉ là một tập con của <span class="math inline">\(\mathbb{R}\)</span>.</p></li>
</ul>
<p>Mô hình tuyến tính tổng quát được xây dựng trên cơ sở của mô hình hồi quy tuyến tính thông thường với mục đích khắc phục hai nhược điểm kể trên.
- Trước hết, mô hình tuyến tính tổng quát giả thiết một phân phối phù hợp cho biến phụ thuộc <span class="math inline">\(Y\)</span>, tùy vào dữ liệu sử dụng để phân tích, tạm gọi là phân phối <span class="math inline">\(F\)</span> với tham số <span class="math inline">\(\boldsymbol{\theta}\)</span>, ký hiệu là <span class="math inline">\(F_\boldsymbol{\theta}\)</span>.
- Tiếp theo, để đảm bảo miền giá trị của giá trị trung bình của <span class="math inline">\(Y\)</span> với điều kiện các biến độc lập bằng <span class="math inline">\(\textbf{x}_i\)</span>, <span class="math inline">\(\mu_i = E(Y|\textbf{X} = \textbf{x}_i)\)</span>, phù hợp với miền giá trị của <span class="math inline">\(\textbf{x}_i^{'} \boldsymbol{\beta}\)</span>, mô hình tuyển tính tổng quát sử dụng một hàm số đơn điệu <span class="math inline">\(g\)</span>, được gọi là hàm liên kết, để biến đổi miền giá trị của <span class="math inline">\(\mu_i\)</span>. Chúng ta phát biểu mô hình tuyến tính tổng quát như sau
<span class="math display" id="eq:glm6">\[\begin{align}
&amp; Y \sim  F_\theta \\
&amp; \mathbb{E}(Y|\textbf{X} = \textbf{x}_i) = \mu_i \\
&amp; g(\mu_i) = \beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p}
\tag{10.6}
\end{align}\]</span></p>
<p>Trước hết, có thể thấy rằng mô hình hồi quy tuyến tính thông thường là trường hợp đặc biệt của mô hình tuyến tính tổng quát khi tham số <span class="math inline">\(\boldsymbol{\theta}\)</span> là <span class="math inline">\(\sigma^2\)</span>; phân phối <span class="math inline">\(F\)</span> là phân phối chuẩn; và hàm <span class="math inline">\(g\)</span> là hàm số đồng nhất <span class="math inline">\(g(x) = x\)</span>.</p>
<p>Giả thiết đơn điệu của hàm liên kết <span class="math inline">\(g\)</span> đảm bảo sự tồn tại của hàm số ngược <span class="math inline">\(g^{-1}\)</span>. Mối liên hệ của <span class="math inline">\(\mu_i\)</span> và <span class="math inline">\(\textbf{x}_i^{'} \boldsymbol{\beta}\)</span> có thể được viết lại dưới dạng hàm ngược của hàm liên kết như sau
<span class="math display" id="eq:glm7">\[\begin{align}
\mu_i = g^{-1}(\textbf{x}_i^{'} \boldsymbol{\beta})
\tag{10.7}
\end{align}\]</span></p>
<p>Quay trở lại ví dụ ở phần trước của chương sách, chúng ta phân tích về tác động của độ tuổi và giới tính lên quyết định có tham gia quyền lợi bảo hiểm bổ sung hay không. Mô hình tuyến tính tổng quát được xây dựng như sau:</p>
<p><span class="math display">\[\begin{align}
&amp; Y \sim  \mathcal{B}(p) \\
&amp; \mathbb{E}(Y|age_i, sex_i) = p_i \\
&amp; \Phi^{-1}(p_i) = 0.678 - 0.016 \times age_i - 0.446 \times sex_i
\end{align}\]</span></p>
<p>Phân phối xác suất của biến <span class="math inline">\(Y\)</span> là phân phối nhị thức do <span class="math inline">\(Y\)</span> chỉ có thể nhận là 0 hoặc 1. Đồng thời, giá trị trung bình của <span class="math inline">\(Y\)</span> nằm trong khoảng <span class="math inline">\((0,1)\)</span> chúng ta có thể chọn hàm liên kết <span class="math inline">\(g\)</span> là hàm <span class="math inline">\(\Phi^{-1}\)</span>. Đây là hàm ngược của hàm phân phối xác suất của biến ngẫu nhiên phân phối chuẩn <span class="math inline">\(\mathcal{N}(0,1)\)</span> nên thỏa mãn các điều kiện của một hàm liên kết: hàm đơn điệu tăng; có miền xác định là <span class="math inline">\((0,1)\)</span>; và miền giá trị là tập số thực <span class="math inline">\(\mathbb{R}\)</span>. Nếu không lựa chọn <span class="math inline">\(\Phi^{-1}\)</span>, mọi hàm số đơn điệu, có miền xác định là khoảng <span class="math inline">\((0,1)\)</span>, và miền giá trị là tập số thực <span class="math inline">\(\mathbb{R}\)</span> đều có thể được lựa chọn làm hàm số kết nối.</p>
</div>
<div id="xây-dựng-mô-hình-tuyến-tính-tổng-quát" class="section level2" number="10.2">
<h2>
<span class="header-section-number">10.2</span> Xây dựng mô hình tuyến tính tổng quát<a class="anchor" aria-label="anchor" href="#x%C3%A2y-d%E1%BB%B1ng-m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t"><i class="fas fa-link"></i></a>
</h2>
<p>Phần tiếp theo của cuốn sách sẽ thảo luận về cách xây dựng mô hình tuyến tổng quát với các kiểu giá trị khác nhau của biến phụ thuộc <span class="math inline">\(Y\)</span>. Xin được nhắc lại rằng đây là cuốn sách dành cho cả các bạn đọc không có nền tảng toán học nâng cao. Do đó, những thảo luận phức tạp liên quan đến các giả thiết của mô hình hay phương pháp ước lượng tham số sẽ được trình bày ở phần sau của chương sách. Chúng ta sẽ hiểu về mô hình tuyến tính tổng quát thông qua việc ứng dụng mô hình cho các các dữ liệu thực tế trước khi đi sâu vào bản chất toán học của mô hình.</p>
<div id="biến-phụ-thuộc-là-biến-dạng-nhị-phân." class="section level3" number="10.2.1">
<h3>
<span class="header-section-number">10.2.1</span> Biến phụ thuộc là biến dạng nhị phân.<a class="anchor" aria-label="anchor" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-l%C3%A0-bi%E1%BA%BFn-d%E1%BA%A1ng-nh%E1%BB%8B-ph%C3%A2n."><i class="fas fa-link"></i></a>
</h3>
<p>Đây là các trường hợp mà biến phụ thuộc chỉ nhận một trong hai giá trị. Ở phần trên chúng ta đã trình bày các ví dụ cho trường hợp này: khách hàng có hay không hoàn trả nợ thẻ tín dụng, khách hàng phản hồi tích cực hay tiêu cực về sản phầm, một yêu cầu bồi thường là trục lợi hay bình thường, một giao dịch rút tiền ngân hàng có hay không phải là giao dịch gian lận, … Mặc dù đây chỉ là một trường hợp đặc biệt của biến phụ thuộc nhận giá trị rời rạc nhưng qua các ví dụ thực tế lại thấy rằng phần lớn các dữ liệu gặp phải lại có biến phụ thuộc ở dạng nhị phân. Khi <span class="math inline">\(Y\)</span> chỉ nhận hai giá trị, chúng ta sẽ luôn mã hóa giá trị của <span class="math inline">\(Y\)</span> thành hai số là 0 và 1. Một vài cuốn sách khác, hoặc trong một vài lĩnh vực nghiên cứu khác, người xây dựng mô hình có thể mã hóa <span class="math inline">\(Y\)</span> thành -1 và 1. Tuy nhiên hai cách mã hóa này chỉ khác nhau ở hình thức chứ không làm ảnh hưởng đến kết quả của mô hình.</p>
<div id="phân-phối-xác-suất-của-biến-phụ-thuộc." class="section level4" number="10.2.1.1">
<h4>
<span class="header-section-number">10.2.1.1</span> Phân phối xác suất của biến phụ thuộc.<a class="anchor" aria-label="anchor" href="#ph%C3%A2n-ph%E1%BB%91i-x%C3%A1c-su%E1%BA%A5t-c%E1%BB%A7a-bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c."><i class="fas fa-link"></i></a>
</h4>
<p>Khi biến phụ thuộc là biến dạng nhị phân, một cách tự nhiên, chúng ta sẽ sử dụng phân phối nhị thức, hay còn gọi là phân phối Bernoulli, để mô tả biến phụ thuộc. Biến ngẫu nhiên <span class="math inline">\(B\)</span> có phân phối nhị thức với tham số <span class="math inline">\(\rho\)</span>, <span class="math inline">\(0 &lt; \rho &lt; 1\)</span>, ký hiệu <span class="math inline">\(\mathcal{B}(\rho)\)</span>, là biến ngẫu nhiên chỉ nhận hai giá trị là 0 và 1 với hàm khối lượng xác suất như sau<br><span class="math display" id="eq:glm80">\[\begin{align}
\mathbb{P}(B = x) = \rho^x \times (1-\rho)^{(1-x)} \text{ với } x \in \{0;1\}
\tag{10.8}
\end{align}\]</span></p>
<p>Chúng ta có giá trị trung bình và phương sai của <span class="math inline">\(\mathcal{B}(\rho)\)</span>.
<span class="math display" id="eq:glm81">\[\begin{align}
&amp; \mathbb{E}(B) = \rho \\
&amp; \mathbb{V}(B) = \rho \ (1-\rho)
\tag{10.9}
\end{align}\]</span></p>
<p>Có thể thấy rằng phân phối nhị thức có duy nhất một tham số <span class="math inline">\(\rho\)</span> và tham số này cũng chính là giá trị trung bình của biến đó. Phương sai của <span class="math inline">\(\mathcal{B}(\rho)\)</span> nhỏ hơn giá trị trung bình.</p>
</div>
<div id="lựa-chọn-hàm-liên-kết." class="section level4" number="10.2.1.2">
<h4>
<span class="header-section-number">10.2.1.2</span> Lựa chọn hàm liên kết.<a class="anchor" aria-label="anchor" href="#l%E1%BB%B1a-ch%E1%BB%8Dn-h%C3%A0m-li%C3%AAn-k%E1%BA%BFt."><i class="fas fa-link"></i></a>
</h4>
<p>Khi biến phụ thuộc <span class="math inline">\(Y\)</span> có phân phối nhị thức, giá trị trung bình của biến phụ thuộc sẽ nằm trong khoảng <span class="math inline">\((0,1)\)</span>. Từ công thức <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:glm6">(10.6)</a>, nếu cho <span class="math inline">\(\rho_i\)</span> là giá trị trung bình của biến phụ thuộc với điều kiện các biến độc lập <span class="math inline">\(\textbf{X} = \textbf{x}_i\)</span>, ta có</p>
<p><span class="math display" id="eq:bn1">\[\begin{align}
&amp; \mathbb{E}(Y|\textbf{X} = \textbf{x}_i) = \rho_i \\
&amp; g(\rho_i) = \beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,3}
\tag{10.10}
\end{align}\]</span></p>
<p>Như vậy, mọi hàm số đơn điệu có miền xác định là khoảng <span class="math inline">\((0,1)\)</span> và miền giá trị là toàn bộ tập số thực <span class="math inline">\(\mathbb{R}\)</span> đều có thể được lựa chọn để làm hàm ngược của hàm liên kết. Làm thế nào để có được những hàm số có tính chất như vậy? Chúng ta đều biết rằng các hàm phân phối xác suất của một biến ngẫu nhiên liên tục bất kỳ là các hàm số tăng, có miền xác định là <span class="math inline">\(\mathbb{R}\)</span> và miền giá trị là khoảng <span class="math inline">\((0,1)\)</span>. Do đó, hàm số ngược của các hàm phân phối xác suất, sẽ là các hàm số tăng, có miền xác định là khoảng <span class="math inline">\((0,1)\)</span> và miền giá trị là <span class="math inline">\(\mathbb{R}\)</span>. Nói một cách khác, hàm số ngược của các hàm phân phối xác suất bất kỳ thỏa mãn đầy đủ tính chất của hàm liên kết trong trường hợp <span class="math inline">\(Y\)</span> có phân phối nhị thức.</p>
<p>Trong thực tế, việc lựa chọn hàm liên kết còn có mục tiêu là để mô hình dễ giải thích và quá trình ước lượng mô hình đơn giản nhất có thể. Các hàm phân phối xác suất thường được lựa chọn làm <span class="math inline">\(g^{-1}(.)\)</span> bao gồm có: thứ nhất là hàm phân phối của biến ngẫu nhiên logistic; thứ hai là hàm phân phối của biến ngẫu nhiên phân phối chuẩn; và thứ ba là hàm phân phối của biến ngẫu nhiên phân phối Cauchy.</p>
<ol style="list-style-type: decimal">
<li>Hàm phân phối của biến ngẫu nhiên logistic và hàm ngược được cho bởi công thức sau
<span class="math display">\[\begin{align}
&amp; \textit{Hàm phân phối xác suất: } \ g^{-1}(x) = \cfrac{1}{1 + e^{-x}} \\
&amp; \textit{Hàm ngược: } \ g(x) = ln(\cfrac{x}{1- x})
\end{align}\]</span>
</li>
</ol>
<p>Với biến phụ thuộc <span class="math inline">\(Y\)</span> là có phân phối nhị thức và hàm <span class="math inline">\(g\)</span> là hàm số ngược của hàm phân phối của biến ngẫu nhiên logistic, chúng ta có mô hình tuyến tính tổng quát như sau:</p>
<p><span class="math display" id="eq:logit1">\[\begin{align}
&amp; Y_i \sim \mathcal{B}(\rho_i) \\
&amp; \rho_i = \cfrac{1}{1 + exp(-(\beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p}))} \\
&amp; ln(\cfrac{\rho_i}{1 - \rho_i}) = \beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p}
\tag{10.11}
\end{align}\]</span></p>
<p>Đây là mô hình được biết đến rộng rãi với tên gọi là hồi quy logistic và cũng là mô hình thường được sử dụng nhất trong khi biến phụ thuộc là biến nhị phân. Mô hình có ưu điểm là sự dễ hiểu khi diễn giải kết quả:</p>
<ul>
<li><p><span class="math inline">\(\rho_i\)</span> ngoài ý nghĩa là trung bình của biến ngẫu nhiên <span class="math inline">\(Y_i\)</span> còn có ý nghĩa là xác suất xảy ra sự kiện <span class="math inline">\(Y_i = 1\)</span>.</p></li>
<li><p>Giá trị <span class="math inline">\(\cfrac{\rho_i}{1 - \rho_i}\)</span> được gọi là odds của sự kiện <span class="math inline">\(Y_i = 1\)</span>. Mối liên hệ giữa quan sát thứ <span class="math inline">\(i\)</span> của biến độc lập <span class="math inline">\(X_j\)</span> là <span class="math inline">\(x_{i,j}\)</span> và obbs của sự kiện <span class="math inline">\(Y_i = 1\)</span> có thể được diễn giải thông qua hệ số <span class="math inline">\(\beta_j\)</span>.</p></li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Hàm phân phối của biến ngẫu nhiên chuẩn <span class="math inline">\(\mathcal{N}(0,1)\)</span> và hàm ngược của hàm phân phối được cho bởi công thức sau
<span class="math display">\[\begin{align}
&amp; g^{-1}(x) = \Phi(x) \\
&amp; g(x) = \Phi^{-1}(x) \\
&amp; \Phi(x) = \cfrac{1}{\sqrt{2 \pi}} \  \int\limits_{-\infty}^x \ exp(-t^2/2)  \\
\end{align}\]</span>
</li>
</ol>
<p>Chúng ta có mô hình tuyến tính tổng quát như sau</p>
<p><span class="math display" id="eq:probit1">\[\begin{align}
&amp; Y_i \sim \mathcal{B}(\rho_i) \\
&amp; \rho_i = \Phi(\beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p}) \\
&amp; \Phi^{-1}(\rho_i) = \beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p}
\tag{10.12}
\end{align}\]</span></p>
<p>Hàm số ngược của biến ngẫu nhiên phân phối chuẩn được gọi là hàm probit do đó mô hình GLM trong trường hợp này còn được biết đến với tên gọi là mô hình probit.</p>
<ol start="3" style="list-style-type: decimal">
<li>Hàm phân phối của biến ngẫu nhiên Cauchy và hàm ngược của hàm phân phối được cho bởi công thức sau
<span class="math display" id="eq:cauchy1">\[\begin{align}
&amp; g^{-1}(x) = \cfrac{1}{2} + \cfrac{arctan(x)}{\pi} \\
&amp; g(x) = tan\left( \pi \left( x - \cfrac{1}{2} \right) \right)
\tag{10.13}
\end{align}\]</span>
</li>
</ol>
<p>Chúng ta có mô hình tuyến tính tổng quát như sau</p>
<p><span class="math display" id="eq:cauchy2">\[\begin{align}
&amp; Y_i \sim \mathcal{B}(\rho_i) \\
&amp; p_i = \cfrac{1}{2} + \cfrac{arctan(\beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p})}{\pi}  \\
&amp; tan\left( \pi \left( \rho_i - \cfrac{1}{2} \right) \right) = \beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p}
\tag{10.14}
\end{align}\]</span></p>
<p>Hàm số ngược của phân phối cauchy còn được gọi là hàm cauchit, do đó mô hình tuyến tính tổng quát trong trường hợp này còn được biết đến với tên là mô hình cauchit.</p>
<p>Hình vẽ dưới đây mô tả hình dạng của ba hàm số kết nối</p>
<div class="inline-figure"><img src="10-mo-hinh-tuyen-tinh-tong-quat_files/figure-html/unnamed-chunk-5-1.png" width="1440"></div>
<p>Mô hình tuyến tính tổng quát trong trường hợp <span class="math inline">\(Y\)</span> là biến nhị phân thường được ước lượng bằng phương pháp tối đa hóa hàm likelihood, hay gọi tắt là phương pháp MLE. Để tránh sự phức tạp không cần thiết chúng tôi sẽ trình bày phần ước lượng mô hình trong phần sau của chương sách.</p>
<p>Trong R, hàm số <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> của thư viện <span class="math inline">\(stat\)</span> được sử dụng để xây dựng mô hình tuyến tính tổng quát. Tham số <span class="math inline">\(family\)</span> trong hàm <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> dùng để khai báo phân phối xác suất cho biến phụ thuộc <span class="math inline">\(Y\)</span> và để lựa chọn hàm liên kết phù hợp. Trở lại với ví dụ khi <span class="math inline">\(Y\)</span> là biến nhị phân mô tả khách hàng có hay không lựa chọn các quyền lợi đầy đủ khi tham gia bảo hiểm bổ sung, chúng ra thực hiện xây dựng mô hình như sau</p>
<div class="sourceCode" id="cb649"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Phân phối Y là nhị thức và hàm liên kết là hàm logit</span></span>
<span><span class="va">glm.binomial.logit</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span>, data<span class="op">=</span><span class="va">dat</span>, </span>
<span>          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"logit"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Phân phối Y là nhị thức và hàm liên kết là hàm probit</span></span>
<span><span class="va">glm.binomial.probit</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span>, data<span class="op">=</span><span class="va">dat</span>, </span>
<span>          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"probit"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Phân phối Y là nhị thức và hàm liên kết là hàm cauchit</span></span>
<span><span class="va">glm.binomial.cauchy</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">sex</span>, data<span class="op">=</span><span class="va">dat</span>, </span>
<span>          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"cauchit"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>Cả ba mô hình tuyến tính tổng quát ở trên đều cho <span class="math inline">\(Y\)</span> là một biến ngẫu nhiên phân phối nhị thức, nhưng mối liên hệ giữa độ tuổi và giới tính đến giá trị trung bình của <span class="math inline">\(Y\)</span> lại được mô tả bằng các công thức khác nhau</p>
<ol style="list-style-type: decimal">
<li><p>Trong mô hình logit:
<span class="math display">\[\begin{align}
\mathbb{P}(Y_i = 1| age_i, sex_i) = \cfrac{1}{1 + exp(-(1.109 - 0.026 \times age_{i} - 0.723 \times sex_{i}))}
\end{align}\]</span></p></li>
<li><p>Trong mô hình probit
<span class="math display">\[\begin{align}
\mathbb{P}(Y_i = 1| age_i, sex_i) = \Phi\left(0.678 - 0.016 \times age_{i} - 0.446 \times sex_{i}\right)
\end{align}\]</span></p></li>
<li><p>Trong mô hình cauchit
<span class="math display">\[\begin{align}
\mathbb{P}(Y_i = 1| age_i, sex_i) = \cfrac{1}{2} + \cfrac{arctan\left(0.997 - 0.024 \times age_{i} - 0.624 \times sex_{i}\right)} {\pi}
\end{align}\]</span></p></li>
</ol>
<p>Cả ba mô hình đều cho cùng một kết quả: người có độ tuổi càng cao thì càng ít có khả năng lựa chọn quyền lợi bảo hiểm bổ sung và xác suất nam giới lựa chọn quyền lợi bảo hiểm bổ sung là ít hơn so với nữ giới. Bảng dưới đây đưa ra khả năng/xác suất chấp nhận của ba mô hình tính dựa trên hai biến độc lập là tuổi và giới tính</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:center;">
Người BH
</th>
<th style="text-align:center;">
Độ tuổi
</th>
<th style="text-align:center;">
Giới tính
</th>
<th style="text-align:center;">
Logit
</th>
<th style="text-align:center;">
Probit
</th>
<th style="text-align:center;">
Cauchit
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
Nam
</td>
<td style="text-align:center;">
0.467
</td>
<td style="text-align:center;">
0.465
</td>
<td style="text-align:center;">
0.466
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
Nam
</td>
<td style="text-align:center;">
0.403
</td>
<td style="text-align:center;">
0.402
</td>
<td style="text-align:center;">
0.394
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
Nam
</td>
<td style="text-align:center;">
0.342
</td>
<td style="text-align:center;">
0.342
</td>
<td style="text-align:center;">
0.331
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
Nam
</td>
<td style="text-align:center;">
0.286
</td>
<td style="text-align:center;">
0.285
</td>
<td style="text-align:center;">
0.280
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
Nam
</td>
<td style="text-align:center;">
0.236
</td>
<td style="text-align:center;">
0.233
</td>
<td style="text-align:center;">
0.240
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
Nữ
</td>
<td style="text-align:center;">
0.643
</td>
<td style="text-align:center;">
0.640
</td>
<td style="text-align:center;">
0.652
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
Nữ
</td>
<td style="text-align:center;">
0.582
</td>
<td style="text-align:center;">
0.578
</td>
<td style="text-align:center;">
0.586
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
Nữ
</td>
<td style="text-align:center;">
0.517
</td>
<td style="text-align:center;">
0.515
</td>
<td style="text-align:center;">
0.512
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
Nữ
</td>
<td style="text-align:center;">
0.452
</td>
<td style="text-align:center;">
0.451
</td>
<td style="text-align:center;">
0.436
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
Nữ
</td>
<td style="text-align:center;">
0.389
</td>
<td style="text-align:center;">
0.389
</td>
<td style="text-align:center;">
0.367
</td>
</tr>
</tbody>
</table></div>
<p>Có thể thấy rằng không có sự khác biệt lớn trong tính toán xác suất của <span class="math inline">\(Y\)</span> khi sử dụng hàm liên kết khác nhau. Thực tế thì việc lựa chọn hàm kết nối sẽ không ảnh hưởng lớn đến kết quả của mô hình bằng việc lựa chọn phân phối cho biến phụ thuộc hay việc lựa chọn biến độc lập để giải thích mô hình.</p>
</div>
</div>
<div id="biến-phụ-thuộc-là-biến-rời-rạc-không-có-thứ-tự." class="section level3" number="10.2.2">
<h3>
<span class="header-section-number">10.2.2</span> Biến phụ thuộc là biến rời rạc không có thứ tự.<a class="anchor" aria-label="anchor" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-l%C3%A0-bi%E1%BA%BFn-r%E1%BB%9Di-r%E1%BA%A1c-kh%C3%B4ng-c%C3%B3-th%E1%BB%A9-t%E1%BB%B1."><i class="fas fa-link"></i></a>
</h3>
<p>Biến rời rạc không có thứ tự, hay còn gọi là biến rời rạc danh nghĩa (non-ordinal variable), là biến ngẫu nhiên mà các giá trị có thể nhận không có ý nghĩa so sánh với nhau. Khi nói đến biến rời rạc không có thứ tự, chúng ta luôn hiểu rằng biến nhận từ ba giá trị trở lên bởi vì trường hợp có hai giá trị sẽ tương tự như biến có phân phối nhị phân. Một ví dụ đơn giản cho biến rời rạc không có thứ tự là màu sắc được chọn khi mua xe ô tô, hoặc loại hình bảo hiểm được lựa chọn bởi các khách hàng của một công ty bảo hiểm.</p>
<p>Giả sử biến rời rạc danh nghĩa <span class="math inline">\(Y\)</span> có thể nhận <span class="math inline">\(J\)</span> giá trị khác nhau lần lượt là <span class="math inline">\(1, 2, \cdots, J\)</span>. Với biến danh nghĩa, chúng ta không thể mô tả được mối liên hệ giữa xác suất của hai sự kiện <span class="math inline">\((Y=i)\)</span> và <span class="math inline">\((Y=j)\)</span> với <span class="math inline">\(1 \leq i &lt; j \leq J\)</span> dưới dạng tham số. Chính vì thế cấu trúc dạng tham số của mô hình tuyến tính tổng quát như phương trình <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:glm1">(10.1)</a> là không thể áp dụng được.</p>
<p>Một phương pháp tiếp cận cho trường hợp biến mục tiêu <span class="math inline">\(Y\)</span> là biến danh nghĩa là mở rộng mô hình tuyến tính tổng quát với biến nhị phân: với mỗi <span class="math inline">\(j \in {1,2,\cdots,J}\)</span></p>
<p><span class="math display" id="eq:sm">\[\begin{align}
\mathbb{P}\left(Y = j\right|\textbf{x}_i) = \cfrac{h(\beta_{j,0} + \beta_{j,1} \cdot x_{i,1} + \cdots + \beta_{j,p} \cdot x_{i,p} ) }{ \sum\limits_{j=1}^J h(\beta_{j,0} + \beta_{j,1} \cdot x_{i,1} + \cdots + \beta_{j,p} \cdot x_{i,p} ) }
\tag{10.15}
\end{align}\]</span></p>
<p>với hàm <span class="math inline">\(h\)</span>: <span class="math inline">\(\mathbb{R} \rightarrow \mathbb{R}^+\)</span>. Hàm số <span class="math inline">\(h\)</span> thường được lựa chọn là hàm lũy thừa cơ số tự nhiên <code><a href="https://rdrr.io/r/base/Log.html">exp()</a></code>. Hàm số xác định xác suất xảy ra các sự kiện <span class="math inline">\((Y=j)\)</span> trong phương trình <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:sm">(10.15)</a> được gọi là hàm <span class="math inline">\(softmax\)</span>:
<span class="math display">\[\begin{align}
softmax(z_1, z_2, \cdots, z_p) = \left(\cfrac{e^{z_1}}{\sum\limits_{j=1}^p e^{z_j}}, \cfrac{e^{z_2}}{\sum\limits_{j=1}^p e^{z_1}}, \cdots, \cfrac{e^{z_p}}{\sum\limits_{i=1}^p e^{z_j}}  \right)
\end{align}\]</span></p>
<p>Các tham số <span class="math inline">\(\beta_{j,k}\)</span> được ước lượng để tối thiểu hóa hàm tổn thất tính bằng cross-entropy:
<span class="math display">\[\begin{align}
\sum\limits_{i=1}^n \sum\limits_{j=1}^J y_{i,j} \cdot \log\left(\mathbb{P}\left(Y = j|\textbf{x}_i\right)\right)
\end{align}\]</span></p>
<p>trong đó <span class="math inline">\(\mathbb{P}\left(Y = j|\textbf{x}_i\right)\)</span> được tính toán từ công thức <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:sm">(10.15)</a> và <span class="math inline">\(y_{i,j}\)</span> nhận một trong hai giá trị:</p>
<ul>
<li><p>bằng 1 nếu giá trị quan sát thứ <span class="math inline">\(i\)</span> của biến mục tiêu <span class="math inline">\(Y\)</span> bằng <span class="math inline">\(j\)</span></p></li>
<li><p>bằng 0 nếu giá trị quan sát thứ <span class="math inline">\(i\)</span> của biến mục tiêu <span class="math inline">\(Y\)</span> khác <span class="math inline">\(j\)</span></p></li>
</ul>
<p>Lưu ý rằng có <span class="math inline">\(J\)</span> véc-tơ hệ số tuyến tính trong phương trình <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:sm">(10.15)</a>. Trong thực tế, khi biến mục tiêu <span class="math inline">\(Y\)</span> có thể nhận <span class="math inline">\(J\)</span> giá trị danh nghĩa, chúng ta xây dựng mô hình với <span class="math inline">\((J-1)\)</span> véc-tơ hệ số tuyến tính tương ứng với các giá trị danh nghĩa <span class="math inline">\(1, 2, \cdots, (J-1)\)</span>, đồng thời cố định giá trị của tất cả các hệ số tuyến tính bằng 0 với giá trị danh nghĩa <span class="math inline">\(J\)</span>. Khi tất cả các hệ số tuyến tính bằng 0, chúng ta có <span class="math inline">\(h(.) = exp(0) = 1\)</span> với mọi <span class="math inline">\(\textbf{x}_i\)</span>.</p>
<p><span class="math display" id="eq:sm1">\[\begin{align}
&amp; \mathbb{P}\left(Y = j\right|x_i) = \cfrac{h(\beta_{j,0} + \beta_{j,1} \cdot x_{i,1} + \cdots + \beta_{j,p} \cdot x_{i,p} ) }{1 + \sum\limits_{j=1}^{J-1} h(\beta_{j,0} + \beta_{j,1} \cdot x_{i,1} + \cdots + \beta_{j,p} \cdot x_{i,p} )} \textit{ với } j &lt; J \\
&amp; \mathbb{P}\left(Y = J\right|x_i) = \cfrac{1}{1 + \sum\limits_{j=1}^{J-1} h(\beta_{j,0} + \beta_{j,1} \cdot x_{i,1} + \cdots + \beta_{j,p} \cdot x_{i,p} )} \\
\tag{10.16}
\end{align}\]</span></p>
<p>Chúng ta sẽ xây dựng mô hình phân loại biến mục tiêu trên dữ liệu “travel insurance.csv”. Dữ liệu cung cấp thông tin về các sản phẩm bảo hiểm du lịch từ một đại lý du lịch, với biến mục tiêu là <span class="math inline">\(product.name\)</span> cho biết khách hàng đã lựa chọn sản phẩm sản phẩm bảo hiểm nào. Biến mục tiêu có bốn giá trị tương ứng với bốn loại sản phẩm, mặc dù các sản phẩm này có mức giá khác nhau nhưng việc so sánh các giá trị là không có ý nghĩa. Dữ liệu có 10 biến độc lập, tuy nhiên, để đơn giản hóa, chúng ta chỉ lấy hai biến là giới tính và độ tuổi của người tham gia bảo hiểm.</p>
<p>Mối liên hệ giữa độ tuổi và giới tính của khách hàng đến sản phẩm khách hàng lựa chọn được mô tả qua hình vẽ dưới đây</p>
<div class="inline-figure"><img src="10-mo-hinh-tuyen-tinh-tong-quat_files/figure-html/unnamed-chunk-9-1.png" width="1152"></div>
<p>Có thể thấy rằng có sự khác biệt về độ tuổi của những người lựa chọn các sản phẩm bảo hiểm: những người trẻ tuổi có xu hướng lựa chọn “Bronze Plan” và “Silver Plan” trong khi những người lớn tuổi có xu hướng lựa chọn “Basic Plan” và “Value Plan”. Có sự khác biệt về tỷ lệ nam và nữ khi lựa chọn sản phẩ bảo hiểm, tỷ lệ nam giới lựa chọn “Basic Plan” và “Value Plan” cao, trong khi nữ giới có xu hướng lựa chọn “Bronze Plan” và “Silver Plan”.</p>
<p>Để xây dựng mô hình tuyến tính tổng quát cho biến phân loại danh nghĩa, chúng ta sử dụng hàm <code>multinom()</code> từ thư viện <code>nnet</code>:</p>
<pre><code>## # weights:  16 (9 variable)
## initial  value 19625.769270 
## iter  10 value 18535.510505
## final  value 18040.676017 
## converged</code></pre>
<pre><code>## Call:
## multinom(formula = Product.Name ~ Gender + Age, data = dat1)
## 
## Coefficients:
##             (Intercept)    GenderM          Age
## Bronze Plan   1.5631988 -0.5589519 -0.039513361
## Silver Plan   0.6512458 -0.4871457 -0.031596816
## Value Plan   -1.0970424  0.3380718  0.002018711
## 
## Std. Errors:
##             (Intercept)    GenderM         Age
## Bronze Plan  0.07047991 0.04302279 0.001653049
## Silver Plan  0.08280363 0.05117056 0.001938850
## Value Plan   0.08264747 0.05092679 0.001676413
## 
## Residual Deviance: 36081.35 
## AIC: 36099.35</code></pre>
<p>Dựa trên kết quả ước lượng, chúng ta có công thức tính xác suất chấp nhận các sản phẩm bảo hiểm du lịch của một người có giới tính là <span class="math inline">\(g_i\)</span> và độ tuổi <span class="math inline">\(a_i\)</span> như sau: với sản phẩm “Basic Plan”
<span class="math display">\[\begin{align}
\mathbb{P}(Y = Basic|g_i, a_i) = \cfrac{1}{S_0}
\end{align}\]</span>
với
<span class="math display">\[\begin{align}
S_0 = 1 + exp(1.512 - 0.558 \cdot g_i - 0.038 \cdot a_i) + exp(0.563 - 0.489 \cdot g_i - 0.030 \cdot a_i) +  exp(-3.028 - 0.246 \cdot g_i - 0.039 \cdot a_i)
\end{align}\]</span>
Với các sản phẩm Bronze Plan, Silver Plan và Value Plan, ta có
<span class="math display">\[\begin{align}
&amp; \mathbb{P}(Y = Bronze|g_i, a_i) = \cfrac{exp(1.512 - 0.558 \cdot g_i - 0.038 \cdot a_i)}{S_0} \\
&amp; \mathbb{P}(Y = Silver|g_i, a_i) = \cfrac{exp(0.563 - 0.489 \cdot g_i - 0.030 \cdot a_i)}{S_0} \\
&amp; \mathbb{P}(Y = Value|g_i, a_i) = \cfrac{exp(-3.028 - 0.246 \cdot g_i - 0.039 \cdot a_i)}{S_0}
\end{align}\]</span></p>
Bảng dưới đây tính toán xác suất chấp nhận các sản phẩm du lịch theo một vài độ tuổi và giới tính
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:center;">
Khách hàng
</th>
<th style="text-align:center;">
Độ tuổi
</th>
<th style="text-align:center;">
Giới tính
</th>
<th style="text-align:center;">
Bronze Plan
</th>
<th style="text-align:center;">
Silver Plan
</th>
<th style="text-align:center;">
Value Plan
</th>
<th style="text-align:center;">
Basic Plan
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;border-left:1px solid;">
1
</td>
<td style="text-align:center;border-left:1px solid;">
Nữ
</td>
<td style="text-align:center;border-left:1px solid;">
10
</td>
<td style="text-align:center;border-left:1px solid;">
0.54
</td>
<td style="text-align:center;border-left:1px solid;">
0.23
</td>
<td style="text-align:center;border-left:1px solid;">
0.06
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.17
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
2
</td>
<td style="text-align:center;border-left:1px solid;">
Nữ
</td>
<td style="text-align:center;border-left:1px solid;">
20
</td>
<td style="text-align:center;border-left:1px solid;">
0.48
</td>
<td style="text-align:center;border-left:1px solid;">
0.22
</td>
<td style="text-align:center;border-left:1px solid;">
0.08
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.22
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
3
</td>
<td style="text-align:center;border-left:1px solid;">
Nữ
</td>
<td style="text-align:center;border-left:1px solid;">
30
</td>
<td style="text-align:center;border-left:1px solid;">
0.41
</td>
<td style="text-align:center;border-left:1px solid;">
0.21
</td>
<td style="text-align:center;border-left:1px solid;">
0.10
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.28
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
4
</td>
<td style="text-align:center;border-left:1px solid;">
Nữ
</td>
<td style="text-align:center;border-left:1px solid;">
40
</td>
<td style="text-align:center;border-left:1px solid;">
0.34
</td>
<td style="text-align:center;border-left:1px solid;">
0.19
</td>
<td style="text-align:center;border-left:1px solid;">
0.13
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.35
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
5
</td>
<td style="text-align:center;border-left:1px solid;">
Nữ
</td>
<td style="text-align:center;border-left:1px solid;">
50
</td>
<td style="text-align:center;border-left:1px solid;">
0.27
</td>
<td style="text-align:center;border-left:1px solid;">
0.16
</td>
<td style="text-align:center;border-left:1px solid;">
0.15
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.41
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
6
</td>
<td style="text-align:center;border-left:1px solid;">
Nữ
</td>
<td style="text-align:center;border-left:1px solid;">
60
</td>
<td style="text-align:center;border-left:1px solid;">
0.21
</td>
<td style="text-align:center;border-left:1px solid;">
0.14
</td>
<td style="text-align:center;border-left:1px solid;">
0.18
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.47
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
7
</td>
<td style="text-align:center;border-left:1px solid;">
Nam
</td>
<td style="text-align:center;border-left:1px solid;">
10
</td>
<td style="text-align:center;border-left:1px solid;">
0.44
</td>
<td style="text-align:center;border-left:1px solid;">
0.21
</td>
<td style="text-align:center;border-left:1px solid;">
0.11
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.24
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
8
</td>
<td style="text-align:center;border-left:1px solid;">
Nam
</td>
<td style="text-align:center;border-left:1px solid;">
20
</td>
<td style="text-align:center;border-left:1px solid;">
0.37
</td>
<td style="text-align:center;border-left:1px solid;">
0.19
</td>
<td style="text-align:center;border-left:1px solid;">
0.15
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.30
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
9
</td>
<td style="text-align:center;border-left:1px solid;">
Nam
</td>
<td style="text-align:center;border-left:1px solid;">
30
</td>
<td style="text-align:center;border-left:1px solid;">
0.30
</td>
<td style="text-align:center;border-left:1px solid;">
0.16
</td>
<td style="text-align:center;border-left:1px solid;">
0.18
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.36
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
10
</td>
<td style="text-align:center;border-left:1px solid;">
Nam
</td>
<td style="text-align:center;border-left:1px solid;">
40
</td>
<td style="text-align:center;border-left:1px solid;">
0.23
</td>
<td style="text-align:center;border-left:1px solid;">
0.14
</td>
<td style="text-align:center;border-left:1px solid;">
0.21
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.42
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
11
</td>
<td style="text-align:center;border-left:1px solid;">
Nam
</td>
<td style="text-align:center;border-left:1px solid;">
50
</td>
<td style="text-align:center;border-left:1px solid;">
0.18
</td>
<td style="text-align:center;border-left:1px solid;">
0.11
</td>
<td style="text-align:center;border-left:1px solid;">
0.24
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.47
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;">
12
</td>
<td style="text-align:center;border-left:1px solid;">
Nam
</td>
<td style="text-align:center;border-left:1px solid;">
60
</td>
<td style="text-align:center;border-left:1px solid;">
0.13
</td>
<td style="text-align:center;border-left:1px solid;">
0.09
</td>
<td style="text-align:center;border-left:1px solid;">
0.27
</td>
<td style="text-align:center;border-left:1px solid;border-right:1px solid;">
0.51
</td>
</tr>
</tbody>
</table></div>
<p>Kết quả từ mô hình cho thấy chỉ có “Basic Plan” và “Bronze Plan” được chọn nếu chúng ta chỉ sử dụng hai biến độc lập là giới tính và độ tuổi. Khả năng dự đoán của mô hình không cao do mô hình còn quá đơn giản, chúng tôi muốn nhấn mạnh về cách xây dựng mô hình trước khi cố gắng xây dựng một mô hình có khả năng dự báo tốt. Chúng ta sẽ thảo luận về đánh giá hiệu quả của mô hình ở các phần sau của chương sách.</p>
</div>
<div id="biến-phụ-thuộc-là-biến-rời-rạc-có-thứ-tự." class="section level3" number="10.2.3">
<h3>
<span class="header-section-number">10.2.3</span> Biến phụ thuộc là biến rời rạc có thứ tự.<a class="anchor" aria-label="anchor" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-l%C3%A0-bi%E1%BA%BFn-r%E1%BB%9Di-r%E1%BA%A1c-c%C3%B3-th%E1%BB%A9-t%E1%BB%B1."><i class="fas fa-link"></i></a>
</h3>
<p>Biến rời rạc có thứ tự, còn gọi là ordinal categorical variable, là các biến nhận giá trị rời rạc mà các giá trị rời rạc có thể so sánh được với nhau. Một ví dụ điển hình cho biến rời rạc có thứ tự là số lần mà một người đi khám chữa bệnh sử dụng bảo hiểm y tế hoặc một khách hàng gửi yêu cầu bồi thường đến công ty bảo hiểm. Đây là trường hợp mà chúng ta có thể sử dụng một phân phối xác suất rời rạc có tham số để mô tả biến phụ thuộc <span class="math inline">\(Y\)</span> giống như mô hình <a href="#eq:gml1">(<strong>??</strong>)</a>.</p>
<div id="biến-phụ-thuộc-có-phân-phối-poisson." class="section level4" number="10.2.3.1">
<h4>
<span class="header-section-number">10.2.3.1</span> Biến phụ thuộc có phân phối Poisson.<a class="anchor" aria-label="anchor" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-c%C3%B3-ph%C3%A2n-ph%E1%BB%91i-poisson."><i class="fas fa-link"></i></a>
</h4>
<p>Phân phối rời rạc thường được lựa chọn cho biến phụ thuộc rời rạc có thứ tự là phân phối Poisson. Hàm phân phối xác suất của biến ngẫu nhiên <span class="math inline">\(Y\)</span> có phân phối Poisson với tham số <span class="math inline">\(\lambda &gt; 0\)</span>, ký hiệu <span class="math inline">\(Y \sim \mathcal{P}(\lambda)\)</span> được cho bởi công thức sau
<span class="math display">\[\begin{align}
\mathbb{P}(Y = y) = e^{-\lambda} \cdot \cfrac{\lambda^y}{y!} \text{ với } y = 0, 1, 2, \cdots
\end{align}\]</span></p>
<p>Phân phối Poisson thường được sử dụng để mô tả số lần một hiện tượng xảy ra trong một khoảng thời gian nhất định. Nguyên nhân là do phân phối Poisson này có mối liên hệ trực tiếp đến các mô hình có thời gian chờ có phân phối kiểu mũ. Thật vậy, nếu thời gian chờ giữa hai sự kiện liên tiếp xảy ra của một hiện tượng nào đó là một biến ngẫu nhiên liên tục có hàm phân phối xác suất kiểu mũ với tham số <span class="math inline">\(\gamma\)</span> thì số lần hiện tượng đó xảy ra trong một khoảng thời gian từ <span class="math inline">\(t_1\)</span> đến <span class="math inline">\(t_2\)</span> sẽ là một biến ngẫu nhiên phân phối Poisson với tham số <span class="math inline">\(\lambda = \cfrac{(t_1 - t_2)}{\gamma}\)</span>. Thật vậy, với <span class="math inline">\(T\)</span> là khoảng thời gian giữa 2 sự kiện liên tiếp xảy ra và <span class="math inline">\(T\)</span> có phân phối mũ:
<span class="math display">\[\begin{align}
\mathbb{P}(T \leq x) = 1 - exp(-\gamma x)
\end{align}\]</span>
và nếu <span class="math inline">\(N\)</span> là số lần xảy ra sự kiện (đi khám bệnh, lái xe gây ra tai nạn) giữa hai mốc thời gian <span class="math inline">\(t_1 &lt; t_2\)</span> thì <span class="math inline">\(N\)</span> sẽ có phân phối Poisson với tham số <span class="math inline">\(\lambda\)</span>:
<span class="math display">\[\begin{align}
&amp; \mathbb{P}(N = k) = e^{-\lambda} \cdot \cfrac{\lambda^k}{k!}\\
&amp; \lambda = \cfrac{(t_1 - t_2)}{\gamma}
\end{align}\]</span></p>
<p>Biến ngẫu nhiên có phân phối Poisson với tham số <span class="math inline">\(\lambda\)</span>, ký hiệu <span class="math inline">\(\mathcal{P}(\lambda)\)</span>, có tính chất là giá trị trung bình và phương sai đều bằng tham số của biến đó là <span class="math inline">\(\lambda\)</span>. Phân phối Poisson nằm trong họ các phân phối mũ nên sẽ rất thuận tiện trong xây dựng và ước lượng mô hình bằng phương pháp hợp lý tối đa. Ngoài ra, bằng cách cho tham số của phân phối Poisson một phân phối xác suất, chúng ta có thể thu được các phân phối rời rạc linh hoạt hơn trong mô tả các biến ngẫu nhiên dạng đếm được.</p>
<p>Khi xây dựng mô hình tuyến tính với biến mục tiêu <span class="math inline">\(Y\)</span> có phân phối Poisson, giá trị trung bình <span class="math inline">\(Y\)</span> nhận giá trị dương nên chúng ta cần chọn các hàm liên kết <span class="math inline">\(g\)</span> có miền xác định là tập các số thực dương <span class="math inline">\(\mathbb{R}^+\)</span> và miền giá trị là tập số thực <span class="math inline">\(\mathbb{R}\)</span>. Hàm số thường được lựa chọn là hàm <span class="math inline">\(log\)</span>.</p>
<p>Chúng ta có thể viết mô hình tuyến tính tổng quát khi <span class="math inline">\(Y\)</span> có phân phối Poisson, thường được gọi tắt là hồi quy Poisson, như sau</p>
<p><span class="math display" id="eq:pois1">\[\begin{align}
&amp; Y_i \sim \mathcal{P}(\lambda_i) \\
&amp; log(\lambda_i) = \left(\beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,p}\right) \\
\tag{10.17}
\end{align}\]</span></p>
<p>Dữ liệu được sử dụng để mô tả mô hình tuyến tính tổng quát với biến phụ thuộc phân phối Poisson là dữ liệu <span class="math inline">\(SingaporeAuto.csv\)</span>. Dữ liệu được tổng hợp bởi Hiệp hội bảo hiểm Singapore trong năm 1993 mô tả số vụ tai nạn ô tô xảy ra cùng với các đặc điểm của người lái và đặc điểm của xe gây tai nạn. Cũng giống như các phần trước, chúng ta sẽ xây dựng mô hình ở mức độ đơn giản nhất để bạn đọc dễ dàng hình dung. Biến phụ thuộc trong mô hình là biến <span class="math inline">\(Clm\_Count\)</span> cho biết số vụ tai nạn mà một lái xe gây ra trong vòng một năm, hai biến phụ thuộc bao gồm có:</p>
<ul>
<li><p>Biến <span class="math inline">\(PC\)</span> là biến nhận hai giá trị là 0 tương ứng với xe được đăng ký theo công ty và nhận giá trị 1 tương ứng với xe được đăng ký theo cá nhân.</p></li>
<li><p>Biến <span class="math inline">\(NCD\)</span>, viết tắt của No Claims Discount, cho biết lịch sử gây ra tai nạn của lái xe. Giá trị <span class="math inline">\(NCD\)</span> càng cao nghĩa là lịch sử người lái xe càng gây ra ít tai nạn.</p></li>
</ul>
<p>Chúng ta sử dụng hàm <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> để xây dựng và ước lượng mô hình tuyến tính tổng quát:</p>
<div class="sourceCode" id="cb652"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD/Dataset/SingaporeAuto.csv"</span><span class="op">)</span></span>
<span><span class="va">glm2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Clm_Count</span><span class="op">~</span><span class="va">PC</span><span class="op">+</span><span class="va">NCD</span>, data<span class="op">=</span><span class="va">dat</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm2</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Clm_Count ~ PC + NCD, family = poisson(link = "log"), 
##     data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.4685  -0.3801  -0.3520  -0.3283   4.1716  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -2.641681   0.073836 -35.778  &lt; 2e-16 ***
## PC           0.431980   0.091840   4.704 2.56e-06 ***
## NCD         -0.013943   0.002618  -5.327 9.99e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 2887.2  on 7482  degrees of freedom
## Residual deviance: 2848.3  on 7480  degrees of freedom
## AIC: 3849.4
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Bạn đọc có thể thấy rằng cả hai biến <span class="math inline">\(PC\)</span> và <span class="math inline">\(NCD\)</span> đều có tác động đến giá trị trung bình của biến mục tiêu <span class="math inline">\(Clm\_Count\)</span> do các giá trị p-value đều nhỏ. Mối liên hệ giữa số lượng tai nạn xảy ra và các biến <span class="math inline">\(PC\)</span> và <span class="math inline">\(NCD\)</span> được mô tả như sau:</p>
<p><span class="math display" id="eq:pois2">\[\begin{align}
&amp; Clm\_Count_i \sim \mathcal{P}(\lambda_i) \\
&amp; \log(\lambda_i) = -2.641 + 0.432 \cdot PC_{i} - 0.013 \cdot NCD_{i} \\
&amp; \lambda_i = \exp\left(-2.641 + 0.432 \cdot PC_{i} - 0.013 \cdot NCD_{i} \right)
\tag{10.18}
\end{align}\]</span></p>
<p>Hệ số của biến <span class="math inline">\(PC\)</span> là số dương, điều này cho biết các xe đăng ký dưới dạng cá nhân có khả năng gây tai nạn cao hơn so với xe đăng ký dưới hình thức doanh nghiệp. Đồng thời, hệ số của biến <span class="math inline">\(NCD\)</span> âm cho biết lái xe có lịch sử lái xe tốt, tương ứng với <span class="math inline">\(NCD\)</span> cao, ít có khả năng gây ra tai nạn hơn lái xe có lịch sử lái xe không tốt, tương ứng với <span class="math inline">\(NCD\)</span> thấp.</p>
</div>
<div id="phân-phối-rời-rạc-có-lạm-phát-tại-giá-trị-0." class="section level4" number="10.2.3.2">
<h4>
<span class="header-section-number">10.2.3.2</span> Phân phối rời rạc có lạm phát tại giá trị 0.<a class="anchor" aria-label="anchor" href="#ph%C3%A2n-ph%E1%BB%91i-r%E1%BB%9Di-r%E1%BA%A1c-c%C3%B3-l%E1%BA%A1m-ph%C3%A1t-t%E1%BA%A1i-gi%C3%A1-tr%E1%BB%8B-0."><i class="fas fa-link"></i></a>
</h4>
<p>Biến phụ thuộc dạng đếm chứa một tỷ lệ lớn giá trị bằng 0 là các kiểu biến phụ thuộc thường gặp phải khi làm việc trên dữ liệu trong lĩnh vực bảo hiểm. Tỷ lệ lớn ở đây thường được hiểu là trên 90% giá trị quan sát được. Đa số các phân phối xác suất rời rạc thông thường, bao gồm phân phối Poisson, không mô tả tốt khi biến phụ thuộc <span class="math inline">\(Y\)</span> trong trường hợp này.</p>
<p>Một giải pháp phổ biến khi làm việc với kiểu dữ liệu như vậy là thay đổi phân phối dạng đếm thông thường để làm tăng tỷ lệ giá trị nhận được tại 0, để thu được các phân phối thường được gọi là các phân phối lạm phát tại 0, hay Zero-inflated variable. Phân phối lạm phát tại 0 là hỗn hợp của hai phân phối xác suất rời rạc, bao gồm một phân phối nhị thức chỉ báo cho trường hợp 0, và một phân phối xác suất dành cho biến đếm thông thường. Hàm phân phối của biến ngẫu nhiên dạng đếm có lạm phát tại 0, ký hiệu <span class="math inline">\(ZI_Y\)</span>, có thể được mô tả như sau
<span class="math display" id="eq:zip1">\[\begin{align}
\mathbb{P}(ZI_Y = y) = \begin{cases}
&amp; \omega + (1-\omega) \cdot \mathbb{P}(Y=0) \text{ khi y = 0} \\
&amp; (1-\omega) \cdot \mathbb{P}(Y=y) \text{ khi y &gt; 0}
\end{cases}
\tag{10.19}
\end{align}\]</span>
trong đó biến ngẫu nhiên <span class="math inline">\(Y\)</span> tuân theo phân phối số đếm tiêu chuẩn được. Trong trường hợp tham số <span class="math inline">\(\omega\)</span> bằng 0, phân phối của biến ngẫu nhiên <span class="math inline">\(ZI_Y\)</span> sẽ tương ứng tương ứng với phân phối của biến Y.</p>
<p>Tất cả các phân phối kiểu đếm đều có thể được sử dụng để tạo ra các biến mới có lạm phát tại 0. Trong các mô hình tuyến tính tổng quát, biến dạng đếm thường được mô tả bằng phân phối cổ điển Poisson. Với việc sử dụng phương trình <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:zip1">(10.19)</a>, hàm phân phối của biến ngẫu nhiên Poisson có lạm phát tại 0, ký hiệu là <span class="math inline">\(ZI_\mathcal{P}\)</span> được cho bởi công thức sau:</p>
<p><span class="math display" id="eq:zip2">\[\begin{align}
\mathbb{P}(ZI_\mathcal{P} = y) = \begin{cases}
&amp; \omega + (1-\omega) \cdot e^{-\lambda} \text{ khi y = 0} \\
&amp; (1-\omega) \cdot e^{-\omega} \cdot \cfrac{\lambda^y}{y!} \text{ khi y &gt; 0}
\end{cases}
\tag{10.20}
\end{align}\]</span></p>
<p>Chúng ta có thể xác định giá trị trung bình và phương sai của phân phối <span class="math inline">\(ZI_Y\)</span> dựa trên tham số <span class="math inline">\(\omega\)</span> và giá trị trung bình cũng như phương sai của biến <span class="math inline">\(Y\)</span> như sau
<span class="math display" id="eq:zip3">\[\begin{align}
&amp; \mathbb{E}(ZI_Y) = (1-\omega) \cdot \mathbb{E}(Y) \\
&amp; \mathbb{V}(ZI_Y) = (1-\omega) \cdot \mathbb{V}(Y) + \omega(1-\omega) \cdot \mathbb{E}(Y)^2
\tag{10.21}
\end{align}\]</span></p>
<p>Trong trường hợp <span class="math inline">\(Y\)</span> có phân phối Poission, chúng ta có giá trị trung bình và phương sai của biến <span class="math inline">\(ZI_\mathcal{P}\)</span>:
<span class="math display" id="eq:zip4">\[\begin{align}
&amp; \mathbb{E}(ZI_\mathcal{P}) = (1-\omega) \cdot \lambda \\
&amp; \mathbb{V}(ZI_\mathcal{P}) = \mathbb{E}(ZI_\mathcal{P}) \cdot (1 + \lambda - \mathbb{E}(ZI_\mathcal{P}))
\tag{10.22}
\end{align}\]</span></p>
<p>Với giá trị trung bình và phương sai của biến <span class="math inline">\(ZI_\mathcal{P}\)</span> như phương trình <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:zip1">(10.19)</a>, chúng ta có thể xây dựng mô hình tuyến tính tổng quát với biến phụ thuộc là <span class="math inline">\(ZI_\mathcal{P}\)</span> như sau: giá trị trung bình <span class="math inline">\(\left((1-\omega) \cdot \lambda\right)\)</span> sẽ được giải thích thông qua các biến phụ thuộc trong khi tham số <span class="math inline">\(\lambda\)</span> sẽ được ước lượng bằng phương pháp hợp lý tối đa.</p>
<p>Biến phụ thuộc phân phối <span class="math inline">\(ZI_\mathcal{P}\)</span> sẽ hữu ích cho mục đích lập mô hình trong trường hợp dữ liệu quan sát có sự tập trung quá mức tại giá trị 0. Ngoài phân phối Poisson, các phân phối mở rộng từ phân phối Poisson cũng có thể được sử dụng với để tạo ra các phân phối có lạm phát tại 0, chẳng hạn như biến ngẫu nhiên phân phối Poisson - Gamma, Poisson - Inverse gaussian.</p>
<p>Trong các nghiên cứu thực nghiệm, nhiều tác giả đã chứng minh rằng việc áp dụng phân phối có lạm phát tại 0 để mô hình hóa số lượng yêu cầu bồi thường bảo hiểm là phù hợp để mô tả hành vi của người được bảo hiểm. Thật vậy, trong ngành bảo hiểm không phải tất cả các vụ tai nạn đều được báo cáo, công ty bảo hiểm chỉ có thông tin về các yêu cầu bồi thường được báo cáo. Có hai cách để giải thích cách phân phối có lạm phát tại 0 như sau: (1) Một số người được bảo hiểm không gửi yêu cầu bồi thường dù có xảy ra sự kiện bảo hiểm, do họ không có nhận thức được về việc được bảo hiểm, hoặc không có nhu cầu gửi yêu cầu bảo hiểm. (2) Một cách giải thích khác của mô hình lạm phát tại 0 là xem xét xác suất của mỗi vụ tai nạn được báo cáo. Một hành vi thực tế của người được bảo hiểm là nếu họ đã báo cáo vụ tai nạn đầu tiên thì những vụ tai nạn tiếp theo cũng sẽ được báo cáo, còn nếu vụ tai nạn đầu tiên không được báo cáo thì các vụ tai nạn sau sẽ không được báo cáo. Cả hai cách giải thích dựa trên hành vi này đều dẫn đến việc số lượng biến mục tiêu nhận giá trị bằng 0 cao hơn so với số lượng tai nạn thực tế xảy ra.</p>
Dữ liệu <span class="math inline">\(exposure.csv\)</span> là dữ liệu điển hình cho biến phụ thuộc có lạm phát tại giá trị 0. Dữ liệu được rút gọn chỉ bao gồm hai biến độc lập là tuổi (Age) và giới tính (Gender) của người được bảo hiểm. Biến phụ thuộc là số lần người được bảo hiểm báo cáo tai nạn trong khoảng thời gian một năm. Sự khác nhau giữa mô hình tuyến tính tổng quát với biến phụ thuộc có phân phối Poisson thông thường và mô hình tuyến tính tổng quát với biến phụ thuộc có phân phối Poisson có lạm phát tại 0 được mô tả như sau:
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-13">Table 10.1: </span>Khác nhau giữa GLM - Poisson và GLM - ZIP
</caption>
<thead><tr>
<th style="text-align:left;">
Thành phần
</th>
<th style="text-align:left;">
GLM Poisson
</th>
<th style="text-align:left;">
GLM Poisson Zero-inflated
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Phân phối của biến phụ thuộc
</td>
<td style="text-align:left;">
<span class="math inline">\(Y_i \sim \mathcal{P}(\lambda_i)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(Y_i \sim ZI_\mathcal{P}(\lambda_i, \omega)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Trung bình của biến phụ thuộc
</td>
<td style="text-align:left;">
<span class="math inline">\(\lambda_i\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\lambda_i \cdot (1-\omega)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Tham số của biến Poisson
</td>
<td style="text-align:left;">
<span class="math inline">\(\lambda_i = exp(\beta_0 + \beta_1 \cdot Age_i + \beta_2 \cdot Gender_i)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\lambda_i = exp(\beta_0 + \beta_1 \cdot Age_i + \beta_2 \cdot Gender_i)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Tham số Zero-inflated
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
<span class="math inline">\(\omega = exp(\alpha_0)\)</span>
</td>
</tr>
</tbody>
</table></div>
<p>Để xây dựng mô hình tuyến tính tổng quát trong đó biến phụ thuộc có phân phối <span class="math inline">\(ZI_\mathcal{P}\)</span> chúng ta sử dụng hàm số <code>zeroinfl()</code> của thư viện <span class="math inline">\(pscl\)</span>.</p>
<div class="sourceCode" id="cb654"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD/Dataset/exposure.csv"</span><span class="op">)</span></span>
<span><span class="co"># Biến phụ thuộc có phân phối Poisson</span></span>
<span><span class="va">glm1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Claim_Count</span><span class="op">~</span><span class="va">Age</span><span class="op">+</span><span class="va">Gender</span>,</span>
<span>          family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>,</span>
<span>          data<span class="op">=</span><span class="va">dat</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Biến phụ thuộc có phân phối Zero inflated poisson</span></span>
<span><span class="va">zip.glm</span><span class="op">&lt;-</span><span class="fu">zeroinfl</span><span class="op">(</span><span class="va">Claim_Count</span><span class="op">~</span><span class="va">Age</span><span class="op">+</span><span class="va">Gender</span><span class="op">|</span><span class="fl">1</span>,</span>
<span>                  dist <span class="op">=</span> <span class="st">'poisson'</span>,</span>
<span>                  link <span class="op">=</span> <span class="st">"log"</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">zip.glm</span><span class="op">)</span></span></code></pre></div>
<p>Chúng ta có kết quả ước lượng các mô hình</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-15">Table 1.3: </span>Kết quả ước lượng GLM - Poisson và GLM - ZIP
</caption>
<thead><tr>
<th style="text-align:left;">
Thành phần
</th>
<th style="text-align:left;">
GLM Poisson
</th>
<th style="text-align:left;">
GLM Poisson Zero-inflated
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Phân phối của biến phụ thuộc
</td>
<td style="text-align:left;">
<span class="math inline">\(Y_i \sim \mathcal{P}(\lambda_i)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(Y_i \sim ZI_\mathcal{P}(\lambda_i, \theta)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Trung bình của biến phụ thuộc
</td>
<td style="text-align:left;">
<span class="math inline">\(\lambda_i\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\lambda_i \cdot (1-\theta)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Tham số của biến Poisson
</td>
<td style="text-align:left;">
<span class="math inline">\(\lambda_i = exp(-0.544 - 0.0214 \cdot Age + 0.106 \cdot Gender)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\lambda_i = exp(-0.063 - 0.0215 \cdot Age + 0.104 \cdot Gender)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Tham số Zero-inflated
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
<span class="math inline">\(\theta = exp(-0.971)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Giá trị Log Likelyhood
</td>
<td style="text-align:left;">
-6419
</td>
<td style="text-align:left;">
-6353
</td>
</tr>
</tbody>
</table></div>
<p>Có thể thấy rằng mô hình tuyến tính tổng quát với biến phụ thuộc phân phối <span class="math inline">\(ZI_\mathcal{P}\)</span> có giá trị hàm hợp lý tối đa lớn hơn, điều này cũng có nghĩa là phân phối <span class="math inline">\(ZI_\mathcal{P}\)</span> phù hợp hơn phân phối Poisson thông thường khi mô tả biến phụ thuộc trong dữ liệu. Dựa vào kết quả ước lượng từ hai mô hình, chúng ta có thể tính toán xác suất không có tai nạn và xác suất để xảy ra một tai nạn theo độ tuổi và giới tính của người tham gia bảo hiểm như sau</p>
<div class="inline-figure"><img src="10-mo-hinh-tuyen-tinh-tong-quat_files/figure-html/unnamed-chunk-16-1.png" width="1152" style="display: block; margin: auto;"></div>
<div class="inline-figure"><img src="10-mo-hinh-tuyen-tinh-tong-quat_files/figure-html/unnamed-chunk-17-1.png" width="1152" style="display: block; margin: auto;"></div>
<p>Có thể nhận thấy rằng xác suất mà một người được bảo hiểm không để xảy ra tai nạn trong mô hình tuyến tính tổng quát với biến phụ thuộc có phân phối <span class="math inline">\(ZI_\mathcal{P}\)</span> là luôn cao hơn so với mô hình tuyến tính tổng quát với biến phụ thuộc có phân phối Poisson thông thường. Đồng thời, mô hình tuyến tính tổng quát với biến phụ thuộc có phân phối <span class="math inline">\(ZI_\mathcal{P}\)</span> cho kết quả xác suất xảy ra đúng một tai nạn thấp hơn so với mô hình có biến phụ thuộc có phân phối Poisson thông thường.</p>
</div>
</div>
<div id="biến-phụ-thuộc-có-phân-phối-liên-tục." class="section level3" number="10.2.4">
<h3>
<span class="header-section-number">10.2.4</span> Biến phụ thuộc có phân phối liên tục.<a class="anchor" aria-label="anchor" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-c%C3%B3-ph%C3%A2n-ph%E1%BB%91i-li%C3%AAn-t%E1%BB%A5c."><i class="fas fa-link"></i></a>
</h3>
<p>Một giả thiết quan trọng của mô hình tuyến tính tổng quát là biến phụ thuộc nằm trong họ các biến ngẫu nhiên có phân phối kiểu mũ, hay exponential family. Chúng ta sẽ thảo luận kỹ hơn về họ các biến ngẫu nhiên có phân phối kiểu mũ trong phần sau của cuốn sách. Lưu ý rằng họ các biến ngẫu nhiên có phân phối kiểu mũ không tương đồng với khái niệm biến ngẫu nhiên có phân phối mũ. Phân phối mũ chỉ là mộ trường hợp đặc biệt của phân phối kiển mũ. Có nhiều biến ngẫu nhiên liên tục khác có phân phối nằm trong họ các phân phối kiểu mũ. Có thể kể đến như phân phối gamma, phân phối chuẩn, phân phối chuẩn ngược…</p>
<p>Các bước để xây dựng mô hình tuyến tính tổng quát trong trường hợp biến phụ thuộc <span class="math inline">\(Y\)</span> là biến ngẫu nhiên liên tục hoàn toàn tương tự như cách xây dựng mô hình tuyến tính tổng quát ở trên, bao gồm bước chọn phân phối xác suất cho biến mục tiêu và lựa chọn hàm liên kết phù hợp. Chúng ta sẽ tiếp tục xây dựng mô hình với dữ liệu “exposure.csv” đã đề cập ở các phần trên. Biến mục tiêu không còn là số lần khách hàng gửi yêu cầu bồi thường, mà là số tiền trung bình mỗi lần khách hàng gửi yêu cầu (biến <span class="math inline">\(Ave\_Amount\)</span>). Các biến giải thích vẫn tiếp tục là giới tính (<span class="math inline">\(Gender\)</span>) và độ tuổi (<span class="math inline">\(Age\)</span>) của người được bảo hiểm.</p>
<div class="sourceCode" id="cb655"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD/Dataset/exposure.csv"</span><span class="op">)</span></span>
<span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">dat</span>,Ave_Amount <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">Claim_Count</span><span class="op">&gt;</span><span class="fl">0</span>,<span class="va">Total_Claim</span><span class="op">/</span><span class="va">Claim_Count</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat1</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">dat</span>,<span class="va">Claim_Count</span><span class="op">&gt;</span><span class="fl">0</span><span class="op">)</span></span></code></pre></div>
<p>Mối liên hệ giữa <span class="math inline">\(Ave\_Amount\)</span> được thể hiện qua đồ thị dưới đây</p>
<div class="sourceCode" id="cb656"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat1</span><span class="op">$</span><span class="va">Gender</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">dat1</span><span class="op">$</span><span class="va">Gender</span><span class="op">==</span><span class="fl">0</span>,<span class="st">"F"</span>,<span class="st">"M"</span><span class="op">)</span></span>
<span><span class="va">p1</span><span class="op">&lt;-</span><span class="va">dat1</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">Gender</span>,y <span class="op">=</span> <span class="va">Ave_Amount</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">ylim</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">200</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Số tiền yêu cầu bồi thường trung bình và giới tính"</span><span class="op">)</span></span>
<span><span class="va">p2</span><span class="op">&lt;-</span><span class="va">dat1</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">Age</span>,y <span class="op">=</span> <span class="va">Ave_Amount</span><span class="op">)</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha<span class="op">=</span><span class="fl">0.2</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>col<span class="op">=</span><span class="st">"black"</span>, size <span class="op">=</span> <span class="fl">1</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/lims.html">ylim</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">200</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Số tiền yêu cầu bồi thường trung bình và độ tuổi"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/gridExtra/man/arrangeGrob.html">grid.arrange</a></span><span class="op">(</span><span class="va">p1</span>,<span class="va">p2</span>,ncol<span class="op">=</span><span class="fl">2</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="10-mo-hinh-tuyen-tinh-tong-quat_files/figure-html/unnamed-chunk-19-1.png" width="672"></div>
<p>Đồ thị bên trái cho thấy số tiền yêu cầu bồi thường trung bình của nữ là cao hơn nam giới. Phân phối xác suất của số tiền yêu cầu bồi thương trung bình là phân phối liên tục lệch phải, có đuôi bên phải lớn. Đồ thị bên phải cho thấy số tiền yêu cầu bồi thường trung bình có xu hướng tăng theo độ tuổi.</p>
<p>Số tiền bảo hiểm trung bình là số dương nên chúng ta sẽ sử dụng phân phối <span class="math inline">\(gamma\)</span> với hàm liên kết là hàm <code><a href="https://rdrr.io/r/base/Log.html">log()</a></code>. Lưu ý rằng phân phối <code><a href="https://rdrr.io/r/base/Special.html">gamma()</a></code> là phân phối có hai tham số, thường được ký hiệu là <span class="math inline">\(\alpha\)</span> và <span class="math inline">\(\gamma\)</span>, với hàm mật độ xác suất, giá trị trung bình, và phương sai như sau
<span class="math display">\[\begin{align}
&amp; f_Y(y) = \cfrac{\beta^\alpha}{\Gamma(\alpha)} \ y^{\alpha-1} \ e^{-\gamma y} \\
&amp; \mathbb{E}(X) = \cfrac{\alpha}{\gamma} \\
&amp; \mathbb{V}(X) = \cfrac{\alpha}{\gamma^2}
\end{align}\]</span></p>
<p>Khi phân phối <span class="math inline">\(gamma\)</span> được sử dụng cho biến phụ thuộc, giá trị trung bình được tính bằng <span class="math inline">\(\alpha/\gamma\)</span>, sẽ được mô tả thông qua các biến độc lập trong khi tham số <span class="math inline">\(\alpha\)</span> sẽ được ước lượng dựa trên hàm hợp lý tối đa:</p>
<div class="sourceCode" id="cb657"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD/Dataset/exposure.csv"</span><span class="op">)</span></span>
<span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">dat</span>,Ave_Amount <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">Claim_Count</span><span class="op">&gt;</span><span class="fl">0</span>,<span class="va">Total_Claim</span><span class="op">/</span><span class="va">Claim_Count</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat1</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">dat</span>,<span class="va">Claim_Count</span><span class="op">&gt;</span><span class="fl">0</span><span class="op">)</span></span>
<span><span class="va">glm3</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Ave_Amount</span><span class="op">~</span><span class="va">Age</span><span class="op">+</span><span class="va">Gender</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">Gamma</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span>,data <span class="op">=</span> <span class="va">dat1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm3</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Ave_Amount ~ Age + Gender, family = Gamma(link = "log"), 
##     data = dat1)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -4.3309  -0.9498  -0.3047   0.3360   2.9954  
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.047535   0.065517  -0.726    0.468    
## Age          0.079089   0.001534  51.563   &lt;2e-16 ***
## Gender      -0.534010   0.041951 -12.730   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for Gamma family taken to be 0.9241118)
## 
##     Null deviance: 4666.5  on 2110  degrees of freedom
## Residual deviance: 2205.7  on 2108  degrees of freedom
## AIC: 15710
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Ngoài các hệ số của các biến độc lập trong mô hình tuyến tính tổng quát, hàm <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> còn cung cấp giá trị ước lượng được cho tham số <span class="math inline">\(\phi\)</span> (disperson paramter hay tham số phân tán) là <span class="math inline">\(0.924\)</span>. Tham số phân tán được định nghĩa trong họ các phân phối kiểu mũ sẽ được thảo luận trong phần tiếp theo. Đối với phân phối <span class="math inline">\(gamma\)</span>, tham số phân tán được tính bằng <span class="math inline">\(\phi = 1/\alpha\)</span>.</p>
<p>Giá trị số tiền bồi thường trung bình được được mô tả bằng mô hình tuyến tính tổng quát như sau:
<span class="math display">\[\begin{align}
&amp; Y_i \sim Gamma(\mu_i = \alpha_i/\gamma_i , \phi_i = 1/\alpha_i) \\
&amp; \phi_i = 0.924 \\
&amp; log(\mu_i) = -0.0475 + 0.079 \cdot Age_i + 0.534 \cdot Gender_i
\end{align}\]</span></p>
<p>Trước khi đi vào chi tiết các thành phần của mô hình, chúng tôi muốn kết luận rằng mô hình tuyến tính tổng quát có thể được sử dụng để mô hình hóa dữ liệu trong nhiều hoàn cảnh khác nhau. Việc xây dựng mô hình tuyến tính tổng quát luôn được bắt đầu bằng việc lựa chọn phân phối cho biến phụ thuộc và lựa chọn hàm số liên kết. Có các quy tắc chung trong việc lựa chọn phân phối và hàm liên kết giống như chúng tôi đã trình bày ở phần trên. Tuy nhiên để đưa ra được mô hình tuyến tính tổng quát phù hợp cho từng dữ liệu cụ thể, hoặc để có thể mở rộng được mô hình tuyến tính tổng quát trong các kiểu dữ liệu phức tạp hơn, bạn đọc cần am hiểu sâu hơn về các đặc điểm kỹ thuật của các mô hình này. Các kiến thức này sẽ được trình bày trong các phần tiếp theo của chương.</p>
</div>
</div>
<div id="các-thành-phần-của-mô-hình-tuyến-tính-tổng-quát." class="section level2" number="10.3">
<h2>
<span class="header-section-number">10.3</span> Các thành phần của mô hình tuyến tính tổng quát.<a class="anchor" aria-label="anchor" href="#c%C3%A1c-th%C3%A0nh-ph%E1%BA%A7n-c%E1%BB%A7a-m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t."><i class="fas fa-link"></i></a>
</h2>
<p>Như chúng ta đã thảo luận trong phần trước, mô hình tuyến tính tổng quát khắc phục hai giả thiết, cũng là hai nhược điểm của mô hình tuyến tính thông thường, đó là i) biến phụ thuộc có phân phối chuẩn, và ii) giá trị trung bình của biến phụ thuộc bằng một tổ hợp tuyến tính của các biến độc lập. Trong phần này của cuốn sách, chúng tôi sẽ thảo luận kỹ hơn vào cách tiếp cận để khắc phục các hạn chế kể trên.</p>
<ul>
<li><p>Thứ nhất, thay vì sử dụng phân phối chuẩn, mô hình tuyến tính tổng quát giả thiết rằng biến phụ thuộc có phân phối nằm trong họ các phân phối kiểu mũ (exponential family). Phân phối chuẩn chỉ là một trường hợp đặc biệt của họ các phân phối này.</p></li>
<li><p>Thứ hai, mô hình tuyến tính tổng quát sử dụng một hàm <span class="math inline">\(g\)</span>, được gọi là hàm liên kết, để mô tả mối liên hệ giữa giá trị trung bình của biến phụ thuộc với tổ hợp tuyến tính của các biến độc lập. Lựa chọn hàm <span class="math inline">\(g\)</span> có ý nghĩa quan trọng không chỉ trong cách luận giải kết quả của mô hình, mà còn ở việc dễ dàng ước lượng tham số của mô hình.</p></li>
</ul>
<div id="họ-các-biến-ngẫu-nhiên-có-phân-phối-kiểu-mũ." class="section level3" number="10.3.1">
<h3>
<span class="header-section-number">10.3.1</span> Họ các biến ngẫu nhiên có phân phối kiểu mũ.<a class="anchor" aria-label="anchor" href="#h%E1%BB%8D-c%C3%A1c-bi%E1%BA%BFn-ng%E1%BA%ABu-nhi%C3%AAn-c%C3%B3-ph%C3%A2n-ph%E1%BB%91i-ki%E1%BB%83u-m%C5%A9."><i class="fas fa-link"></i></a>
</h3>
<p>Thay vì giả thiết rằng <span class="math inline">\(Y\)</span> có phân phối chuẩn trong mô hình tuyến tính thông thường, mô hình tuyến tính tổng quát giả thiết biến phụ thuộc <span class="math inline">\(Y\)</span> nằm trong họ các biến ngẫu nhiên có phân phối kiểu mũ. Họ các biến ngẫu nhiên có phân phối kiểu mũ (exponential family) có hàm mật độ xác suất có thể viết dưới dạng như sau:
<span class="math display">\[\begin{align}
f(y;\theta,\phi) = \exp\left[ \cfrac{y \theta - b(\theta)}{a(\phi)} + c(y,\phi) \right]
\end{align}\]</span>
trong đó</p>
<ul>
<li>Tham số <span class="math inline">\(\theta\)</span> được gọi là tham số <span class="math inline">\(chính\)</span> <span class="math inline">\(tắc\)</span> của phân phối kiểu mũ.</li>
<li>Tham số <span class="math inline">\(\phi\)</span> được gọi là tham số <span class="math inline">\(phân\)</span> <span class="math inline">\(tán\)</span>. Nguyên nhân là do giá trị trung bình của biến ngẫu nhiên <span class="math inline">\(Y\)</span> không phụ thuộc vào <span class="math inline">\(\phi\)</span>. Tham số <span class="math inline">\(\phi\)</span>, mà tổng quát hơn là hàm <span class="math inline">\(a(\phi)\)</span> sẽ xác định phương sai của biến phụ thuộc.</li>
<li>Các hàm số <span class="math inline">\(b(\theta)\)</span>, <span class="math inline">\(a(\phi)\)</span> và <span class="math inline">\(c(y,\phi)\)</span> sẽ quyết định kiểu phân phối của biến phụ thuộc.</li>
</ul>
<p>Giá trị trung bình và phương sai của biến phụ thuộc <span class="math inline">\(Y\)</span> được cho bởi các công thức sau:
<span class="math display" id="eq:EF1">\[\begin{align}
&amp; \mathbb{E}(Y) = b^{'}(\theta) \\
&amp; \mathbb{V}(Y) = a(\phi) \cdot b^{''}(\theta)
\tag{10.23}
\end{align}\]</span>
với <span class="math inline">\(b^{'}(\theta)\)</span> và <span class="math inline">\(b^{''}(\theta)\)</span> lần lượt là đạo hàm bậc một và đạo hàm bậc hai của hàm số <span class="math inline">\(b\)</span> theo biến <span class="math inline">\(\theta\)</span>.</p>
<p>Họ các biến ngẫu nhiên có phân phối kiểu mũ bao gồm đa số các biến ngẫu nhiên liên tục thông thường như phân phối chuẩn, phân phối mũ, phân phối Gamma, phân phối chuẩn ngược. Các biến ngẫu nhiên phân phối rời rạc như phân phối nhị thức, phân phối binomial, hoặc phân phối Poisson cũng nằm trong họ các biến ngẫu nhiên có phân phối kiểu mũ.</p>
<ul>
<li><p>Ví dụ 1: phân phối Poisson thường được sử dụng để mô tả phân phối của biến đếm trong mô hình tuyến tính tổng quát. Hàm phân phối của biến ngẫu nhiên Poisson với tham số <span class="math inline">\(\lambda\)</span>, ký hiệu <span class="math inline">\(\mathcal{P}(\lambda)\)</span>, được cho bởi công thức
<span class="math display">\[\begin{align}
\mathbb{P}(Y = y; \lambda) = exp(-\lambda) \ \cfrac{\lambda^y}{y!}
\end{align}\]</span>
Chúng ta có thể viết phân phối <span class="math inline">\(\mathcal{P}(\lambda)\)</span> dưới dạng phân phối mũ như sau
<span class="math display">\[\begin{align}
\mathbb{P}(Y = y; \theta) = exp\left[ \cfrac{\theta y - exp(\theta)}{1} - log(\Gamma(y+1)) \right] \text{ với } \lambda = exp(\theta)
\end{align}\]</span>
Đây là hàm phân phối của biến ngẫu nhiên nằm trong họ các phân phối kiểu mũ với <span class="math inline">\(a(\phi) = 1\)</span>; <span class="math inline">\(b(\theta) = exp(\theta)\)</span> và <span class="math inline">\(c(y,\phi) = log\left(\Gamma(y+1)\right)\)</span>. Bạn đọc có thể tính toán trung bình và phương sai của phân phối <span class="math inline">\(\lambda\)</span> dựa theo công thức <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:EF1">(10.23)</a>
<span class="math display">\[\begin{align}
&amp; \mathbb{E}(Y) = b^{'}(\theta) = exp(\theta) = \lambda \\
&amp; \mathbb{V}(Y) = a(\phi) \cdot b^{''}(\theta) = 1 \cdot exp(\theta) = \lambda
\end{align}\]</span></p></li>
<li><p>Ví dụ 2: phân phối chuẩn là một biến ngẫu nhiên nằm trong họ các phân phối kiểu mũ. Thật vậy, chúng ta có hàm mật độ của biến ngẫu nhiên phân phối chuẩn với trung bình <span class="math inline">\(\mu\)</span> và độ lệch chuẩn <span class="math inline">\(\sigma\)</span>, ký hiệu <span class="math inline">\(\mathcal{N}(\mu,\sigma)\)</span>, như sau
<span class="math display">\[\begin{align}
f(y,\mu,\sigma) = \cfrac{1}{\sqrt{2 \pi \sigma^2}} \exp\left[ \cfrac{-(y - \mu)^2}{2 \ \sigma^2} \right]
\end{align}\]</span>
Hàm phân phối của <span class="math inline">\(\mathcal{N}(\mu,\sigma)\)</span> có thể được viết dưới dạng phân phối kiểu mũ
<span class="math display">\[\begin{align}
\cfrac{1}{\sqrt{2 \pi} \sigma} \exp\left[ \cfrac{-(y - \mu)^2}{2 \ \sigma^2} \right] &amp;= \exp\left[ \cfrac{-(y - \mu)^2}{2 \ \sigma^2} - \cfrac{1}{2} log(2 \pi \sigma^2) \right] \\
&amp;= \exp\left[ \cfrac{\mu y - \mu^2/2} {\sigma^2} - \cfrac{y^2}{2\sigma^2} - \cfrac{1}{2} log(2 \pi \sigma^2) \right]
\end{align}\]</span>
Với <span class="math inline">\(\theta = \mu\)</span> và <span class="math inline">\(\phi = \sigma^2\)</span> chúng ta có hàm mật độ của biến ngẫu nhiên <span class="math inline">\(\mathcal{N}(\mu,\sigma)\)</span> là hàm mật độ của biến ngẫu nhiên nằm trong họ các phân phối kiểu mũ, với <span class="math inline">\(a(\phi) = \phi\)</span>, <span class="math inline">\(b(\theta) = \theta^2/2\)</span> và
<span class="math display">\[\begin{align}
c(y,\phi) = -\cfrac{y^2}{2\phi} - \cfrac{1}{2} log(2 \pi \phi)
\end{align}\]</span>
Bạn đọc có thể kiểm tra giá trị trung bình và phương sai của phân phối <span class="math inline">\(\mathcal{N}(\mu,\sigma)\)</span> dựa theo công thức <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:EF1">(10.23)</a>
<span class="math display">\[\begin{align}
&amp; \mathbb{E}(Y) = b^{'}(\theta) = \theta = \mu \\
&amp; \mathbb{V}(Y) = a(\phi) \cdot b^{''}(\theta) = \phi \cdot 1 = \phi = \sigma^2
\end{align}\]</span></p></li>
<li><p>Ví dụ 3: phân phối <span class="math inline">\(Gamma(\alpha,\gamma)\)</span> nằm trong họ các phân phối kiểu mũ. Thật vậy
<span class="math display">\[\begin{align}
f(y) &amp;= \cfrac{\gamma^\alpha}{\Gamma(\alpha)} \ y^{\alpha-1} \ e^{-\gamma \cdot y} \\
&amp;= \exp\left[ -\gamma \cdot y + \alpha \log(\gamma) - \log(\Gamma(\alpha)) - (\alpha-1) \cdot \log(y)    \right]
\end{align}\]</span>
Với <span class="math inline">\(\theta = -\gamma/\alpha\)</span> và <span class="math inline">\(\phi = 1/\alpha\)</span> ta có
<span class="math display">\[\begin{align}
f(y) &amp; = \exp\left[ \cfrac{\theta y + \log(-\theta)}{1/\alpha} - \cfrac{\log(\alpha)}{1/\alpha} - \log(\Gamma(\alpha)) - (\alpha-1) \cdot \log(y)    \right] \\
&amp; = \exp\left[ \cfrac{\theta y + \log(-\theta)}{\phi} + \cfrac{\log(\phi)}{\phi} - \log(\Gamma(1/\phi)) - (1/\phi-1) \cdot \log(y)    \right]
\end{align}\]</span>
Chúng ta có phân phối kiểu mũ với <span class="math inline">\(a(\phi) = \phi\)</span>, <span class="math inline">\(b(\theta) = \log(-\theta)\)</span>, và
<span class="math display">\[\begin{align}
c(y,\phi) = \cfrac{\log(\phi)}{\phi} - \log(\Gamma(1/\phi)) - (1/\phi-1) \cdot \log(y)
\end{align}\]</span>
Chúng ta kiểm tra giá trị trung bình và phương sai của phân phối <span class="math inline">\(Gamma(\alpha,\beta)\)</span> theo công thức <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:EF1">(10.23)</a>
<span class="math display">\[\begin{align}
&amp; \mathbb{E}(Y) = b^{'}(\theta) = - \cfrac{1}{\theta} = \cfrac{\alpha}{\gamma} \\
&amp; \mathbb{V}(Y) = a(\phi) \cdot b^{''}(\theta) = \cfrac{1}{\alpha} \cdot \cfrac{\alpha^2}{\gamma^2} = \cfrac{\alpha}{\gamma^2}
\end{align}\]</span></p></li>
</ul>
<p>Trong trường hợp hàm số <span class="math inline">\(a(\phi)\)</span> là hàm số tuyến tính theo <span class="math inline">\(\phi\)</span>, nghĩa là tồn tại số <span class="math inline">\(\omega\)</span> sao cho <span class="math inline">\(a(\phi) = \cfrac{\phi}{\omega}\)</span> chúng ta có hàm mật độ của biến ngẫu nhiên có phân phối kiểu mũ như sau
<span class="math display">\[\begin{align}
f(y;\theta,\phi) = \exp\left[ \cfrac{y \theta - b(\theta)}{\phi/\omega} + c(y,\phi) \right]
\end{align}\]</span>
Giá trị trung bình và phương sai của biến ngẫu nhiên <span class="math inline">\(Y\)</span> trong trường hợp này được xác định như sau:
<span class="math display">\[\begin{align}
&amp; \mathbb{E}(Y) = b^{'}(\theta) \\
&amp; \mathbb{V}(Y) = \cfrac{\phi}{\omega} \cdot b^{''}(\theta)
\end{align}\]</span></p>
<p>Giả sử hàm <span class="math inline">\(b^{'}(.)\)</span> là hàm số đơn điệu và tồn tại hàm số ngược <span class="math inline">\({b^{'}}^{-1}(.)\)</span> thì <span class="math inline">\(\theta = {b^{'}}^{-1}\left(\mathbb{E}(Y)\right)\)</span>. Do đó mối liên hệ giữa phương sai của biến ngẫu nhiên <span class="math inline">\(Y\)</span> và giá trị trung bình của biến <span class="math inline">\(Y\)</span> được thể hiện qua công thức sau
<span class="math display">\[\begin{align}
\mathbb{V}(Y) = \cfrac{\phi}{\omega} \cdot b^{''}({b^{'}}^{-1}(\mathbb{E}(Y)))
\end{align}\]</span></p>
<p>Hàm số <span class="math inline">\(V(\cdot) = b^{''}({b^{'}}^{-1}(\cdot))\)</span> được gọi là hàm phương sai của phân phối kiểu mũ. Tại sao chúng ta cần định nghĩa một hàm số phức tạp như vậy? Bởi vì hàm <span class="math inline">\(V(\cdot)\)</span> là cơ sở để người xây dựng mô hình kiểm soát phương sai của biến ngẫu nhiên kiểu mũ.</p>
<p>Giả sử biến phụ thuộc quan sát được là <span class="math inline">\(Y_1, Y_2, \cdots, Y_n\)</span> có cùng phân phối kiểu mũ với cùng tham số <span class="math inline">\(\phi\)</span>, cùng hàm <span class="math inline">\(b(\cdot)\)</span> và <span class="math inline">\(c(\cdot)\)</span>, nhưng có giá trị <span class="math inline">\(\omega_i\)</span> khác nhau. Giá trị trung bình của biến <span class="math inline">\(Y_i\)</span>, ký hiệu là <span class="math inline">\(\mu_i\)</span> được giải thích thông qua các biến độc lập và không phụ thuộc vào <span class="math inline">\(\omega_i\)</span>, trong khi phương sai của biến <span class="math inline">\(Y_i\)</span> phụ thuộc vào <span class="math inline">\(\omega_i\)</span> và giá trị trung bình <span class="math inline">\(\mu_i\)</span>:
<span class="math display">\[\begin{align}
\mathbb{V}(Y_i) = \cfrac{\phi}{\omega_i} \cdot V(\mu_i)
\end{align}\]</span></p>
<p>Khi ước lượng mô hình tuyến tính tổng quát trên một dữ liệu cụ thể, giá trị hàm phương sai <span class="math inline">\(V\)</span> phụ thuộc vào cách chúng ta lựa chọn hàm <span class="math inline">\(b\)</span> và giá trị trung bình của <span class="math inline">\(Y_i\)</span>. Tham số <span class="math inline">\(\phi\)</span> không phụ thuộc vào quan sát <span class="math inline">\(Y_i\)</span>, do đó hệ số <span class="math inline">\(w_i\)</span> có ý nghĩa quyết định trong xác định phương sai của <span class="math inline">\(Y_i\)</span>. Chúng ta có thể lựa chọn đơn giản là cho <span class="math inline">\(w_i\)</span> bằng 1 với mọi <span class="math inline">\(i\)</span>, nếu chúng ta tin rằng tỷ lệ <span class="math inline">\(\cfrac{V(\mu_i)}{\mathbb{V}(Y_i)}\)</span> là hằng số. Trong một số trường hợp, <span class="math inline">\(\cfrac{V(\mu_i)}{\mathbb{V}(Y_i)}\)</span> thay đổi theo <span class="math inline">\(i\)</span>, đó là lúc chúng ta cần lựa chọn <span class="math inline">\(w_i\)</span> để cho kết quả tốt nhất. Chúng ta sẽ tiếp tục thảo luận về hàm phương sai của biến phụ thuộc trong phần hàm hợp lý tối đa của biến ngẫu nhiên nằm trong họ phân phối các phân phối kiểu mũ.</p>
</div>
<div id="hàm-liên-kết." class="section level3" number="10.3.2">
<h3>
<span class="header-section-number">10.3.2</span> Hàm liên kết.<a class="anchor" aria-label="anchor" href="#h%C3%A0m-li%C3%AAn-k%E1%BA%BFt."><i class="fas fa-link"></i></a>
</h3>
<p>Hàm số liên kết <span class="math inline">\(g(\cdot)\)</span> liên kết giá trị trung bình của biến phụ thuộc với tổ hợp tuyến tính của các biến độc lập luôn được lựa chọn trong nhóm các hàm số đơn điệu và có đạo hàm trên miền xác định của hàm số đó. Các giả thiết này đảm bảo để hàm liên kết có hàm số ngược <span class="math inline">\(g^{-1}(\cdot)\)</span> cũng là hàm đơn điệu và có đạo hàm trên miền xác định. Một yếu tố quan trọng khác khi lựa chọn hàm liên kết đó là <span class="math inline">\(g(\cdot)\)</span> có miền xác định trùng với miền xác định của giá trị trung bình của biến phụ thuộc và miền giá trị của <span class="math inline">\(g(\cdot)\)</span> là tập số thực <span class="math inline">\(\mathbb{R}\)</span>.</p>
<p>Xin được nhắc lại rằng mối liên hệ giữa trung bình của biến phụ thuộc và tổ hợp tuyến tính của biến độc lập được mô tả thông qua hàm liên kết như sau:
<span class="math display">\[\begin{align}
&amp; g(\mu_i) = \beta_0 + \beta_1 \cdot x_{i,1} +  \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,d} \\
&amp; \mu_i = g^{-1}\left( beta_0 + \beta_1 \cdot x_{i,1} +  \beta_2 \cdot x_{i,2} + \cdots + \beta_p \cdot x_{i,d} \right)
\end{align}\]</span></p>
<p>Danh sách các hàm số thường được sử dụng làm hàm liên kết được cho trong bảng dưới đây</p>
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:left;">
Tên hàm số
</th>
<th style="text-align:left;">
Hàm <span class="math inline">\(g(\mu)\)</span>
</th>
<th style="text-align:left;">
Hàm <span class="math inline">\(g^{-1}(\mu)\)</span>
</th>
<th style="text-align:left;">
Miền xác định
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Identily
</td>
<td style="text-align:left;">
<span class="math inline">\(\mu\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\mu\)</span>
</td>
<td style="text-align:left;">
(-,+)
</td>
</tr>
<tr>
<td style="text-align:left;">
Log
</td>
<td style="text-align:left;">
<span class="math inline">\(\log(\mu)\)</span>$
</td>
<td style="text-align:left;">
<span class="math inline">\(\exp(\mu)\)</span>
</td>
<td style="text-align:left;">
(0,+)
</td>
</tr>
<tr>
<td style="text-align:left;">
Logit
</td>
<td style="text-align:left;">
<span class="math inline">\(\log(\mu/(1-\mu)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(e^{\mu}/(1+e^\mu)\)</span>
</td>
<td style="text-align:left;">
(0,1)
</td>
</tr>
<tr>
<td style="text-align:left;">
Probit
</td>
<td style="text-align:left;">
<span class="math inline">\(\Phi^{-1}(\mu)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\Phi(\mu)\)</span>
</td>
<td style="text-align:left;">
(0,1)
</td>
</tr>
<tr>
<td style="text-align:left;">
Log-log
</td>
<td style="text-align:left;">
<span class="math inline">\(\log(-\log(1-\mu))\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(1 - \exp(-\exp(\mu))\)</span>
</td>
<td style="text-align:left;">
(0,1)
</td>
</tr>
<tr>
<td style="text-align:left;">
Inverse
</td>
<td style="text-align:left;">
<span class="math inline">\(1/\mu\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(1/\mu\)</span>
</td>
<td style="text-align:left;">
(-,+)/0
</td>
</tr>
<tr>
<td style="text-align:left;">
Inverse squared
</td>
<td style="text-align:left;">
<span class="math inline">\(1/\mu^2\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(1/\sqrt{\mu}\)</span>
</td>
<td style="text-align:left;">
(0,+)
</td>
</tr>
</tbody>
</table></div>
<ul>
<li><p>Ví dụ 1: khi <span class="math inline">\(Y\)</span> mô tả số lần khách hàng gửi yêu cầu bảo hiểm, giá trị trung bình của <span class="math inline">\(Y\)</span> sẽ là số thực dương. Các hàm số có miền xác định là tập các số thực dương sẽ phù hợp trong trường hợp này. Có thể thấy trong bảng trên các hàm <span class="math inline">\(g(\mu) = \log(\mu)\)</span> và hàm <span class="math inline">\(g(\mu) = 1/\mu^2\)</span> là các hàm số có thể lựa chọn là hàm liên kết.</p></li>
<li><p>Ví dụ 2: khi <span class="math inline">\(Y\)</span> mô tả khách hàng có gửi yêu cầu bảo hiểm hay không, hoặc mô tả sự kiện tai nạn có xảy ra hay không, giá trị trung bình của <span class="math inline">\(Y\)</span> nằm trong khoảng <span class="math inline">\((0,1)\)</span>. Do đó các hàm <span class="math inline">\(Logit\)</span>, hàm <span class="math inline">\(Probit\)</span>, hàm <span class="math inline">\(Log-Log\)</span>, hoặc hàm <span class="math inline">\(Cauchit\)</span> sẽ là lựa chọn phù hợp cho hàm liên kết.</p></li>
</ul>
<p>Khi lựa chọn hàm liên kết bạn đọc cần cân nhắc đến khả năng giải thích của mô hình và sự khó khăn có thể gặp phải khi ước lượng của tham số trong mô hình. Ví dụ như khi biến mục tiêu chỉ nhận giá trị 0 hoặc 1, hàm logit thường xuyên được sử dụng bởi vì khả năng giải thích tốt hơn hàm <span class="math inline">\(Probit\)</span> hay <span class="math inline">\(Log-Log\)</span>. Hoặc khi cân nhắc lựa chọn giữa hàm <span class="math inline">\(log\)</span> và hàm <span class="math inline">\(inverse\)</span> <span class="math inline">\(squared\)</span>, hàm <span class="math inline">\(log\)</span> thường được ưu tiên lựa chọn. Có thể so sánh mối liên hệ giữa <span class="math inline">\(\mu_i\)</span> với các biến độc lập như dưới đây thông qua hàm <span class="math inline">\(log\)</span> hoặc hàm <span class="math inline">\(inverse\)</span> <span class="math inline">\(squared\)</span> như sau
<span class="math display">\[\begin{align}
&amp;\text{ Hàm log: } \mu_i = exp(\beta_0) \cdot exp(\beta_1 \cdot x_{i,1}) \cdots exp(\beta_p \cdot x_{i,p}) \\
&amp;\text{ Inverse squared: } \mu_i = \cfrac{1}{\sqrt{\beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{i,p}}}
\end{align}\]</span>
Khi sử dụng hàm <span class="math inline">\(log\)</span>, mỗi biến độc lập tác động lên giá trị trung bình của biến phụ thuộc một cách độc lập với nhau theo quy tắc nhân, trong khi đó không dễ để đánh giá tác động của một biến độc lập lên biến phụ thuộc trong công thức của hàm <span class="math inline">\(inverse\)</span> <span class="math inline">\(squared\)</span>. Hay nói cách khác, sử dụng hàm <span class="math inline">\(log\)</span> thường sẽ dễ dàng giải thích kết quả hơn so với khi sử dụng hàm <span class="math inline">\(inverse\)</span> <span class="math inline">\(squared\)</span>.</p>
<p>Với <span class="math inline">\(Y\)</span> là biến ngẫu nhiên nằm trong họ các phân phối kiểu mũ ta có <span class="math inline">\(\mathbb{E}(Y_i) = b^{'}(\theta_i)\)</span>. Khi chúng ta lựa chọn hàm liên kết là <span class="math inline">\(g(\cdot) = (b^{'})^{-1}(\cdot)\)</span> thì mối liên hệ giữa tham số chính tắc <span class="math inline">\(\theta_i\)</span> với các biến độc lập sẽ là tuyến tính. Thật vậy,
<span class="math display">\[\begin{align}
&amp; \mu_i = g^{-1}(\theta_i) \\
&amp; g(\mu_i) = \beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{i,p}\\
&amp; \rightarrow \theta_i = \beta_0 + \beta_1 \cdot x_{i,1} + \beta_2 \cdot x_{i,2} \cdots + \beta_p \cdot x_{i,p}
\end{align}\]</span></p>
<p>Như vậy, với lựa chọn hàm liên kết <span class="math inline">\(g(\cdot) = (b^{'})^{-1}(\cdot)\)</span>, tham số chính tắc <span class="math inline">\(\theta_i\)</span> của biến ngẫu nhiên phân phối mũ <span class="math inline">\(Y_i\)</span> bằng tổ hợp tuyến tính của các biến độc lập. Trong trường hợp này, hàm liên kết <span class="math inline">\((b^{'})^{-1}(\cdot)\)</span> còn được gọi là hàm liên kết chính tắc của biến phụ thuộc <span class="math inline">\(Y\)</span>.</p>
<ul>
<li><p>Ví dụ 1: khi <span class="math inline">\(Y\)</span> là biến ngẫu nhiên có phân phối chuẩn <span class="math inline">\(\mathcal{N}(\mu, \sigma)\)</span>, chúng ta có <span class="math inline">\(b(\mu) = \mu^2/2\)</span> và <span class="math inline">\(b^{'}(\mu) = \mu\)</span> do đó hàm liên kết chính tắc của biến ngẫu nhiên phân phối chuẩn <span class="math inline">\(\mathcal{N}(\mu, \sigma)\)</span> là <span class="math inline">\(g(\mu) = \mu\)</span>.</p></li>
<li><p>Ví dụ 2: khi <span class="math inline">\(Y\)</span> là biến ngẫu nhiên có phân phối <span class="math inline">\(gamma(\alpha,\gamma)\)</span>, chúng ta có <span class="math inline">\(b(\mu) = \log(-\mu)\)</span>, và <span class="math inline">\(b^{'}(\mu) = -1/\mu\)</span>, do đó hàm liên kết chính tắc của biến ngẫu nhiên phân phối gamma là <span class="math inline">\(g(\mu) = -1/\mu\)</span>. Trong trường hợp này hàm liên kết không có miền xác định là tập các số thực dương. Có thể thấy rằng lựa chọn hàm liên kết chính tắc không phải là một lựa chọn phù hợp.</p></li>
</ul>
</div>
</div>
<div id="hàm-hợp-lý-tối-đa-và-ước-lượng-mô-hình." class="section level2" number="10.4">
<h2>
<span class="header-section-number">10.4</span> Hàm hợp lý tối đa và ước lượng mô hình.<a class="anchor" aria-label="anchor" href="#h%C3%A0m-h%E1%BB%A3p-l%C3%BD-t%E1%BB%91i-%C4%91a-v%C3%A0-%C6%B0%E1%BB%9Bc-l%C6%B0%E1%BB%A3ng-m%C3%B4-h%C3%ACnh."><i class="fas fa-link"></i></a>
</h2>
<p>Hệ số tuyến tính của các biến độc lập <span class="math inline">\(\boldsymbol{\beta} = (\beta_0, \beta_1, \cdots, \beta_p)\)</span> được ước lượng từ dữ liệu <span class="math inline">\(\textbf{y} = (y_1, y_2, \cdots y_n)\)</span> và <span class="math inline">\(\textbf{x} = (\textbf{x}_1, \textbf{x}_2, \cdots \textbf{x}_n)\)</span> bằng phương pháp tối đa hóa hàm hợp lý, hay còn gọi là hàm likelihood. Khi biến mục tiêu <span class="math inline">\(Y_i\)</span> có phân phối kiểu mũ, hàm likelihood được viết như sau
<span class="math display">\[\begin{align}
L(\textbf{y},\boldsymbol{\beta}) = \prod\limits_{i=1}^n \ \exp\left[ \cfrac{y_i \theta - b(\theta)}{a_i(\phi)} + c_i(y_i,\phi) \right]
\end{align}\]</span>
Trong hầu hết các trường hợp, chúng ta sẽ thực hiện tính toán trên hàm Log-likelihood thay vì hàm likelihood. Hàm Log-likelihood được ký hiệu <span class="math inline">\(l(\textbf{y},\beta)\)</span> được xác định như sau</p>
<p><span class="math display">\[\begin{align}
l(\textbf{y},\beta) &amp;= \log \left( \prod\limits_{i=1}^n \ \exp\left[ \cfrac{y_i \theta_i - b(\theta_i)}{a_i(\phi)} + c_i(y_i,\phi) \right] \right) \\
&amp;= \sum\limits_{i=1}^n  \left(\cfrac{y_i \theta_i - b(\theta_i)}{a_i(\phi)} + c_i(y_i,\phi)\right)
\end{align}\]</span>
Véc-tơ hệ số <span class="math inline">\(\boldsymbol{\beta}\)</span> được ước lượng sao cho giá trị của hàm Log-likelihood đạt giá trị lớn nhất. Như vậy <span class="math inline">\(\boldsymbol{\beta}\)</span> là nghiệm của hệ phương trình
<span class="math display">\[\begin{align}
\cfrac{\partial l(\textbf{y},\boldsymbol{\beta})}{\partial \beta_j} &amp; = 0 \ \ \forall j = 1,2, \cdots, p
\end{align}\]</span>
Lưu ý rằng <span class="math inline">\(b^{'}(\theta_i) = \mu_i\)</span> nên trong các thành phần của hàm mật độ xác suất của biến <span class="math inline">\(Y_i\)</span> chỉ có hàm số <span class="math inline">\(b(\cdot)\)</span> và tham số <span class="math inline">\(\theta_i\)</span> phụ thuộc vào hệ số <span class="math inline">\(\boldsymbol{\beta}\)</span>. Đạo hàm của hàm Log-likelihood theo <span class="math inline">\(\beta\)</span> có thể viết được như sau
<span class="math display">\[\begin{align}
\cfrac{\partial l(\textbf{y},\beta)}{\partial \beta_j} &amp; = \sum\limits_{i=1}^n  \cfrac{1}{a_i(\phi)} \left(y_i \cfrac{\partial \theta_i}{\partial \beta_j} - \cfrac{\partial b(\theta_i)}{\partial \beta_j} \right) \\
&amp; = \sum\limits_{i=1}^n  \cfrac{y_i - b^{'}(\theta_i)}{a_i(\phi)} \cfrac{\partial \theta_i}{\partial \beta_j}
\end{align}\]</span></p>
<p>Lưu ý rằng <span class="math inline">\(\mu_i = b^{'}(\theta_i)\)</span>, đo đó
<span class="math display">\[\begin{align}
\theta_i = (b^{'})^{-1}(\mu_i) = (b^{'})^{-1}\left(g^{-1}(\beta_0 + \beta_1 \cdot x_{i,1} + \cdots \beta_p \cdot x_{i,p})\right)
\end{align}\]</span>
đồng thời, đạo hàm của hàm ngược được của các hàm <span class="math inline">\(b^{'}(\cdot)\)</span> và <span class="math inline">\(g(\cdot)\)</span> được xác định như sau
<span class="math display">\[\begin{align}
&amp; \left((b^{'})^{-1}\right)^{'}(\mu_i) = \cfrac{1}{(b^{''}\left((b^{'})^{-1}(\mu_i)\right)} = \cfrac{1}{b^{''}(\theta_i)} \\
&amp; (g^{-1}(\psi_i))^{'} = \cfrac{1}{(g^{'}(g^{-1}(\psi_i))} =  \cfrac{1}{g^{'}(\mu_i)}
\end{align}\]</span>
với <span class="math inline">\(\psi_i = \beta_0 + \beta_1 \cdot x_{i,1} + \cdots \beta_p \cdot x_{i,p}\)</span>.</p>
<p>Như vậy, đạo hàm của <span class="math inline">\(\theta_i\)</span> theo <span class="math inline">\(\beta_j\)</span> được tính như sau
<span class="math display">\[\begin{align}
\cfrac{\partial \theta_i}{\partial \beta_j} = \cfrac{\partial (b^{'})^{-1}(g^{-1}(\psi_i(\beta_j)))}{\partial \beta_j} = \cfrac{x_{i,j}}{b^{''}(\theta_i) \cdot g^{'}(\mu_i)}
\end{align}\]</span></p>
<p>Ta có đạo hàm của hàm Log-likelihood theo các tham số <span class="math inline">\(\beta_j\)</span>
<span class="math display">\[\begin{align}
\cfrac{\partial l(\textbf{y},\beta)}{\partial \beta_j} = \sum\limits_{i=1}^n  \cfrac{(y_i - \mu_i) \cdot x_{i,j}}{a_i(\phi) \cdot b^{''}(\theta_i) \cdot g^{'}(\mu_i)}
\end{align}\]</span></p>
<p>Với lựa chọn <span class="math inline">\(a_i(\phi) = \cfrac{\phi}{\omega_i}\)</span>, do phương sai của biến phụ thuộc là <span class="math inline">\(a_i(\phi) \cdot b^{''}(\theta_i)\)</span> nên ta có thể viết hàm Log-likelihood theo các tham số <span class="math inline">\(\beta_j\)</span> theo giá trị trung bình và phương sai của biến phụ thuộc
<span class="math display">\[\begin{align}
\cfrac{\partial l(\textbf{y},\boldsymbol{\beta})}{\partial \beta_j} &amp;= \sum\limits_{i=1}^n  \cfrac{(y_i - \mu_i) \cdot x_{i,j}}{\mathbb{V}(y_i) \cdot g^{'}(\mu_i)} \\
&amp; = \sum\limits_{i=1}^n w_i \cfrac{(y_i - \mu_i) \cdot x_{i,j}}{\phi V(\mu_i) \cdot g^{'}(\mu_i)} \\
&amp; =\cfrac{1}{\phi} \sum\limits_{i=1}^n w_i \cfrac{x_{i,j}}{V(\mu_i) \cdot g^{'}(\mu_i)} (y_i - \mu_i)
\end{align}\]</span>
Có thể thầy rằng:</p>
<ul>
<li><p>Thứ nhất, <span class="math inline">\(\beta_j\)</span> là nghiệm của phương trình <span class="math inline">\(\cfrac{\partial l(\textbf{y},\beta)}{\partial \beta_j} = 0\)</span> sẽ không phụ thuộc vào giá trị của tham số phân tán <span class="math inline">\(\phi\)</span>.</p></li>
<li><p>Thứ hai, giá trị của <span class="math inline">\(\mu_i\)</span> phụ thuộc vào giá trị của các biến độc lập <span class="math inline">\(\textbf{x}_i\)</span> và phụ thuộc vào các hệ số <span class="math inline">\(\boldsymbol{\beta}\)</span>, do đó giá trị <span class="math inline">\(\cfrac{x_{i,j}}{V(\mu_i) \cdot g^{'}(\mu_i)}\)</span> không phụ thuộc hoàn toàn vào cách chúng ta xây dựng mô hình.</p></li>
<li><p>Thứ ba, giá trị <span class="math inline">\(w_i\)</span> không phụ thuộc vào dữ liệu do đó có thể được sử dụng linh hoạt để ước lượng mô hình có kết quả tốt nhất.</p></li>
</ul>
<p>Giải hệ phương trình với ẩn là véc-tơ tham số <span class="math inline">\(\boldsymbol{\beta}\)</span> như trên thường phải sử dụng các phương pháp giải số. Phương pháp thường được sử dụng là thuật toán Newton Raphson.</p>
<p>Hàm <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> sử dụng xuyên suốt trong chương sách cho phép bạn đọc ước lượng mô hình tuyến tính tổng quát cho đa số các phân phối thường gặp của <span class="math inline">\(Y_i\)</span>. Tham số <span class="math inline">\(weight\)</span> trong hàm <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> là véc-tơ tham số <span class="math inline">\(w_i\)</span> như chúng ta đã trình bày ở trên. Lựa chọn giá trị cho <span class="math inline">\(w_i\)</span> hoàn toàn do cách tiếp cận của người xây dựng mô hình.</p>
<ul>
<li><p>Ví dụ 1: khi lựa chọn <span class="math inline">\(Y_i\)</span> có phân phối Poisson với tham số <span class="math inline">\(\lambda_i = exp(\theta_i)\)</span> và hàm liên kết là hàm <span class="math inline">\(g(\cdot) = log(\cdot)\)</span>. Chúng ta có <span class="math inline">\(a(\phi) = 1\)</span> do đó <span class="math inline">\(w_i = 1 \forall i\)</span>.
<span class="math display">\[\begin{align}
&amp; g(\mu_i) = log(\mu_i) \rightarrow g^{'}(\mu_i) = 1/\mu_i \\
&amp; b(\theta) = exp(\theta) \rightarrow b^{'}(\theta) = b^{''}(\theta) = exp(\theta) \rightarrow (b^{'})^{-1}(\theta) = \log(\theta) \rightarrow V(\theta) = b^{''}(b^{'})^{-1})(\theta) = \theta
\end{align}\]</span>
Đạo hàm của hàm Log-likelihood theo <span class="math inline">\(\beta_j\)</span> trở thành
<span class="math display">\[\begin{align}
\sum\limits_{i=1}^n w_i \cdot \cfrac{x_{i,j}}{\phi V(\mu_i) \cdot g^{'}(\mu_i)} (y_i - \mu_i) &amp;= \sum\limits_{i=1}^n x_{i,j} (y_i - \mu_i) \\
&amp;= \sum\limits_{i=1}^n x_{i,j} \left[y_i - \exp(\beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{i,p})\right]
\end{align}\]</span>
hay nói một cách khác, véc-tơ tham số <span class="math inline">\(\beta\)</span> để tối đa hóa giá trị của hàm Log-likelihood là nghiệm của hệ phương trình
<span class="math display">\[\begin{align}
\sum\limits_{i=1}^n x_{i,j} \left[y_i - \exp \left(\beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{i,p} \right) \right] = 0 \ \forall j
\end{align}\]</span></p></li>
<li><p>Ví dụ 2: khi <span class="math inline">\(Y_i\)</span> có phân phối Gamma với tham số <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\gamma_i\)</span> chúng ta có <span class="math inline">\(b(\theta_i) = log(-\theta_i)\)</span> với <span class="math inline">\(\theta_i = - \cfrac{\gamma_i}{\alpha}\)</span> đồng thời <span class="math inline">\(a(\phi) = \phi\)</span> do đó <span class="math inline">\(w_i = 1\)</span> <span class="math inline">\(\forall i\)</span>. Giả sử hàm liên kết được lựa chọn là hàm <span class="math inline">\(log\)</span>: <span class="math inline">\(g(\cdot) = log(\cdot)\)</span>.
<span class="math display">\[\begin{align}
&amp; g(\mu_i) = log(\mu_i) \rightarrow g^{'}(\mu_i) = 1/\mu_i \\
&amp; b(\theta_i) = log(-\theta_i) \rightarrow b^{'}(\theta_i) = -1/\theta_i \rightarrow b^{''}(\theta) = 1/\theta^2 \rightarrow (b^{'})^{-1}(\theta) = -1/\theta \rightarrow V(\mu) = b^{''}(b^{'})^{-1})(\mu) = \mu^2
\end{align}\]</span>
Đạo hàm của hàm Log-likelihood theo <span class="math inline">\(\beta_j\)</span> trở thành
<span class="math display">\[\begin{align}
\sum\limits_{i=1}^n w_i \cdot \cfrac{x_{i,j}}{\phi V(\mu_i) \cdot g^{'}(\mu_i)} (y_i - \mu_i) &amp;= \sum\limits_{i=1}^n \cfrac{x_{i,j}}{\mu_i} (y_i - \mu_i)
\end{align}\]</span>
véc-tơ tham số <span class="math inline">\(\boldsymbol{\beta}\)</span> để tối đa hóa giá trị của hàm Log-likelihood là nghiệm của hệ phương trình
<span class="math display">\[\begin{align}
\sum\limits_{i=1}^n x_{i,j} \left\{y_i \cdot \exp\left[-(\beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{i,p}) \right] - 1 \right\} = 0 \ \forall j
\end{align}\]</span></p></li>
<li><p>Ví dụ 3: khi <span class="math inline">\(Y_i\)</span> là số tiền bồi thường trung bình cho 1 tai nạn trong vòng 1 năm của một khách hàng, biết rằng khách hàng được bồi thường <span class="math inline">\(n_i\)</span> lần trong năm và số tiền bồi thường của một vụ tai nạn là biến ngẫu nhiên <span class="math inline">\(Y^*_i\)</span> phân phối Gamma với tham số <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta_i\)</span>. Do <span class="math inline">\(Y_i\)</span> là giá trị trung bình của <span class="math inline">\(n_i\)</span> biến phân phối Gamma độc lập với cùng tham số <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta_i\)</span> nên <span class="math inline">\(Y_i\)</span> sẽ có phân phối Gamma với tham số <span class="math inline">\((n_i \alpha)\)</span> và <span class="math inline">\((n_i \beta_i)\)</span>. Khi viết <span class="math inline">\(Y_i\)</span> dưới dạng phân phối kiểu mũ, chúng ta có <span class="math inline">\(b(\theta_i) = log(-\theta_i)\)</span> với <span class="math inline">\(\theta_i = - \cfrac{\beta_i}{\alpha}\)</span> và <span class="math inline">\(a(\phi) = \phi/n_i\)</span>. Véc-tơ tham số <span class="math inline">\(\boldsymbol{\beta}\)</span> để tối đa hóa giá trị của hàm Log-likelihood là nghiệm của hệ phương trình
<span class="math display">\[\begin{align}
\sum\limits_{i=1}^n n_i \cdot \ x_{i,j} \cdot  \left[y_i \cdot \exp\left(-(\beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{i,p}) \right) - 1 \right] = 0 \ \forall j
\end{align}\]</span></p></li>
</ul>
</div>
<div id="so-sánh-và-lựa-chọn-mô-hình-tuyến-tính-tổng-quát." class="section level2" number="10.5">
<h2>
<span class="header-section-number">10.5</span> So sánh và lựa chọn mô hình tuyến tính tổng quát.<a class="anchor" aria-label="anchor" href="#so-s%C3%A1nh-v%C3%A0-l%E1%BB%B1a-ch%E1%BB%8Dn-m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t."><i class="fas fa-link"></i></a>
</h2>
<p>Nắm được các nguyên tắc chung bạn đọc có thể tự xây dựng nhiều mô hình tuyến tính tổng quát khác nhau cho một dữ liệu cụ thể. Thách thức đặt ra là một mô hình liệu có thực sự có tốt hơn các mô hình khác, hay trong số các mô hình bạn lựa chọn mô hình nào là phù hợp nhất? Phần này của chương sẽ thảo luận về vấn đề so sánh mô hình và lựa chọn mô hình. Các chỉ tiêu thống kê được sủ dụng để so sánh mô hình sẽ xoay quanh giá trị của hàm hợp lý tối đa, bao gồm có thước đo deviance, chỉ tiêu AIC, AICC, hay BIC.</p>
<div id="thước-đo-deviance" class="section level3" number="10.5.1">
<h3>
<span class="header-section-number">10.5.1</span> Thước đo deviance<a class="anchor" aria-label="anchor" href="#th%C6%B0%E1%BB%9Bc-%C4%91o-deviance"><i class="fas fa-link"></i></a>
</h3>
<p>Thước đo được gọi là deviance thường được sử dụng để đánh giá và so sánh các mô hình tuyến tính tổng quát có cùng phân phối của biến độc lập. Chỉ tiêu này được tính toán dựa trên giá trị hàm Log-likelihood. Khi <span class="math inline">\(Y\)</span> là biến ngẫu nhiên trong nhóm các phân phối mũ, hàm log-likelihood được viết như sau
<span class="math display">\[\begin{align}
l(\textbf{y},\theta) &amp; = \sum\limits_{i=1}^n  \left(\cfrac{y_i \theta_i - b(\theta_i)}{a_i(\phi)} + c_i(y_i,\phi)\right)
\end{align}\]</span>
với <span class="math inline">\(\boldsymbol{\theta}\)</span> là véc-tơ các tham số chính tắc, <span class="math inline">\(\boldsymbol{\theta} = (\theta_1, \theta_2, \cdots, \theta_n)\)</span>. Sau khi phân phối của <span class="math inline">\(Y\)</span> và hàm liên kết được lựa chọn, chúng ta ước lượng được véc-tơ tham số <span class="math inline">\(\boldsymbol{\beta}\)</span> là hệ số của các biến độc lập bằng cách tối đa hóa hàm log-likelihood. Sau khi đã xác định được véc-tơ tham số <span class="math inline">\(\boldsymbol{\beta}\)</span>, với mỗi lựa chọn cho phân phối của <span class="math inline">\(Y\)</span> và hàm liên kết, chúng ta sẽ tính toán được các tham số chính tắc của mô hình tuyến tính tổng quát. Nếu hàm liên kết được lựa chọn là hàm liên kết chính tắc, <span class="math inline">\(g(\cdot) = (b^{'})^{-1}(\cdot)\)</span>, chúng ta có các tham số chính tắc chính là tổ hợp tuyến tính của các biến độc lập <span class="math inline">\(\boldsymbol{\theta}^M = (\theta^M_1, \theta^M_2, \cdots, \theta^M_n)\)</span> với
<span class="math display" id="eq:compa1">\[\begin{align}
\theta^M_i = \beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{i,p}
\tag{10.24}
\end{align}\]</span></p>
<p>Với mỗi lựa chọn cho mô hình tuyến tính tổng quát, bao gồm lựa chọn cho phân phối của <span class="math inline">\(Y\)</span> và hàm liên kết <span class="math inline">\(g\)</span>, tạm gọi là mô hình <span class="math inline">\(M\)</span>, chúng ta gọi <span class="math inline">\(l(\textbf{y},\boldsymbol{\theta}^M)\)</span> là giá trị của hàm Log-likelihood tại tham số <span class="math inline">\(\boldsymbol{\theta}^M\)</span> được xác định qua phương trình <a href="m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t..html#eq:compa1">(10.24)</a>. Lưu ý rằng véc-tơ <span class="math inline">\(\boldsymbol{\theta}^M\)</span> có độ dài là <span class="math inline">\(n\)</span>, bằng với kích thước của dữ liệu, tuy nhiên các tham số này được tính toán từ <span class="math inline">\((p+1)\)</span> giá trị <span class="math inline">\(\beta\)</span> ước lượng được và giá trị của biến độc lập.</p>
<p>Điều gì xảy ra nếu tham số chính tắc <span class="math inline">\(\boldsymbol{\theta}\)</span> hoàn toàn tự do và không phụ thuộc vào biến độc lập? Hàm Log-likelihood sẽ đạt giá trị cực đại tại <span class="math inline">\(\theta^S = (\theta^S_1, \theta^S_2, \cdots, \theta^S_n)\)</span> với <span class="math inline">\(\theta^S_i\)</span> là giá trị sao cho đạo hàm của hàm Log-likelihood tại <span class="math inline">\(\theta^S_i\)</span> bằng 0. Do <span class="math inline">\(\theta\)</span> hoàn toàn tự do nên chỉ có thành phần thứ <span class="math inline">\(i\)</span> của hàm Log-likelihood phụ thuộc vào <span class="math inline">\(\theta^S_i\)</span>
<span class="math display">\[\begin{align}
\cfrac{\partial l(\textbf{y},\theta)}{\partial \theta_i} &amp; =  \cfrac{y_i - b^{'}(\theta_i)}{a_i(\phi)}
\end{align}\]</span>
Cho đạo hàm của <span class="math inline">\(l(\textbf{y},\theta)\)</span> theo <span class="math inline">\(\theta_i\)</span> bằng 0 chúng ta có <span class="math inline">\(y_i - b^{'}(\theta^S_i) = 0\)</span> hay <span class="math inline">\(\theta^S_i = (b^{'})^{-1}(y_i)\)</span>.</p>
<p>Bạn đọc lưu ý rằng giá trị hàm Log-likelihood đạt cực đại tại <span class="math inline">\(\boldsymbol{\theta}^S\)</span> không có nghĩa là tham số <span class="math inline">\(\boldsymbol{\theta}^S\)</span> là lựa chọn tốt nhất cho mô hình tuyến tính tổng quát bởi tham số có đến <span class="math inline">\(n\)</span> bậc tự do. <span class="math inline">\(\boldsymbol{\theta}^S\)</span> cho chúng ta thông tin về giá trị cận trên của <span class="math inline">\(l(\textbf{y},\theta)\)</span> khi <span class="math inline">\(\theta\)</span> thay đổi. Thước đo deviance của mô hình <span class="math inline">\(M\)</span>, ký hiệu <span class="math inline">\(D*(y,\theta^M)\)</span> được định nghĩa là hai lần khoảng cách từ <span class="math inline">\(l(\textbf{y},\boldsymbol{\theta}^M)\)</span> đến giá trị tối đa <span class="math inline">\(l(\textbf{y},\boldsymbol{\theta}^S)\)</span>. Deviance của một mô hình cho biết mô hình được lựa chọn gần với phân phối quan sát được như thế nào, và mô hình có deviance càng nhỏ thì càng giải thích tốt hơn biến phụ thuộc
<span class="math display">\[\begin{align}
D^{*}(y, \theta^M) &amp;= 2 \left( l(\textbf{y},\theta^S) - l(\textbf{y},\theta^M) \right) \\
&amp; = 2 \sum\limits_{i=1}^n  \cfrac{y_i (\theta^S_i - \theta^M_i) - (b(\theta^S_i) - b(\theta^M_i))}{a_i(\phi)}
\end{align}\]</span></p>
<p>Trong trường hợp hàm <span class="math inline">\(a_i(\phi)\)</span> là tuyến tính theo <span class="math inline">\(\phi\)</span>; <span class="math inline">\(a_i(\phi) = \cfrac{\phi}{w_i}\)</span>, ta có
<span class="math display">\[\begin{align}
D^{*}(y, \theta^M) &amp; = \cfrac{1}{\phi} \sum\limits_{i=1}^n 2w_i \cdot \left[y_i (\theta^S_i - \theta^M_i) - (b(\theta^S_i) - b(\theta^M_i)) \right]  = \cfrac{D(y, \theta^M)}{\phi}
\end{align}\]</span>
với
<span class="math display">\[\begin{align}
D(y, \theta^M) &amp; = \sum\limits_{i=1}^n 2w_i \cdot \left[y_i (\theta^S_i - \theta^M_i) - (b(\theta^S_i) - b(\theta^M_i)) \right]
\end{align}\]</span>
trong đó <span class="math inline">\(D(y, \theta^M)\)</span> là thước đo deviance bỏ qua ảnh hưởng của tham số dispersion <span class="math inline">\(\phi\)</span>.</p>
<ul>
<li><p>Ví dụ 1: biến mục tiêu <span class="math inline">\(Y_i\)</span> có phân phối chuẩn: <span class="math inline">\(Y_i \sim \mathcal{N}(\mu_i, \sigma)\)</span> và hàm liên kết <span class="math inline">\(g(x) = x\)</span>. Có thể viết hàm mật độ của <span class="math inline">\(Y_i\)</span> dưới dạng phân phối mũ như sau
<span class="math display">\[\begin{align}
f(y, \theta_i, \phi) &amp; = \exp\left[ \cfrac{\theta_i y - \theta_i^2/2} {\phi} - \cfrac{y^2}{2\phi} - \cfrac{1}{2} log(2 \pi \phi) \right]
\end{align}\]</span>
với <span class="math inline">\(\theta_i = \mu_i\)</span> và <span class="math inline">\(\phi = \sigma^2\)</span>. Ta có <span class="math inline">\(\theta^S_i = (b^{'})^{-1}(y_i) = y_i\)</span>, do đó deviance tính trên quan sát <span class="math inline">\(\textbf{y}\)</span> được xác định như sau
<span class="math display">\[\begin{align}
D(y, \theta^M) &amp; = \sum\limits_{i=1}^n 2 \cdot \left[y_i (\theta^S_i - \theta^M_i) - (b(\theta^S_i) - b(\theta^M_i)) \right] \\
&amp; = \sum\limits_{i=1}^n (y_i - \theta^M_i)^2 \\
&amp; = \sum\limits_{i=1}^n \left[y_i -  (\beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{p,1}) \right]^2
\end{align}\]</span>
Trong trường hợp hồi quy tuyến tính thông thường, deviance chính là tổng bình phương sai số.</p></li>
<li><p>Ví dụ 2: biến mục tiêu <span class="math inline">\(Y_i\)</span> có phân phối Poisson <span class="math inline">\(Y_i \sim \mathcal{P}(\lambda_i)\)</span> và hàm liên kết <span class="math inline">\(g(\cdot) = log(\cdot)\)</span>.
<span class="math display">\[\begin{align}
f(y; \theta_i) = exp\left[ \cfrac{\theta_i y - exp(\theta_i)}{1} - log(\Gamma(y+1)) \right] \text{ với } \lambda_i = exp(\theta_i)
\end{align}\]</span>
Ta có <span class="math inline">\(\theta^S_i = (b^{'})^{-1}(y_i) = log(y_i)\)</span>, do đó deviance tính trên quan sát <span class="math inline">\(\textbf{y}\)</span> được xác định như sau
<span class="math display">\[\begin{align}
D(y, \theta^M) &amp; = \sum\limits_{i=1}^n 2 \cdot \left[y_i (\theta^S_i - \theta^M_i) - (b(\theta^S_i) - b(\theta^M_i)) \right] \\
&amp; = \sum\limits_{i=1}^n 2 \cdot \left[y_i (log(y_i) - \theta^M_i) - (y_i - exp(\theta^M_i)) \right] \\
&amp; = \sum\limits_{i=1}^n 2 \cdot \left[y_i \left(log(y_i) - log(\mu^M_i)\right) - (y_i - \mu^M_i) \right]
\end{align}\]</span>
với <span class="math inline">\(\mu^M_i = \exp(\beta_0 + \beta_1 \cdot x_{i,1} + \cdots + \beta_p \cdot x_{p,1})\)</span>.</p></li>
</ul>
<p>Kết quả ước lượng khi sử dụng hàm <code><a href="https://rdrr.io/r/stats/glm.html">glm()</a></code> trong R hiển thị hai giá trị là Null deviance và Residual deviance. Null deviance được tính toán với giả thiết là chỉ có hệ số chặn <span class="math inline">\(\beta_0\)</span>, còn Residual deviance được tính toán với véc-tơ <span class="math inline">\(\boldsymbol{\beta}\)</span> đầy đủ.</p>
<p>Giá trị Residual deviance ngoài sử dụng để so sánh hai mô hình có cùng phân phối của biến phụ thuộc còn được sử dụng để lựa chọn biến trong mô hình. Giả sử hai mô hình <span class="math inline">\(M1\)</span> và <span class="math inline">\(M2\)</span> có cùng phân phối cho biến phụ thuộc và có cùng hàm liên kết <span class="math inline">\(g(.)\)</span>, mô hình <span class="math inline">\(M1\)</span> có <span class="math inline">\(m_1\)</span> biến độc lập trong khi mô hình <span class="math inline">\(M_2\)</span> có <span class="math inline">\(m_2\)</span> biến độc lập, bao gồm tất cả các biến độc lập của mô hình <span class="math inline">\(M1\)</span>. Nói một cách khác, <span class="math inline">\(M_2\)</span> có nhiều hơn <span class="math inline">\(M_1\)</span> là <span class="math inline">\((m_2 - m_1)\)</span> biến độc lập. Mô hình <span class="math inline">\(M_2\)</span> sẽ có deviance lớn hơn mô hình <span class="math inline">\(M_1\)</span> do có nhiều biến độc lập hơn, tuy nhiên việc thêm <span class="math inline">\((m_2 - m_1)\)</span> biến độc lập vào mô hình có ý nghĩa thống kê nếu hiệu số giữa <span class="math inline">\(D^*(y, \theta^{M_2})\)</span> và <span class="math inline">\(D^*(y, \theta^{M_1})\)</span> là đủ lớn.</p>
<p>Có thể chứng minh được rằng khi kích thước dữ liệu đủ lớn, hiệu số giữa <span class="math inline">\(D^*(y, \theta^{M_2})\)</span> và <span class="math inline">\(D^*(y, \theta^{M_1})\)</span> là một biến ngẫu nhiên phân phối xấp xỉ phân phối <span class="math inline">\(\chi^2\)</span> với bậc tự do <span class="math inline">\((m_2 - m_1)\)</span>
<span class="math display">\[\begin{align}
D^{*}(y, \theta^{M_1}) - D^{*}(y, \theta^{M_2}) = 2 \cdot \log\left( \cfrac{L(y,\theta^{M_2})}{L(y,\theta^{M_1})} \right) \sim \chi^2(m_2 - m_1)
\end{align}\]</span></p>
<ul>
<li>Ví dụ 3: trong dữ liệu <span class="math inline">\(exposure.csv\)</span>, khi biến <span class="math inline">\(Claim\_Count\)</span> được giả thiết có phân phối Poisson và giá trị trung bình được giải thích bằng độ tuổi, hoặc giới tính của người được bảo hiểm, hoặc cả hai biến. Chúng ta gọi mô hình <span class="math inline">\(M_1\)</span> là mô hình mà giá trị trung bình của biến phụ thuộc được giải thích bằng biến độ tuổi, mô hình <span class="math inline">\(M_2\)</span> là mô hình mà giá trị trung bình của biến phụ thuộc được giải thích bằng cả biến giới tính, và mô hình <span class="math inline">\(M_3\)</span> là mô hình mà biến phụ thuộc phụ thuộc vào cả độ tuổi và giới tính của khách hàng.</li>
</ul>
<div class="sourceCode" id="cb659"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD/Dataset/exposure.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">glm_M1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Claim_Count</span><span class="op">~</span><span class="va">Age</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link<span class="op">=</span><span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span><span class="va">glm_M2</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Claim_Count</span><span class="op">~</span><span class="va">Gender</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link<span class="op">=</span><span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span><span class="va">glm_M3</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Claim_Count</span><span class="op">~</span><span class="va">Age</span><span class="op">+</span><span class="va">Gender</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link<span class="op">=</span><span class="st">"log"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm_M1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm_M2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm_M3</span><span class="op">)</span></span></code></pre></div>
Giá trị residual deviance của ba mô hình được tổng hợp ở bảng dưới đây
<div class="inline-table"><table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:center;">
Mô hình
</th>
<th style="text-align:center;">
Biến phụ thuộc
</th>
<th style="text-align:center;">
Deviance
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;border-left:1px solid;width: 2; font-weight: bold;border-right:1px solid;">
<span class="math inline">\(M_1\)</span>
</td>
<td style="text-align:center;border-left:1px solid;">
Age
</td>
<td style="text-align:center;border-left:1px solid;">
8324.2
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;width: 2; font-weight: bold;border-right:1px solid;">
<span class="math inline">\(M_2\)</span>
</td>
<td style="text-align:center;border-left:1px solid;">
Gender
</td>
<td style="text-align:center;border-left:1px solid;">
8540.5
</td>
</tr>
<tr>
<td style="text-align:center;border-left:1px solid;width: 2; font-weight: bold;border-right:1px solid;">
<span class="math inline">\(M_3\)</span>
</td>
<td style="text-align:center;border-left:1px solid;">
Age, Gender
</td>
<td style="text-align:center;border-left:1px solid;">
8316.8
</td>
</tr>
</tbody>
</table></div>
<p>Mô hình <span class="math inline">\(M_1\)</span> và <span class="math inline">\(M_2\)</span> đều chỉ có một biến độc lập và <span class="math inline">\(M_1\)</span> có deviance nhỏ hơn <span class="math inline">\(M_2\)</span> do đó mô hình <span class="math inline">\(M_1\)</span> tốt hơn <span class="math inline">\(M_2\)</span>. So sánh mô hình <span class="math inline">\(M_1\)</span> với 1 biến độc lập là <span class="math inline">\(Age\)</span> với mô hình <span class="math inline">\(M_3\)</span> có 2 biến độc lập là <span class="math inline">\(Age\)</span> và <span class="math inline">\(Gender\)</span> cần dựa trên kiểm định <span class="math inline">\(\chi^2\)</span>. Ta có <span class="math inline">\(D^{*}(y, \theta^{M_1}) - D^{*}(y, \theta^{M_2}) = 8324.2 - 8316.8 = 7.4\)</span>. Giá trị 7.4 tương ứng với mức xác suất <span class="math inline">\(0.994\)</span> của phân phối <span class="math inline">\(\chi^2(1)\)</span>. Điều này có ý nghĩa là ở mức độ tin cậy 99%, có thể kết luận rằng thêm biến <span class="math inline">\(Gender\)</span> vào mô hình <span class="math inline">\(M_1\)</span> là có ý nghĩa thống kê, tuy nhiên việc thêm biến <span class="math inline">\(Gender\)</span> lại không có ý nghĩa thống kê ở mức độ tin cậy <span class="math inline">\(99.5\%\)</span>.</p>
</div>
<div id="giá-trị-hàm-log-likelihood-aic-và-bic" class="section level3" number="10.5.2">
<h3>
<span class="header-section-number">10.5.2</span> Giá trị hàm log-likelihood, AIC và BIC<a class="anchor" aria-label="anchor" href="#gi%C3%A1-tr%E1%BB%8B-h%C3%A0m-log-likelihood-aic-v%C3%A0-bic"><i class="fas fa-link"></i></a>
</h3>
<p>Deviance là một thước đo hữu ích trong so sánh các mô hình có cùng phân phối của biến phụ thuộc và hàm liên kết. Khi các mô hình cần so sánh không có chung phân phối của biến phụ thuộc thì hiệu giữa hai hàm log-likelihood sẽ không có phân phối <span class="math inline">\(\chi^2\)</span> và khi đó việc so sánh các mô hình là không thế thực hiện được.</p>
<p>Trong phần trước, chúng ta đã định nghĩa <span class="math inline">\(l(y,\theta^M)\)</span> là giá trị tối đa của hàm log-likelihood cho mô hình M với tập hợp các biến độc lập đã lựa chọn. Nhìn chung, giá trị của <span class="math inline">\(l(y,\theta^M)\)</span> không cho biết nhiều thông tin về độ phù hợp của mô hình, nhưng người xây dựng mô hình thường mong muốn giá trị này càng lớn thì càng tốt. Tuy nhiên, có một vấn đề khi so sánh trực tiếp giá trị <span class="math inline">\(l(y,\theta^M)\)</span> giữa các mô hình là: một mô hình bao gồm nhiều biến độc lập hơn thì rất có thể có giá trị <span class="math inline">\(l(y,\theta^M)\)</span> lớn hơn. Để giải quyết vấn đề này, có ba thước đo được điều chỉnh từ <span class="math inline">\(l(y,\theta^M)\)</span> thường được sử dụng cho mô hình tuyến tính tổng quát với mục đích đánh giá và so sánh giữa các mô hình là AIC, AICC và BIC.</p>
<p>Chỉ tiêu AIC, viết tắt của Akaike information criterion, là chỉ tiêu đơn giản nhất được tính toán từ công thức như sau
<span class="math display">\[\begin{align}
AIC = 2 \left(-l(y,\theta^M)+r\right)
\end{align}\]</span>
trong đó <span class="math inline">\(r\)</span> là số lượng tham số cần ước lượng trong mô hình. Giá trị <span class="math inline">\(AIC\)</span> càng nhỏ thì mô hình càng khớp hơn với dữ liệu.</p>
<p>Chỉ tiêu AICC (hoặc AICs) được điều chỉnh từ AIC, được sử dụng khi kích thước dữ liệu không quá lớn để thay thế cho AIC, và được tính bởi công thức như sau
<span class="math display">\[\begin{align}
AICC = AIC + \cfrac{2r(r+1)}{n-r-1}
\end{align}\]</span>
Khi kích thước dữ liệu <span class="math inline">\(n\)</span> lớn, AIC và AICC sẽ tương đương nhau do <span class="math inline">\(\cfrac{2r(r+1)}{n-r-1}\)</span> nhỏ.</p>
<p>Chỉ tiêu thứ ba là BIC, là viết tắt của Bayesian information criterion. Trong một vài tài liệu BIC còn được gọi là SBC. Cũng giống như AIC và AICC, BIC là chỉ tiêu được tính toán từ giá trị cực đại của hàm log-likelihood điểu chỉnh để phản ánh số lượng tham số sử dụng trong mô hình là nhiều hay ít
<span class="math display">\[\begin{align}
BIC = 2 \left(-l(y,\theta^M)+r log(n)\right)
\end{align}\]</span></p>
<p>Cơ sở lý thuyết cho các chỉ tiêu AIC, AICC, và BIC bạn đọc có thể tìm thấy trong bất kỳ tài liệu thống kê toán nào, do đó chúng tôi sẽ không trình bày trong cuốn sách này. Chúng tôi muốn nhấn mạnh vào góc độ ứng dụng của các chỉ tiêu này khi sử dụng để so sánh các mô hình.</p>
<ul>
<li>Ví dụ 1: chúng ta quay trở lại dữ liệu “MotoInsurance.csv” khi biến mục tiêu <span class="math inline">\(Y\)</span> chỉ nhận hai giá trị là “No” hoặc “Yes”. Biến <span class="math inline">\(Y\)</span> có thể là biến dạng nhị phân hoặc vừa có thể là biến dạng đếm nếu chúng ta cho tương đương giá trị “No” tương đương với 0 và giá trị “Yes” tương ứng với 1. Khi xây dựng mô hình tuyến tính tổng quát, chúng ta có thể sử dụng phân phối Poisson cho biến mục tiêu với hàm liên kết <span class="math inline">\(g(\cdot) = log(\cdot)\)</span>.</li>
</ul>
<div class="sourceCode" id="cb660"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"../KHDL_KTKD/Dataset/MotoInsurance.csv"</span><span class="op">)</span></span>
<span><span class="va">dat</span><span class="op">$</span><span class="va">Y</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">Y</span><span class="op">==</span><span class="st">"Yes"</span>,<span class="fl">1</span>,<span class="fl">0</span><span class="op">)</span></span>
<span><span class="va">dat</span><span class="op">$</span><span class="va">sex</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">sex</span><span class="op">)</span></span>
<span><span class="va">dat</span><span class="op">$</span><span class="va">urban</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">urban</span><span class="op">)</span></span>
<span><span class="va">glm.pois</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span><span class="op">~</span><span class="va">age</span><span class="op">+</span><span class="va">sex</span><span class="op">+</span><span class="va">urban</span><span class="op">+</span><span class="va">seniority</span>,data<span class="op">=</span><span class="va">dat</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">poisson</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"log"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm.pois</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Y ~ age + sex + urban + seniority, family = poisson(link = "log"), 
##     data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0824  -0.7362  -0.5465   0.5711   1.9556  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.286511   0.105615  -2.713  0.00667 ** 
## age         -0.034131   0.002546 -13.406  &lt; 2e-16 ***
## sexM        -0.491418   0.057331  -8.572  &lt; 2e-16 ***
## urban1       0.625032   0.053999  11.575  &lt; 2e-16 ***
## seniority    0.070888   0.004257  16.652  &lt; 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 2938.1  on 3999  degrees of freedom
## Residual deviance: 2418.7  on 3995  degrees of freedom
## AIC: 5202.7
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Do <span class="math inline">\(Y\)</span> là biến nhị phân nên một cách tự nhiên, bạn đọc sẽ cân nhắc sử dụng phân phối nhị phân cho <span class="math inline">\(Y\)</span>. Chúng ta xây dựng mô hình tuyến tính tổng quát với phân phối nhị thức cho <span class="math inline">\(Y\)</span> và hàm liên kết là hàm <span class="math inline">\(logit\)</span>. Thay vì sử dụng cả 4 biến độc lập, chúng ta chỉ sử dụng hai biến độc lập là <span class="math inline">\(age\)</span> và <span class="math inline">\(sex\)</span>,</p>
<div class="sourceCode" id="cb662"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span><span class="op">$</span><span class="va">Y</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">Y</span><span class="op">)</span> <span class="co"># đổi biến Y thành factor</span></span>
<span><span class="va">glm.binom.logit</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span><span class="op">~</span><span class="va">age</span><span class="op">+</span><span class="va">sex</span>,data<span class="op">=</span><span class="va">dat</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"logit"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm.binom.logit</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Y ~ age + sex, family = binomial(link = "logit"), 
##     data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4544  -0.9261  -0.7396   1.2607   2.0088  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.109828   0.130876   8.480   &lt;2e-16 ***
## age         -0.026603   0.002709  -9.822   &lt;2e-16 ***
## sexM        -0.723479   0.076585  -9.447   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 5163.3  on 3999  degrees of freedom
## Residual deviance: 4935.3  on 3997  degrees of freedom
## AIC: 4941.3
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Tương tự như mô hình <span class="math inline">\(glm.pois\)</span>, mô hình <span class="math inline">\(glm.binom.logit\)</span> cũng có tất cả các hệ số của biến độc lập khác 0. Làm thế nào để biết rằng mô hình <span class="math inline">\(glm.pois\)</span> sử dụng phân phối Poisson với 4 biến độc lập hay mô hình <span class="math inline">\(glm.binom.logit\)</span> với phân phối nhị thức cho <span class="math inline">\(Y\)</span> và 2 biến độc lập là tốt hơn? Nếu chúng ta sử dụng thước đo deviance thì kết quả sẽ không chính xác vì các mô hình có phân phối của biến phụ thuộc khác nhau. Chỉ tiêu <span class="math inline">\(AIC\)</span> được tính toán sẵn từ hàm <span class="math inline">\(glm\)</span> có thể được sử dụng để so sánh hai mô hình trong trường hợp này. Chỉ tiêu AIC của <span class="math inline">\(glm.pois\)</span> là 5202.7 trong khi chỉ tiêu AIC của <span class="math inline">\(glm.binom.logit\)</span> là 4941.3. Mô hình <span class="math inline">\(glm.binom.logit\)</span> có AIC nhỏ hơn nên sẽ tốt hơn để mô hình hóa dữ liệu trong trường hợp này.</p>
<ul>
<li>Ví dụ 2: chúng ta sẽ tiếp tục với dữ liệu “MotoInsurance.csv”. Một cách tự nhiên, khi sử dụng phân phối nhị thức cho biến phụ thuộc, bạn đọc sử dụng hàm liên kết là hàm <span class="math inline">\(logit\)</span>. Liệu lựa chọn này có là tốt nhất để mô hình hóa dữ liệu mà chúng ta đang nghiên cứu? Bạn đọc có thể sử dụng chỉ tiêu AIC để lựa chọn hàm liên kết phù hợp. Chúng ta sẽ sử dụng 4 biến độc lập là <span class="math inline">\(age\)</span>, <span class="math inline">\(sex\)</span>, <span class="math inline">\(urban\)</span>, và <span class="math inline">\(seniority\)</span> để giải thích giá trị trung bình của biến phụ thuộc khi xây dựng mô hình</li>
</ul>
<div class="sourceCode" id="cb664"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">glm.binom.logit</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span><span class="op">~</span><span class="va">age</span><span class="op">+</span><span class="va">sex</span><span class="op">+</span><span class="va">seniority</span><span class="op">+</span><span class="va">urban</span>,data<span class="op">=</span><span class="va">dat</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"logit"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">glm.binom.probit</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span><span class="op">~</span><span class="va">age</span><span class="op">+</span><span class="va">sex</span><span class="op">+</span><span class="va">seniority</span><span class="op">+</span><span class="va">urban</span>,data<span class="op">=</span><span class="va">dat</span>, family <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/family.html">binomial</a></span><span class="op">(</span>link <span class="op">=</span> <span class="st">"probit"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm.binom.logit</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Y ~ age + sex + seniority + urban, family = binomial(link = "logit"), 
##     data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4424  -0.8115  -0.5046   1.0440   2.7439  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.793757   0.144541   5.492 3.98e-08 ***
## age         -0.058754   0.003525 -16.668  &lt; 2e-16 ***
## sexM        -0.983040   0.085377 -11.514  &lt; 2e-16 ***
## seniority    0.133569   0.006808  19.618  &lt; 2e-16 ***
## urban1       1.174515   0.078060  15.046  &lt; 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 5163.3  on 3999  degrees of freedom
## Residual deviance: 4295.8  on 3995  degrees of freedom
## AIC: 4305.8
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb666"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">glm.binom.probit</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Y ~ age + sex + seniority + urban, family = binomial(link = "probit"), 
##     data = dat)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4931  -0.8168  -0.4987   1.0639   2.9359  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  0.449579   0.085724   5.244 1.57e-07 ***
## age         -0.034482   0.002009 -17.163  &lt; 2e-16 ***
## sexM        -0.577303   0.050821 -11.360  &lt; 2e-16 ***
## seniority    0.077888   0.003890  20.021  &lt; 2e-16 ***
## urban1       0.697759   0.046129  15.126  &lt; 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 5163.3  on 3999  degrees of freedom
## Residual deviance: 4292.4  on 3995  degrees of freedom
## AIC: 4302.4
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Mô hình <span class="math inline">\(glm.binom.probit\)</span> có deviance và AIC nhỏ hơn <span class="math inline">\(glm.binom.logit\)</span>, điều này cho biết sử dụng hàm liên kết <span class="math inline">\(probit\)</span> sẽ cho kết quả tốt hơn so với hàm liên kết <span class="math inline">\(logit\)</span>.</p>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="m%C3%B4-h%C3%ACnh-h%E1%BB%93i-quy-tuy%E1%BA%BFn-t%C3%ADnh.html"><span class="header-section-number">9</span> Mô hình hồi quy tuyến tính</a></div>
<div class="next"><a href="reference.html"><span class="header-section-number">11</span> REFERENCE</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t."><span class="header-section-number">10</span> Mô hình tuyến tính tổng quát.</a></li>
<li><a class="nav-link" href="#c%C3%A1c-nh%C6%B0%E1%BB%A3c-%C4%91i%E1%BB%83m-c%E1%BB%A7a-m%C3%B4-h%C3%ACnh-h%E1%BB%93i-quy-tuy%E1%BA%BFn-t%C3%ADnh."><span class="header-section-number">10.1</span> Các nhược điểm của mô hình hồi quy tuyến tính.</a></li>
<li>
<a class="nav-link" href="#x%C3%A2y-d%E1%BB%B1ng-m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t"><span class="header-section-number">10.2</span> Xây dựng mô hình tuyến tính tổng quát</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-l%C3%A0-bi%E1%BA%BFn-d%E1%BA%A1ng-nh%E1%BB%8B-ph%C3%A2n."><span class="header-section-number">10.2.1</span> Biến phụ thuộc là biến dạng nhị phân.</a></li>
<li><a class="nav-link" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-l%C3%A0-bi%E1%BA%BFn-r%E1%BB%9Di-r%E1%BA%A1c-kh%C3%B4ng-c%C3%B3-th%E1%BB%A9-t%E1%BB%B1."><span class="header-section-number">10.2.2</span> Biến phụ thuộc là biến rời rạc không có thứ tự.</a></li>
<li><a class="nav-link" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-l%C3%A0-bi%E1%BA%BFn-r%E1%BB%9Di-r%E1%BA%A1c-c%C3%B3-th%E1%BB%A9-t%E1%BB%B1."><span class="header-section-number">10.2.3</span> Biến phụ thuộc là biến rời rạc có thứ tự.</a></li>
<li><a class="nav-link" href="#bi%E1%BA%BFn-ph%E1%BB%A5-thu%E1%BB%99c-c%C3%B3-ph%C3%A2n-ph%E1%BB%91i-li%C3%AAn-t%E1%BB%A5c."><span class="header-section-number">10.2.4</span> Biến phụ thuộc có phân phối liên tục.</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#c%C3%A1c-th%C3%A0nh-ph%E1%BA%A7n-c%E1%BB%A7a-m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t."><span class="header-section-number">10.3</span> Các thành phần của mô hình tuyến tính tổng quát.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#h%E1%BB%8D-c%C3%A1c-bi%E1%BA%BFn-ng%E1%BA%ABu-nhi%C3%AAn-c%C3%B3-ph%C3%A2n-ph%E1%BB%91i-ki%E1%BB%83u-m%C5%A9."><span class="header-section-number">10.3.1</span> Họ các biến ngẫu nhiên có phân phối kiểu mũ.</a></li>
<li><a class="nav-link" href="#h%C3%A0m-li%C3%AAn-k%E1%BA%BFt."><span class="header-section-number">10.3.2</span> Hàm liên kết.</a></li>
</ul>
</li>
<li><a class="nav-link" href="#h%C3%A0m-h%E1%BB%A3p-l%C3%BD-t%E1%BB%91i-%C4%91a-v%C3%A0-%C6%B0%E1%BB%9Bc-l%C6%B0%E1%BB%A3ng-m%C3%B4-h%C3%ACnh."><span class="header-section-number">10.4</span> Hàm hợp lý tối đa và ước lượng mô hình.</a></li>
<li>
<a class="nav-link" href="#so-s%C3%A1nh-v%C3%A0-l%E1%BB%B1a-ch%E1%BB%8Dn-m%C3%B4-h%C3%ACnh-tuy%E1%BA%BFn-t%C3%ADnh-t%E1%BB%95ng-qu%C3%A1t."><span class="header-section-number">10.5</span> So sánh và lựa chọn mô hình tuyến tính tổng quát.</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#th%C6%B0%E1%BB%9Bc-%C4%91o-deviance"><span class="header-section-number">10.5.1</span> Thước đo deviance</a></li>
<li><a class="nav-link" href="#gi%C3%A1-tr%E1%BB%8B-h%C3%A0m-log-likelihood-aic-v%C3%A0-bic"><span class="header-section-number">10.5.2</span> Giá trị hàm log-likelihood, AIC và BIC</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/dgrtwo/tidy-text-mining/blob/master/10-mo-hinh-tuyen-tinh-tong-quat.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/dgrtwo/tidy-text-mining/edit/master/10-mo-hinh-tuyen-tinh-tong-quat.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong></strong>" was written by . </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
